// Code generated by ent, DO NOT EDIT.

package memoryentry

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/lx-wnk/kontor/server/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldUpdatedAt, v))
}

// SpaceID applies equality check predicate on the "space_id" field. It's identical to SpaceIDEQ.
func SpaceID(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldSpaceID, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldSummary, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldContent, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldKind, v))
}

// SourceKind applies equality check predicate on the "source_kind" field. It's identical to SourceKindEQ.
func SourceKind(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldSourceKind, v))
}

// SourceRef applies equality check predicate on the "source_ref" field. It's identical to SourceRefEQ.
func SourceRef(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldSourceRef, v))
}

// Confidence applies equality check predicate on the "confidence" field. It's identical to ConfidenceEQ.
func Confidence(v float64) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldConfidence, v))
}

// ValidFrom applies equality check predicate on the "valid_from" field. It's identical to ValidFromEQ.
func ValidFrom(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldValidFrom, v))
}

// ValidUntil applies equality check predicate on the "valid_until" field. It's identical to ValidUntilEQ.
func ValidUntil(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldValidUntil, v))
}

// SupersededBy applies equality check predicate on the "superseded_by" field. It's identical to SupersededByEQ.
func SupersededBy(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldSupersededBy, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldUserID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLTE(FieldUpdatedAt, v))
}

// SpaceIDEQ applies the EQ predicate on the "space_id" field.
func SpaceIDEQ(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldSpaceID, v))
}

// SpaceIDNEQ applies the NEQ predicate on the "space_id" field.
func SpaceIDNEQ(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNEQ(FieldSpaceID, v))
}

// SpaceIDIn applies the In predicate on the "space_id" field.
func SpaceIDIn(vs ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIn(FieldSpaceID, vs...))
}

// SpaceIDNotIn applies the NotIn predicate on the "space_id" field.
func SpaceIDNotIn(vs ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotIn(FieldSpaceID, vs...))
}

// SpaceIDGT applies the GT predicate on the "space_id" field.
func SpaceIDGT(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGT(FieldSpaceID, v))
}

// SpaceIDGTE applies the GTE predicate on the "space_id" field.
func SpaceIDGTE(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGTE(FieldSpaceID, v))
}

// SpaceIDLT applies the LT predicate on the "space_id" field.
func SpaceIDLT(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLT(FieldSpaceID, v))
}

// SpaceIDLTE applies the LTE predicate on the "space_id" field.
func SpaceIDLTE(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLTE(FieldSpaceID, v))
}

// SpaceIDContains applies the Contains predicate on the "space_id" field.
func SpaceIDContains(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldContains(FieldSpaceID, v))
}

// SpaceIDHasPrefix applies the HasPrefix predicate on the "space_id" field.
func SpaceIDHasPrefix(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldHasPrefix(FieldSpaceID, v))
}

// SpaceIDHasSuffix applies the HasSuffix predicate on the "space_id" field.
func SpaceIDHasSuffix(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldHasSuffix(FieldSpaceID, v))
}

// SpaceIDEqualFold applies the EqualFold predicate on the "space_id" field.
func SpaceIDEqualFold(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEqualFold(FieldSpaceID, v))
}

// SpaceIDContainsFold applies the ContainsFold predicate on the "space_id" field.
func SpaceIDContainsFold(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldContainsFold(FieldSpaceID, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldContainsFold(FieldSummary, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldContainsFold(FieldContent, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldContainsFold(FieldKind, v))
}

// SourceKindEQ applies the EQ predicate on the "source_kind" field.
func SourceKindEQ(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldSourceKind, v))
}

// SourceKindNEQ applies the NEQ predicate on the "source_kind" field.
func SourceKindNEQ(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNEQ(FieldSourceKind, v))
}

// SourceKindIn applies the In predicate on the "source_kind" field.
func SourceKindIn(vs ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIn(FieldSourceKind, vs...))
}

// SourceKindNotIn applies the NotIn predicate on the "source_kind" field.
func SourceKindNotIn(vs ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotIn(FieldSourceKind, vs...))
}

// SourceKindGT applies the GT predicate on the "source_kind" field.
func SourceKindGT(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGT(FieldSourceKind, v))
}

// SourceKindGTE applies the GTE predicate on the "source_kind" field.
func SourceKindGTE(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGTE(FieldSourceKind, v))
}

// SourceKindLT applies the LT predicate on the "source_kind" field.
func SourceKindLT(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLT(FieldSourceKind, v))
}

// SourceKindLTE applies the LTE predicate on the "source_kind" field.
func SourceKindLTE(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLTE(FieldSourceKind, v))
}

// SourceKindContains applies the Contains predicate on the "source_kind" field.
func SourceKindContains(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldContains(FieldSourceKind, v))
}

// SourceKindHasPrefix applies the HasPrefix predicate on the "source_kind" field.
func SourceKindHasPrefix(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldHasPrefix(FieldSourceKind, v))
}

// SourceKindHasSuffix applies the HasSuffix predicate on the "source_kind" field.
func SourceKindHasSuffix(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldHasSuffix(FieldSourceKind, v))
}

// SourceKindEqualFold applies the EqualFold predicate on the "source_kind" field.
func SourceKindEqualFold(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEqualFold(FieldSourceKind, v))
}

// SourceKindContainsFold applies the ContainsFold predicate on the "source_kind" field.
func SourceKindContainsFold(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldContainsFold(FieldSourceKind, v))
}

// SourceRefEQ applies the EQ predicate on the "source_ref" field.
func SourceRefEQ(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldSourceRef, v))
}

// SourceRefNEQ applies the NEQ predicate on the "source_ref" field.
func SourceRefNEQ(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNEQ(FieldSourceRef, v))
}

// SourceRefIn applies the In predicate on the "source_ref" field.
func SourceRefIn(vs ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIn(FieldSourceRef, vs...))
}

// SourceRefNotIn applies the NotIn predicate on the "source_ref" field.
func SourceRefNotIn(vs ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotIn(FieldSourceRef, vs...))
}

// SourceRefGT applies the GT predicate on the "source_ref" field.
func SourceRefGT(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGT(FieldSourceRef, v))
}

// SourceRefGTE applies the GTE predicate on the "source_ref" field.
func SourceRefGTE(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGTE(FieldSourceRef, v))
}

// SourceRefLT applies the LT predicate on the "source_ref" field.
func SourceRefLT(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLT(FieldSourceRef, v))
}

// SourceRefLTE applies the LTE predicate on the "source_ref" field.
func SourceRefLTE(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLTE(FieldSourceRef, v))
}

// SourceRefContains applies the Contains predicate on the "source_ref" field.
func SourceRefContains(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldContains(FieldSourceRef, v))
}

// SourceRefHasPrefix applies the HasPrefix predicate on the "source_ref" field.
func SourceRefHasPrefix(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldHasPrefix(FieldSourceRef, v))
}

// SourceRefHasSuffix applies the HasSuffix predicate on the "source_ref" field.
func SourceRefHasSuffix(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldHasSuffix(FieldSourceRef, v))
}

// SourceRefIsNil applies the IsNil predicate on the "source_ref" field.
func SourceRefIsNil() predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIsNull(FieldSourceRef))
}

// SourceRefNotNil applies the NotNil predicate on the "source_ref" field.
func SourceRefNotNil() predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotNull(FieldSourceRef))
}

// SourceRefEqualFold applies the EqualFold predicate on the "source_ref" field.
func SourceRefEqualFold(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEqualFold(FieldSourceRef, v))
}

// SourceRefContainsFold applies the ContainsFold predicate on the "source_ref" field.
func SourceRefContainsFold(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldContainsFold(FieldSourceRef, v))
}

// ConfidenceEQ applies the EQ predicate on the "confidence" field.
func ConfidenceEQ(v float64) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldConfidence, v))
}

// ConfidenceNEQ applies the NEQ predicate on the "confidence" field.
func ConfidenceNEQ(v float64) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNEQ(FieldConfidence, v))
}

// ConfidenceIn applies the In predicate on the "confidence" field.
func ConfidenceIn(vs ...float64) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIn(FieldConfidence, vs...))
}

// ConfidenceNotIn applies the NotIn predicate on the "confidence" field.
func ConfidenceNotIn(vs ...float64) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotIn(FieldConfidence, vs...))
}

// ConfidenceGT applies the GT predicate on the "confidence" field.
func ConfidenceGT(v float64) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGT(FieldConfidence, v))
}

// ConfidenceGTE applies the GTE predicate on the "confidence" field.
func ConfidenceGTE(v float64) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGTE(FieldConfidence, v))
}

// ConfidenceLT applies the LT predicate on the "confidence" field.
func ConfidenceLT(v float64) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLT(FieldConfidence, v))
}

// ConfidenceLTE applies the LTE predicate on the "confidence" field.
func ConfidenceLTE(v float64) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLTE(FieldConfidence, v))
}

// ValidFromEQ applies the EQ predicate on the "valid_from" field.
func ValidFromEQ(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldValidFrom, v))
}

// ValidFromNEQ applies the NEQ predicate on the "valid_from" field.
func ValidFromNEQ(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNEQ(FieldValidFrom, v))
}

// ValidFromIn applies the In predicate on the "valid_from" field.
func ValidFromIn(vs ...time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIn(FieldValidFrom, vs...))
}

// ValidFromNotIn applies the NotIn predicate on the "valid_from" field.
func ValidFromNotIn(vs ...time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotIn(FieldValidFrom, vs...))
}

// ValidFromGT applies the GT predicate on the "valid_from" field.
func ValidFromGT(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGT(FieldValidFrom, v))
}

// ValidFromGTE applies the GTE predicate on the "valid_from" field.
func ValidFromGTE(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGTE(FieldValidFrom, v))
}

// ValidFromLT applies the LT predicate on the "valid_from" field.
func ValidFromLT(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLT(FieldValidFrom, v))
}

// ValidFromLTE applies the LTE predicate on the "valid_from" field.
func ValidFromLTE(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLTE(FieldValidFrom, v))
}

// ValidUntilEQ applies the EQ predicate on the "valid_until" field.
func ValidUntilEQ(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldValidUntil, v))
}

// ValidUntilNEQ applies the NEQ predicate on the "valid_until" field.
func ValidUntilNEQ(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNEQ(FieldValidUntil, v))
}

// ValidUntilIn applies the In predicate on the "valid_until" field.
func ValidUntilIn(vs ...time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIn(FieldValidUntil, vs...))
}

// ValidUntilNotIn applies the NotIn predicate on the "valid_until" field.
func ValidUntilNotIn(vs ...time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotIn(FieldValidUntil, vs...))
}

// ValidUntilGT applies the GT predicate on the "valid_until" field.
func ValidUntilGT(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGT(FieldValidUntil, v))
}

// ValidUntilGTE applies the GTE predicate on the "valid_until" field.
func ValidUntilGTE(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGTE(FieldValidUntil, v))
}

// ValidUntilLT applies the LT predicate on the "valid_until" field.
func ValidUntilLT(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLT(FieldValidUntil, v))
}

// ValidUntilLTE applies the LTE predicate on the "valid_until" field.
func ValidUntilLTE(v time.Time) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLTE(FieldValidUntil, v))
}

// ValidUntilIsNil applies the IsNil predicate on the "valid_until" field.
func ValidUntilIsNil() predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIsNull(FieldValidUntil))
}

// ValidUntilNotNil applies the NotNil predicate on the "valid_until" field.
func ValidUntilNotNil() predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotNull(FieldValidUntil))
}

// SupersededByEQ applies the EQ predicate on the "superseded_by" field.
func SupersededByEQ(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldSupersededBy, v))
}

// SupersededByNEQ applies the NEQ predicate on the "superseded_by" field.
func SupersededByNEQ(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNEQ(FieldSupersededBy, v))
}

// SupersededByIn applies the In predicate on the "superseded_by" field.
func SupersededByIn(vs ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIn(FieldSupersededBy, vs...))
}

// SupersededByNotIn applies the NotIn predicate on the "superseded_by" field.
func SupersededByNotIn(vs ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotIn(FieldSupersededBy, vs...))
}

// SupersededByGT applies the GT predicate on the "superseded_by" field.
func SupersededByGT(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGT(FieldSupersededBy, v))
}

// SupersededByGTE applies the GTE predicate on the "superseded_by" field.
func SupersededByGTE(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGTE(FieldSupersededBy, v))
}

// SupersededByLT applies the LT predicate on the "superseded_by" field.
func SupersededByLT(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLT(FieldSupersededBy, v))
}

// SupersededByLTE applies the LTE predicate on the "superseded_by" field.
func SupersededByLTE(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLTE(FieldSupersededBy, v))
}

// SupersededByContains applies the Contains predicate on the "superseded_by" field.
func SupersededByContains(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldContains(FieldSupersededBy, v))
}

// SupersededByHasPrefix applies the HasPrefix predicate on the "superseded_by" field.
func SupersededByHasPrefix(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldHasPrefix(FieldSupersededBy, v))
}

// SupersededByHasSuffix applies the HasSuffix predicate on the "superseded_by" field.
func SupersededByHasSuffix(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldHasSuffix(FieldSupersededBy, v))
}

// SupersededByIsNil applies the IsNil predicate on the "superseded_by" field.
func SupersededByIsNil() predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIsNull(FieldSupersededBy))
}

// SupersededByNotNil applies the NotNil predicate on the "superseded_by" field.
func SupersededByNotNil() predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotNull(FieldSupersededBy))
}

// SupersededByEqualFold applies the EqualFold predicate on the "superseded_by" field.
func SupersededByEqualFold(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEqualFold(FieldSupersededBy, v))
}

// SupersededByContainsFold applies the ContainsFold predicate on the "superseded_by" field.
func SupersededByContainsFold(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldContainsFold(FieldSupersededBy, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldNotNull(FieldUserID))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.FieldContainsFold(FieldUserID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MemoryEntry) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MemoryEntry) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MemoryEntry) predicate.MemoryEntry {
	return predicate.MemoryEntry(sql.NotPredicates(p))
}
