// Code generated by ent, DO NOT EDIT.

package permissionrequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/lx-wnk/kontor/server/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldContainsFold(FieldID, id))
}

// StageRunID applies equality check predicate on the "stage_run_id" field. It's identical to StageRunIDEQ.
func StageRunID(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEQ(FieldStageRunID, v))
}

// Tool applies equality check predicate on the "tool" field. It's identical to ToolEQ.
func Tool(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEQ(FieldTool, v))
}

// Pattern applies equality check predicate on the "pattern" field. It's identical to PatternEQ.
func Pattern(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEQ(FieldPattern, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEQ(FieldReason, v))
}

// Outcome applies equality check predicate on the "outcome" field. It's identical to OutcomeEQ.
func Outcome(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEQ(FieldOutcome, v))
}

// RequestedAt applies equality check predicate on the "requested_at" field. It's identical to RequestedAtEQ.
func RequestedAt(v time.Time) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEQ(FieldRequestedAt, v))
}

// ResolvedAt applies equality check predicate on the "resolved_at" field. It's identical to ResolvedAtEQ.
func ResolvedAt(v time.Time) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEQ(FieldResolvedAt, v))
}

// StageRunIDEQ applies the EQ predicate on the "stage_run_id" field.
func StageRunIDEQ(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEQ(FieldStageRunID, v))
}

// StageRunIDNEQ applies the NEQ predicate on the "stage_run_id" field.
func StageRunIDNEQ(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldNEQ(FieldStageRunID, v))
}

// StageRunIDIn applies the In predicate on the "stage_run_id" field.
func StageRunIDIn(vs ...string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldIn(FieldStageRunID, vs...))
}

// StageRunIDNotIn applies the NotIn predicate on the "stage_run_id" field.
func StageRunIDNotIn(vs ...string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldNotIn(FieldStageRunID, vs...))
}

// StageRunIDGT applies the GT predicate on the "stage_run_id" field.
func StageRunIDGT(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldGT(FieldStageRunID, v))
}

// StageRunIDGTE applies the GTE predicate on the "stage_run_id" field.
func StageRunIDGTE(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldGTE(FieldStageRunID, v))
}

// StageRunIDLT applies the LT predicate on the "stage_run_id" field.
func StageRunIDLT(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldLT(FieldStageRunID, v))
}

// StageRunIDLTE applies the LTE predicate on the "stage_run_id" field.
func StageRunIDLTE(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldLTE(FieldStageRunID, v))
}

// StageRunIDContains applies the Contains predicate on the "stage_run_id" field.
func StageRunIDContains(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldContains(FieldStageRunID, v))
}

// StageRunIDHasPrefix applies the HasPrefix predicate on the "stage_run_id" field.
func StageRunIDHasPrefix(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldHasPrefix(FieldStageRunID, v))
}

// StageRunIDHasSuffix applies the HasSuffix predicate on the "stage_run_id" field.
func StageRunIDHasSuffix(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldHasSuffix(FieldStageRunID, v))
}

// StageRunIDEqualFold applies the EqualFold predicate on the "stage_run_id" field.
func StageRunIDEqualFold(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEqualFold(FieldStageRunID, v))
}

// StageRunIDContainsFold applies the ContainsFold predicate on the "stage_run_id" field.
func StageRunIDContainsFold(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldContainsFold(FieldStageRunID, v))
}

// ToolEQ applies the EQ predicate on the "tool" field.
func ToolEQ(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEQ(FieldTool, v))
}

// ToolNEQ applies the NEQ predicate on the "tool" field.
func ToolNEQ(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldNEQ(FieldTool, v))
}

// ToolIn applies the In predicate on the "tool" field.
func ToolIn(vs ...string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldIn(FieldTool, vs...))
}

// ToolNotIn applies the NotIn predicate on the "tool" field.
func ToolNotIn(vs ...string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldNotIn(FieldTool, vs...))
}

// ToolGT applies the GT predicate on the "tool" field.
func ToolGT(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldGT(FieldTool, v))
}

// ToolGTE applies the GTE predicate on the "tool" field.
func ToolGTE(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldGTE(FieldTool, v))
}

// ToolLT applies the LT predicate on the "tool" field.
func ToolLT(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldLT(FieldTool, v))
}

// ToolLTE applies the LTE predicate on the "tool" field.
func ToolLTE(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldLTE(FieldTool, v))
}

// ToolContains applies the Contains predicate on the "tool" field.
func ToolContains(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldContains(FieldTool, v))
}

// ToolHasPrefix applies the HasPrefix predicate on the "tool" field.
func ToolHasPrefix(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldHasPrefix(FieldTool, v))
}

// ToolHasSuffix applies the HasSuffix predicate on the "tool" field.
func ToolHasSuffix(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldHasSuffix(FieldTool, v))
}

// ToolEqualFold applies the EqualFold predicate on the "tool" field.
func ToolEqualFold(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEqualFold(FieldTool, v))
}

// ToolContainsFold applies the ContainsFold predicate on the "tool" field.
func ToolContainsFold(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldContainsFold(FieldTool, v))
}

// PatternEQ applies the EQ predicate on the "pattern" field.
func PatternEQ(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEQ(FieldPattern, v))
}

// PatternNEQ applies the NEQ predicate on the "pattern" field.
func PatternNEQ(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldNEQ(FieldPattern, v))
}

// PatternIn applies the In predicate on the "pattern" field.
func PatternIn(vs ...string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldIn(FieldPattern, vs...))
}

// PatternNotIn applies the NotIn predicate on the "pattern" field.
func PatternNotIn(vs ...string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldNotIn(FieldPattern, vs...))
}

// PatternGT applies the GT predicate on the "pattern" field.
func PatternGT(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldGT(FieldPattern, v))
}

// PatternGTE applies the GTE predicate on the "pattern" field.
func PatternGTE(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldGTE(FieldPattern, v))
}

// PatternLT applies the LT predicate on the "pattern" field.
func PatternLT(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldLT(FieldPattern, v))
}

// PatternLTE applies the LTE predicate on the "pattern" field.
func PatternLTE(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldLTE(FieldPattern, v))
}

// PatternContains applies the Contains predicate on the "pattern" field.
func PatternContains(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldContains(FieldPattern, v))
}

// PatternHasPrefix applies the HasPrefix predicate on the "pattern" field.
func PatternHasPrefix(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldHasPrefix(FieldPattern, v))
}

// PatternHasSuffix applies the HasSuffix predicate on the "pattern" field.
func PatternHasSuffix(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldHasSuffix(FieldPattern, v))
}

// PatternIsNil applies the IsNil predicate on the "pattern" field.
func PatternIsNil() predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldIsNull(FieldPattern))
}

// PatternNotNil applies the NotNil predicate on the "pattern" field.
func PatternNotNil() predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldNotNull(FieldPattern))
}

// PatternEqualFold applies the EqualFold predicate on the "pattern" field.
func PatternEqualFold(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEqualFold(FieldPattern, v))
}

// PatternContainsFold applies the ContainsFold predicate on the "pattern" field.
func PatternContainsFold(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldContainsFold(FieldPattern, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldContainsFold(FieldReason, v))
}

// OutcomeEQ applies the EQ predicate on the "outcome" field.
func OutcomeEQ(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEQ(FieldOutcome, v))
}

// OutcomeNEQ applies the NEQ predicate on the "outcome" field.
func OutcomeNEQ(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldNEQ(FieldOutcome, v))
}

// OutcomeIn applies the In predicate on the "outcome" field.
func OutcomeIn(vs ...string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldIn(FieldOutcome, vs...))
}

// OutcomeNotIn applies the NotIn predicate on the "outcome" field.
func OutcomeNotIn(vs ...string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldNotIn(FieldOutcome, vs...))
}

// OutcomeGT applies the GT predicate on the "outcome" field.
func OutcomeGT(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldGT(FieldOutcome, v))
}

// OutcomeGTE applies the GTE predicate on the "outcome" field.
func OutcomeGTE(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldGTE(FieldOutcome, v))
}

// OutcomeLT applies the LT predicate on the "outcome" field.
func OutcomeLT(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldLT(FieldOutcome, v))
}

// OutcomeLTE applies the LTE predicate on the "outcome" field.
func OutcomeLTE(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldLTE(FieldOutcome, v))
}

// OutcomeContains applies the Contains predicate on the "outcome" field.
func OutcomeContains(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldContains(FieldOutcome, v))
}

// OutcomeHasPrefix applies the HasPrefix predicate on the "outcome" field.
func OutcomeHasPrefix(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldHasPrefix(FieldOutcome, v))
}

// OutcomeHasSuffix applies the HasSuffix predicate on the "outcome" field.
func OutcomeHasSuffix(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldHasSuffix(FieldOutcome, v))
}

// OutcomeIsNil applies the IsNil predicate on the "outcome" field.
func OutcomeIsNil() predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldIsNull(FieldOutcome))
}

// OutcomeNotNil applies the NotNil predicate on the "outcome" field.
func OutcomeNotNil() predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldNotNull(FieldOutcome))
}

// OutcomeEqualFold applies the EqualFold predicate on the "outcome" field.
func OutcomeEqualFold(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEqualFold(FieldOutcome, v))
}

// OutcomeContainsFold applies the ContainsFold predicate on the "outcome" field.
func OutcomeContainsFold(v string) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldContainsFold(FieldOutcome, v))
}

// RequestedAtEQ applies the EQ predicate on the "requested_at" field.
func RequestedAtEQ(v time.Time) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEQ(FieldRequestedAt, v))
}

// RequestedAtNEQ applies the NEQ predicate on the "requested_at" field.
func RequestedAtNEQ(v time.Time) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldNEQ(FieldRequestedAt, v))
}

// RequestedAtIn applies the In predicate on the "requested_at" field.
func RequestedAtIn(vs ...time.Time) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldIn(FieldRequestedAt, vs...))
}

// RequestedAtNotIn applies the NotIn predicate on the "requested_at" field.
func RequestedAtNotIn(vs ...time.Time) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldNotIn(FieldRequestedAt, vs...))
}

// RequestedAtGT applies the GT predicate on the "requested_at" field.
func RequestedAtGT(v time.Time) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldGT(FieldRequestedAt, v))
}

// RequestedAtGTE applies the GTE predicate on the "requested_at" field.
func RequestedAtGTE(v time.Time) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldGTE(FieldRequestedAt, v))
}

// RequestedAtLT applies the LT predicate on the "requested_at" field.
func RequestedAtLT(v time.Time) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldLT(FieldRequestedAt, v))
}

// RequestedAtLTE applies the LTE predicate on the "requested_at" field.
func RequestedAtLTE(v time.Time) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldLTE(FieldRequestedAt, v))
}

// ResolvedAtEQ applies the EQ predicate on the "resolved_at" field.
func ResolvedAtEQ(v time.Time) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldEQ(FieldResolvedAt, v))
}

// ResolvedAtNEQ applies the NEQ predicate on the "resolved_at" field.
func ResolvedAtNEQ(v time.Time) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldNEQ(FieldResolvedAt, v))
}

// ResolvedAtIn applies the In predicate on the "resolved_at" field.
func ResolvedAtIn(vs ...time.Time) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldIn(FieldResolvedAt, vs...))
}

// ResolvedAtNotIn applies the NotIn predicate on the "resolved_at" field.
func ResolvedAtNotIn(vs ...time.Time) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldNotIn(FieldResolvedAt, vs...))
}

// ResolvedAtGT applies the GT predicate on the "resolved_at" field.
func ResolvedAtGT(v time.Time) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldGT(FieldResolvedAt, v))
}

// ResolvedAtGTE applies the GTE predicate on the "resolved_at" field.
func ResolvedAtGTE(v time.Time) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldGTE(FieldResolvedAt, v))
}

// ResolvedAtLT applies the LT predicate on the "resolved_at" field.
func ResolvedAtLT(v time.Time) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldLT(FieldResolvedAt, v))
}

// ResolvedAtLTE applies the LTE predicate on the "resolved_at" field.
func ResolvedAtLTE(v time.Time) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldLTE(FieldResolvedAt, v))
}

// ResolvedAtIsNil applies the IsNil predicate on the "resolved_at" field.
func ResolvedAtIsNil() predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldIsNull(FieldResolvedAt))
}

// ResolvedAtNotNil applies the NotNil predicate on the "resolved_at" field.
func ResolvedAtNotNil() predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.FieldNotNull(FieldResolvedAt))
}

// HasStageRun applies the HasEdge predicate on the "stage_run" edge.
func HasStageRun() predicate.PermissionRequest {
	return predicate.PermissionRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, StageRunTable, StageRunColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStageRunWith applies the HasEdge predicate on the "stage_run" edge with a given conditions (other predicates).
func HasStageRunWith(preds ...predicate.StageRun) predicate.PermissionRequest {
	return predicate.PermissionRequest(func(s *sql.Selector) {
		step := newStageRunStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PermissionRequest) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PermissionRequest) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PermissionRequest) predicate.PermissionRequest {
	return predicate.PermissionRequest(sql.NotPredicates(p))
}
