// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/kontor/server/internal/db/ent/auditevent"
)

// AuditEventCreate is the builder for creating a AuditEvent entity.
type AuditEventCreate struct {
	config
	mutation *AuditEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTs sets the "ts" field.
func (_c *AuditEventCreate) SetTs(v time.Time) *AuditEventCreate {
	_c.mutation.SetTs(v)
	return _c
}

// SetNillableTs sets the "ts" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableTs(v *time.Time) *AuditEventCreate {
	if v != nil {
		_c.SetTs(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *AuditEventCreate) SetUserID(v string) *AuditEventCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableUserID(v *string) *AuditEventCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *AuditEventCreate) SetAction(v string) *AuditEventCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetTarget sets the "target" field.
func (_c *AuditEventCreate) SetTarget(v string) *AuditEventCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *AuditEventCreate) SetMetadata(v map[string]interface{}) *AuditEventCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetTaskID sets the "task_id" field.
func (_c *AuditEventCreate) SetTaskID(v string) *AuditEventCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableTaskID(v *string) *AuditEventCreate {
	if v != nil {
		_c.SetTaskID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AuditEventCreate) SetID(v string) *AuditEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AuditEventMutation object of the builder.
func (_c *AuditEventCreate) Mutation() *AuditEventMutation {
	return _c.mutation
}

// Save creates the AuditEvent in the database.
func (_c *AuditEventCreate) Save(ctx context.Context) (*AuditEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuditEventCreate) SaveX(ctx context.Context) *AuditEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuditEventCreate) defaults() {
	if _, ok := _c.mutation.Ts(); !ok {
		v := auditevent.DefaultTs()
		_c.mutation.SetTs(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuditEventCreate) check() error {
	if _, ok := _c.mutation.Ts(); !ok {
		return &ValidationError{Name: "ts", err: errors.New(`ent: missing required field "AuditEvent.ts"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "AuditEvent.action"`)}
	}
	if _, ok := _c.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "AuditEvent.target"`)}
	}
	return nil
}

func (_c *AuditEventCreate) sqlSave(ctx context.Context) (*AuditEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected AuditEvent.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuditEventCreate) createSpec() (*AuditEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(auditevent.Table, sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Ts(); ok {
		_spec.SetField(auditevent.FieldTs, field.TypeTime, value)
		_node.Ts = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(auditevent.FieldUserID, field.TypeString, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(auditevent.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(auditevent.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(auditevent.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.TaskID(); ok {
		_spec.SetField(auditevent.FieldTaskID, field.TypeString, value)
		_node.TaskID = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuditEvent.Create().
//		SetTs(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuditEventUpsert) {
//			SetTs(v+v).
//		}).
//		Exec(ctx)
func (_c *AuditEventCreate) OnConflict(opts ...sql.ConflictOption) *AuditEventUpsertOne {
	_c.conflict = opts
	return &AuditEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuditEventCreate) OnConflictColumns(columns ...string) *AuditEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuditEventUpsertOne{
		create: _c,
	}
}

type (
	// AuditEventUpsertOne is the builder for "upsert"-ing
	//  one AuditEvent node.
	AuditEventUpsertOne struct {
		create *AuditEventCreate
	}

	// AuditEventUpsert is the "OnConflict" setter.
	AuditEventUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(auditevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuditEventUpsertOne) UpdateNewValues() *AuditEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(auditevent.FieldID)
		}
		if _, exists := u.create.mutation.Ts(); exists {
			s.SetIgnore(auditevent.FieldTs)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(auditevent.FieldUserID)
		}
		if _, exists := u.create.mutation.Action(); exists {
			s.SetIgnore(auditevent.FieldAction)
		}
		if _, exists := u.create.mutation.Target(); exists {
			s.SetIgnore(auditevent.FieldTarget)
		}
		if _, exists := u.create.mutation.Metadata(); exists {
			s.SetIgnore(auditevent.FieldMetadata)
		}
		if _, exists := u.create.mutation.TaskID(); exists {
			s.SetIgnore(auditevent.FieldTaskID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AuditEventUpsertOne) Ignore() *AuditEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuditEventUpsertOne) DoNothing() *AuditEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuditEventCreate.OnConflict
// documentation for more info.
func (u *AuditEventUpsertOne) Update(set func(*AuditEventUpsert)) *AuditEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuditEventUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *AuditEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuditEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuditEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AuditEventUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AuditEventUpsertOne.ID is not supported by MySQL driver. Use AuditEventUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AuditEventUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AuditEventCreateBulk is the builder for creating many AuditEvent entities in bulk.
type AuditEventCreateBulk struct {
	config
	err      error
	builders []*AuditEventCreate
	conflict []sql.ConflictOption
}

// Save creates the AuditEvent entities in the database.
func (_c *AuditEventCreateBulk) Save(ctx context.Context) ([]*AuditEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuditEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuditEventCreateBulk) SaveX(ctx context.Context) []*AuditEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AuditEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AuditEventUpsert) {
//			SetTs(v+v).
//		}).
//		Exec(ctx)
func (_c *AuditEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *AuditEventUpsertBulk {
	_c.conflict = opts
	return &AuditEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AuditEventCreateBulk) OnConflictColumns(columns ...string) *AuditEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AuditEventUpsertBulk{
		create: _c,
	}
}

// AuditEventUpsertBulk is the builder for "upsert"-ing
// a bulk of AuditEvent nodes.
type AuditEventUpsertBulk struct {
	create *AuditEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(auditevent.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AuditEventUpsertBulk) UpdateNewValues() *AuditEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(auditevent.FieldID)
			}
			if _, exists := b.mutation.Ts(); exists {
				s.SetIgnore(auditevent.FieldTs)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(auditevent.FieldUserID)
			}
			if _, exists := b.mutation.Action(); exists {
				s.SetIgnore(auditevent.FieldAction)
			}
			if _, exists := b.mutation.Target(); exists {
				s.SetIgnore(auditevent.FieldTarget)
			}
			if _, exists := b.mutation.Metadata(); exists {
				s.SetIgnore(auditevent.FieldMetadata)
			}
			if _, exists := b.mutation.TaskID(); exists {
				s.SetIgnore(auditevent.FieldTaskID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AuditEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AuditEventUpsertBulk) Ignore() *AuditEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AuditEventUpsertBulk) DoNothing() *AuditEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AuditEventCreateBulk.OnConflict
// documentation for more info.
func (u *AuditEventUpsertBulk) Update(set func(*AuditEventUpsert)) *AuditEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AuditEventUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *AuditEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AuditEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AuditEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AuditEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
