// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/kontor/server/internal/db/ent/coordlock"
)

// CoordLockCreate is the builder for creating a CoordLock entity.
type CoordLockCreate struct {
	config
	mutation *CoordLockMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetNamespace sets the "namespace" field.
func (_c *CoordLockCreate) SetNamespace(v string) *CoordLockCreate {
	_c.mutation.SetNamespace(v)
	return _c
}

// SetKey sets the "key" field.
func (_c *CoordLockCreate) SetKey(v string) *CoordLockCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetOwnerTaskID sets the "owner_task_id" field.
func (_c *CoordLockCreate) SetOwnerTaskID(v string) *CoordLockCreate {
	_c.mutation.SetOwnerTaskID(v)
	return _c
}

// SetAcquiredAt sets the "acquired_at" field.
func (_c *CoordLockCreate) SetAcquiredAt(v time.Time) *CoordLockCreate {
	_c.mutation.SetAcquiredAt(v)
	return _c
}

// SetNillableAcquiredAt sets the "acquired_at" field if the given value is not nil.
func (_c *CoordLockCreate) SetNillableAcquiredAt(v *time.Time) *CoordLockCreate {
	if v != nil {
		_c.SetAcquiredAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *CoordLockCreate) SetExpiresAt(v time.Time) *CoordLockCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *CoordLockCreate) SetID(v string) *CoordLockCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the CoordLockMutation object of the builder.
func (_c *CoordLockCreate) Mutation() *CoordLockMutation {
	return _c.mutation
}

// Save creates the CoordLock in the database.
func (_c *CoordLockCreate) Save(ctx context.Context) (*CoordLock, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CoordLockCreate) SaveX(ctx context.Context) *CoordLock {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CoordLockCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CoordLockCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CoordLockCreate) defaults() {
	if _, ok := _c.mutation.AcquiredAt(); !ok {
		v := coordlock.DefaultAcquiredAt()
		_c.mutation.SetAcquiredAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CoordLockCreate) check() error {
	if _, ok := _c.mutation.Namespace(); !ok {
		return &ValidationError{Name: "namespace", err: errors.New(`ent: missing required field "CoordLock.namespace"`)}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "CoordLock.key"`)}
	}
	if _, ok := _c.mutation.OwnerTaskID(); !ok {
		return &ValidationError{Name: "owner_task_id", err: errors.New(`ent: missing required field "CoordLock.owner_task_id"`)}
	}
	if _, ok := _c.mutation.AcquiredAt(); !ok {
		return &ValidationError{Name: "acquired_at", err: errors.New(`ent: missing required field "CoordLock.acquired_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "CoordLock.expires_at"`)}
	}
	return nil
}

func (_c *CoordLockCreate) sqlSave(ctx context.Context) (*CoordLock, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected CoordLock.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CoordLockCreate) createSpec() (*CoordLock, *sqlgraph.CreateSpec) {
	var (
		_node = &CoordLock{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(coordlock.Table, sqlgraph.NewFieldSpec(coordlock.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Namespace(); ok {
		_spec.SetField(coordlock.FieldNamespace, field.TypeString, value)
		_node.Namespace = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(coordlock.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.OwnerTaskID(); ok {
		_spec.SetField(coordlock.FieldOwnerTaskID, field.TypeString, value)
		_node.OwnerTaskID = value
	}
	if value, ok := _c.mutation.AcquiredAt(); ok {
		_spec.SetField(coordlock.FieldAcquiredAt, field.TypeTime, value)
		_node.AcquiredAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(coordlock.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CoordLock.Create().
//		SetNamespace(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CoordLockUpsert) {
//			SetNamespace(v+v).
//		}).
//		Exec(ctx)
func (_c *CoordLockCreate) OnConflict(opts ...sql.ConflictOption) *CoordLockUpsertOne {
	_c.conflict = opts
	return &CoordLockUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CoordLock.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CoordLockCreate) OnConflictColumns(columns ...string) *CoordLockUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CoordLockUpsertOne{
		create: _c,
	}
}

type (
	// CoordLockUpsertOne is the builder for "upsert"-ing
	//  one CoordLock node.
	CoordLockUpsertOne struct {
		create *CoordLockCreate
	}

	// CoordLockUpsert is the "OnConflict" setter.
	CoordLockUpsert struct {
		*sql.UpdateSet
	}
)

// SetNamespace sets the "namespace" field.
func (u *CoordLockUpsert) SetNamespace(v string) *CoordLockUpsert {
	u.Set(coordlock.FieldNamespace, v)
	return u
}

// UpdateNamespace sets the "namespace" field to the value that was provided on create.
func (u *CoordLockUpsert) UpdateNamespace() *CoordLockUpsert {
	u.SetExcluded(coordlock.FieldNamespace)
	return u
}

// SetKey sets the "key" field.
func (u *CoordLockUpsert) SetKey(v string) *CoordLockUpsert {
	u.Set(coordlock.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *CoordLockUpsert) UpdateKey() *CoordLockUpsert {
	u.SetExcluded(coordlock.FieldKey)
	return u
}

// SetOwnerTaskID sets the "owner_task_id" field.
func (u *CoordLockUpsert) SetOwnerTaskID(v string) *CoordLockUpsert {
	u.Set(coordlock.FieldOwnerTaskID, v)
	return u
}

// UpdateOwnerTaskID sets the "owner_task_id" field to the value that was provided on create.
func (u *CoordLockUpsert) UpdateOwnerTaskID() *CoordLockUpsert {
	u.SetExcluded(coordlock.FieldOwnerTaskID)
	return u
}

// SetAcquiredAt sets the "acquired_at" field.
func (u *CoordLockUpsert) SetAcquiredAt(v time.Time) *CoordLockUpsert {
	u.Set(coordlock.FieldAcquiredAt, v)
	return u
}

// UpdateAcquiredAt sets the "acquired_at" field to the value that was provided on create.
func (u *CoordLockUpsert) UpdateAcquiredAt() *CoordLockUpsert {
	u.SetExcluded(coordlock.FieldAcquiredAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *CoordLockUpsert) SetExpiresAt(v time.Time) *CoordLockUpsert {
	u.Set(coordlock.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CoordLockUpsert) UpdateExpiresAt() *CoordLockUpsert {
	u.SetExcluded(coordlock.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CoordLock.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(coordlock.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CoordLockUpsertOne) UpdateNewValues() *CoordLockUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(coordlock.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CoordLock.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CoordLockUpsertOne) Ignore() *CoordLockUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CoordLockUpsertOne) DoNothing() *CoordLockUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CoordLockCreate.OnConflict
// documentation for more info.
func (u *CoordLockUpsertOne) Update(set func(*CoordLockUpsert)) *CoordLockUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CoordLockUpsert{UpdateSet: update})
	}))
	return u
}

// SetNamespace sets the "namespace" field.
func (u *CoordLockUpsertOne) SetNamespace(v string) *CoordLockUpsertOne {
	return u.Update(func(s *CoordLockUpsert) {
		s.SetNamespace(v)
	})
}

// UpdateNamespace sets the "namespace" field to the value that was provided on create.
func (u *CoordLockUpsertOne) UpdateNamespace() *CoordLockUpsertOne {
	return u.Update(func(s *CoordLockUpsert) {
		s.UpdateNamespace()
	})
}

// SetKey sets the "key" field.
func (u *CoordLockUpsertOne) SetKey(v string) *CoordLockUpsertOne {
	return u.Update(func(s *CoordLockUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *CoordLockUpsertOne) UpdateKey() *CoordLockUpsertOne {
	return u.Update(func(s *CoordLockUpsert) {
		s.UpdateKey()
	})
}

// SetOwnerTaskID sets the "owner_task_id" field.
func (u *CoordLockUpsertOne) SetOwnerTaskID(v string) *CoordLockUpsertOne {
	return u.Update(func(s *CoordLockUpsert) {
		s.SetOwnerTaskID(v)
	})
}

// UpdateOwnerTaskID sets the "owner_task_id" field to the value that was provided on create.
func (u *CoordLockUpsertOne) UpdateOwnerTaskID() *CoordLockUpsertOne {
	return u.Update(func(s *CoordLockUpsert) {
		s.UpdateOwnerTaskID()
	})
}

// SetAcquiredAt sets the "acquired_at" field.
func (u *CoordLockUpsertOne) SetAcquiredAt(v time.Time) *CoordLockUpsertOne {
	return u.Update(func(s *CoordLockUpsert) {
		s.SetAcquiredAt(v)
	})
}

// UpdateAcquiredAt sets the "acquired_at" field to the value that was provided on create.
func (u *CoordLockUpsertOne) UpdateAcquiredAt() *CoordLockUpsertOne {
	return u.Update(func(s *CoordLockUpsert) {
		s.UpdateAcquiredAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *CoordLockUpsertOne) SetExpiresAt(v time.Time) *CoordLockUpsertOne {
	return u.Update(func(s *CoordLockUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CoordLockUpsertOne) UpdateExpiresAt() *CoordLockUpsertOne {
	return u.Update(func(s *CoordLockUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *CoordLockUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CoordLockCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CoordLockUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CoordLockUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CoordLockUpsertOne.ID is not supported by MySQL driver. Use CoordLockUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CoordLockUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CoordLockCreateBulk is the builder for creating many CoordLock entities in bulk.
type CoordLockCreateBulk struct {
	config
	err      error
	builders []*CoordLockCreate
	conflict []sql.ConflictOption
}

// Save creates the CoordLock entities in the database.
func (_c *CoordLockCreateBulk) Save(ctx context.Context) ([]*CoordLock, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CoordLock, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CoordLockMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CoordLockCreateBulk) SaveX(ctx context.Context) []*CoordLock {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CoordLockCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CoordLockCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CoordLock.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CoordLockUpsert) {
//			SetNamespace(v+v).
//		}).
//		Exec(ctx)
func (_c *CoordLockCreateBulk) OnConflict(opts ...sql.ConflictOption) *CoordLockUpsertBulk {
	_c.conflict = opts
	return &CoordLockUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CoordLock.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CoordLockCreateBulk) OnConflictColumns(columns ...string) *CoordLockUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CoordLockUpsertBulk{
		create: _c,
	}
}

// CoordLockUpsertBulk is the builder for "upsert"-ing
// a bulk of CoordLock nodes.
type CoordLockUpsertBulk struct {
	create *CoordLockCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CoordLock.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(coordlock.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CoordLockUpsertBulk) UpdateNewValues() *CoordLockUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(coordlock.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CoordLock.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CoordLockUpsertBulk) Ignore() *CoordLockUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CoordLockUpsertBulk) DoNothing() *CoordLockUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CoordLockCreateBulk.OnConflict
// documentation for more info.
func (u *CoordLockUpsertBulk) Update(set func(*CoordLockUpsert)) *CoordLockUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CoordLockUpsert{UpdateSet: update})
	}))
	return u
}

// SetNamespace sets the "namespace" field.
func (u *CoordLockUpsertBulk) SetNamespace(v string) *CoordLockUpsertBulk {
	return u.Update(func(s *CoordLockUpsert) {
		s.SetNamespace(v)
	})
}

// UpdateNamespace sets the "namespace" field to the value that was provided on create.
func (u *CoordLockUpsertBulk) UpdateNamespace() *CoordLockUpsertBulk {
	return u.Update(func(s *CoordLockUpsert) {
		s.UpdateNamespace()
	})
}

// SetKey sets the "key" field.
func (u *CoordLockUpsertBulk) SetKey(v string) *CoordLockUpsertBulk {
	return u.Update(func(s *CoordLockUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *CoordLockUpsertBulk) UpdateKey() *CoordLockUpsertBulk {
	return u.Update(func(s *CoordLockUpsert) {
		s.UpdateKey()
	})
}

// SetOwnerTaskID sets the "owner_task_id" field.
func (u *CoordLockUpsertBulk) SetOwnerTaskID(v string) *CoordLockUpsertBulk {
	return u.Update(func(s *CoordLockUpsert) {
		s.SetOwnerTaskID(v)
	})
}

// UpdateOwnerTaskID sets the "owner_task_id" field to the value that was provided on create.
func (u *CoordLockUpsertBulk) UpdateOwnerTaskID() *CoordLockUpsertBulk {
	return u.Update(func(s *CoordLockUpsert) {
		s.UpdateOwnerTaskID()
	})
}

// SetAcquiredAt sets the "acquired_at" field.
func (u *CoordLockUpsertBulk) SetAcquiredAt(v time.Time) *CoordLockUpsertBulk {
	return u.Update(func(s *CoordLockUpsert) {
		s.SetAcquiredAt(v)
	})
}

// UpdateAcquiredAt sets the "acquired_at" field to the value that was provided on create.
func (u *CoordLockUpsertBulk) UpdateAcquiredAt() *CoordLockUpsertBulk {
	return u.Update(func(s *CoordLockUpsert) {
		s.UpdateAcquiredAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *CoordLockUpsertBulk) SetExpiresAt(v time.Time) *CoordLockUpsertBulk {
	return u.Update(func(s *CoordLockUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *CoordLockUpsertBulk) UpdateExpiresAt() *CoordLockUpsertBulk {
	return u.Update(func(s *CoordLockUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *CoordLockUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CoordLockCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CoordLockCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CoordLockUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
