// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/kontor/server/internal/db/ent/grant"
)

// GrantCreate is the builder for creating a Grant entity.
type GrantCreate struct {
	config
	mutation *GrantMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *GrantCreate) SetCreatedAt(v time.Time) *GrantCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GrantCreate) SetNillableCreatedAt(v *time.Time) *GrantCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GrantCreate) SetUpdatedAt(v time.Time) *GrantCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GrantCreate) SetNillableUpdatedAt(v *time.Time) *GrantCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCapabilityName sets the "capability_name" field.
func (_c *GrantCreate) SetCapabilityName(v string) *GrantCreate {
	_c.mutation.SetCapabilityName(v)
	return _c
}

// SetContextKind sets the "context_kind" field.
func (_c *GrantCreate) SetContextKind(v string) *GrantCreate {
	_c.mutation.SetContextKind(v)
	return _c
}

// SetContextRef sets the "context_ref" field.
func (_c *GrantCreate) SetContextRef(v string) *GrantCreate {
	_c.mutation.SetContextRef(v)
	return _c
}

// SetNillableContextRef sets the "context_ref" field if the given value is not nil.
func (_c *GrantCreate) SetNillableContextRef(v *string) *GrantCreate {
	if v != nil {
		_c.SetContextRef(*v)
	}
	return _c
}

// SetPattern sets the "pattern" field.
func (_c *GrantCreate) SetPattern(v string) *GrantCreate {
	_c.mutation.SetPattern(v)
	return _c
}

// SetNillablePattern sets the "pattern" field if the given value is not nil.
func (_c *GrantCreate) SetNillablePattern(v *string) *GrantCreate {
	if v != nil {
		_c.SetPattern(*v)
	}
	return _c
}

// SetMode sets the "mode" field.
func (_c *GrantCreate) SetMode(v string) *GrantCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetLimitCount sets the "limit_count" field.
func (_c *GrantCreate) SetLimitCount(v int) *GrantCreate {
	_c.mutation.SetLimitCount(v)
	return _c
}

// SetNillableLimitCount sets the "limit_count" field if the given value is not nil.
func (_c *GrantCreate) SetNillableLimitCount(v *int) *GrantCreate {
	if v != nil {
		_c.SetLimitCount(*v)
	}
	return _c
}

// SetLimitWindowSeconds sets the "limit_window_seconds" field.
func (_c *GrantCreate) SetLimitWindowSeconds(v int) *GrantCreate {
	_c.mutation.SetLimitWindowSeconds(v)
	return _c
}

// SetNillableLimitWindowSeconds sets the "limit_window_seconds" field if the given value is not nil.
func (_c *GrantCreate) SetNillableLimitWindowSeconds(v *int) *GrantCreate {
	if v != nil {
		_c.SetLimitWindowSeconds(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *GrantCreate) SetExpiresAt(v time.Time) *GrantCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *GrantCreate) SetNillableExpiresAt(v *time.Time) *GrantCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetGrantedBy sets the "granted_by" field.
func (_c *GrantCreate) SetGrantedBy(v string) *GrantCreate {
	_c.mutation.SetGrantedBy(v)
	return _c
}

// SetGrantedAt sets the "granted_at" field.
func (_c *GrantCreate) SetGrantedAt(v time.Time) *GrantCreate {
	_c.mutation.SetGrantedAt(v)
	return _c
}

// SetNillableGrantedAt sets the "granted_at" field if the given value is not nil.
func (_c *GrantCreate) SetNillableGrantedAt(v *time.Time) *GrantCreate {
	if v != nil {
		_c.SetGrantedAt(*v)
	}
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *GrantCreate) SetRevokedAt(v time.Time) *GrantCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *GrantCreate) SetNillableRevokedAt(v *time.Time) *GrantCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetRevokedBy sets the "revoked_by" field.
func (_c *GrantCreate) SetRevokedBy(v string) *GrantCreate {
	_c.mutation.SetRevokedBy(v)
	return _c
}

// SetNillableRevokedBy sets the "revoked_by" field if the given value is not nil.
func (_c *GrantCreate) SetNillableRevokedBy(v *string) *GrantCreate {
	if v != nil {
		_c.SetRevokedBy(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *GrantCreate) SetReason(v string) *GrantCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *GrantCreate) SetNillableReason(v *string) *GrantCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetNodeID sets the "node_id" field.
func (_c *GrantCreate) SetNodeID(v string) *GrantCreate {
	_c.mutation.SetNodeID(v)
	return _c
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_c *GrantCreate) SetNillableNodeID(v *string) *GrantCreate {
	if v != nil {
		_c.SetNodeID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GrantCreate) SetID(v string) *GrantCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the GrantMutation object of the builder.
func (_c *GrantCreate) Mutation() *GrantMutation {
	return _c.mutation
}

// Save creates the Grant in the database.
func (_c *GrantCreate) Save(ctx context.Context) (*Grant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GrantCreate) SaveX(ctx context.Context) *Grant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GrantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GrantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GrantCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := grant.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := grant.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ContextRef(); !ok {
		v := grant.DefaultContextRef
		_c.mutation.SetContextRef(v)
	}
	if _, ok := _c.mutation.Pattern(); !ok {
		v := grant.DefaultPattern
		_c.mutation.SetPattern(v)
	}
	if _, ok := _c.mutation.LimitCount(); !ok {
		v := grant.DefaultLimitCount
		_c.mutation.SetLimitCount(v)
	}
	if _, ok := _c.mutation.LimitWindowSeconds(); !ok {
		v := grant.DefaultLimitWindowSeconds
		_c.mutation.SetLimitWindowSeconds(v)
	}
	if _, ok := _c.mutation.GrantedAt(); !ok {
		v := grant.DefaultGrantedAt()
		_c.mutation.SetGrantedAt(v)
	}
	if _, ok := _c.mutation.RevokedBy(); !ok {
		v := grant.DefaultRevokedBy
		_c.mutation.SetRevokedBy(v)
	}
	if _, ok := _c.mutation.Reason(); !ok {
		v := grant.DefaultReason
		_c.mutation.SetReason(v)
	}
	if _, ok := _c.mutation.NodeID(); !ok {
		v := grant.DefaultNodeID
		_c.mutation.SetNodeID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GrantCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Grant.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Grant.updated_at"`)}
	}
	if _, ok := _c.mutation.CapabilityName(); !ok {
		return &ValidationError{Name: "capability_name", err: errors.New(`ent: missing required field "Grant.capability_name"`)}
	}
	if _, ok := _c.mutation.ContextKind(); !ok {
		return &ValidationError{Name: "context_kind", err: errors.New(`ent: missing required field "Grant.context_kind"`)}
	}
	if _, ok := _c.mutation.ContextRef(); !ok {
		return &ValidationError{Name: "context_ref", err: errors.New(`ent: missing required field "Grant.context_ref"`)}
	}
	if _, ok := _c.mutation.Pattern(); !ok {
		return &ValidationError{Name: "pattern", err: errors.New(`ent: missing required field "Grant.pattern"`)}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "Grant.mode"`)}
	}
	if _, ok := _c.mutation.LimitCount(); !ok {
		return &ValidationError{Name: "limit_count", err: errors.New(`ent: missing required field "Grant.limit_count"`)}
	}
	if v, ok := _c.mutation.LimitCount(); ok {
		if err := grant.LimitCountValidator(v); err != nil {
			return &ValidationError{Name: "limit_count", err: fmt.Errorf(`ent: validator failed for field "Grant.limit_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LimitWindowSeconds(); !ok {
		return &ValidationError{Name: "limit_window_seconds", err: errors.New(`ent: missing required field "Grant.limit_window_seconds"`)}
	}
	if _, ok := _c.mutation.GrantedBy(); !ok {
		return &ValidationError{Name: "granted_by", err: errors.New(`ent: missing required field "Grant.granted_by"`)}
	}
	if _, ok := _c.mutation.GrantedAt(); !ok {
		return &ValidationError{Name: "granted_at", err: errors.New(`ent: missing required field "Grant.granted_at"`)}
	}
	if _, ok := _c.mutation.RevokedBy(); !ok {
		return &ValidationError{Name: "revoked_by", err: errors.New(`ent: missing required field "Grant.revoked_by"`)}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "Grant.reason"`)}
	}
	if _, ok := _c.mutation.NodeID(); !ok {
		return &ValidationError{Name: "node_id", err: errors.New(`ent: missing required field "Grant.node_id"`)}
	}
	return nil
}

func (_c *GrantCreate) sqlSave(ctx context.Context) (*Grant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Grant.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GrantCreate) createSpec() (*Grant, *sqlgraph.CreateSpec) {
	var (
		_node = &Grant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(grant.Table, sqlgraph.NewFieldSpec(grant.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(grant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(grant.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CapabilityName(); ok {
		_spec.SetField(grant.FieldCapabilityName, field.TypeString, value)
		_node.CapabilityName = value
	}
	if value, ok := _c.mutation.ContextKind(); ok {
		_spec.SetField(grant.FieldContextKind, field.TypeString, value)
		_node.ContextKind = value
	}
	if value, ok := _c.mutation.ContextRef(); ok {
		_spec.SetField(grant.FieldContextRef, field.TypeString, value)
		_node.ContextRef = value
	}
	if value, ok := _c.mutation.Pattern(); ok {
		_spec.SetField(grant.FieldPattern, field.TypeString, value)
		_node.Pattern = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(grant.FieldMode, field.TypeString, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.LimitCount(); ok {
		_spec.SetField(grant.FieldLimitCount, field.TypeInt, value)
		_node.LimitCount = value
	}
	if value, ok := _c.mutation.LimitWindowSeconds(); ok {
		_spec.SetField(grant.FieldLimitWindowSeconds, field.TypeInt, value)
		_node.LimitWindowSeconds = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(grant.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.GrantedBy(); ok {
		_spec.SetField(grant.FieldGrantedBy, field.TypeString, value)
		_node.GrantedBy = value
	}
	if value, ok := _c.mutation.GrantedAt(); ok {
		_spec.SetField(grant.FieldGrantedAt, field.TypeTime, value)
		_node.GrantedAt = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(grant.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := _c.mutation.RevokedBy(); ok {
		_spec.SetField(grant.FieldRevokedBy, field.TypeString, value)
		_node.RevokedBy = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(grant.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.NodeID(); ok {
		_spec.SetField(grant.FieldNodeID, field.TypeString, value)
		_node.NodeID = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Grant.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GrantUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GrantCreate) OnConflict(opts ...sql.ConflictOption) *GrantUpsertOne {
	_c.conflict = opts
	return &GrantUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Grant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GrantCreate) OnConflictColumns(columns ...string) *GrantUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GrantUpsertOne{
		create: _c,
	}
}

type (
	// GrantUpsertOne is the builder for "upsert"-ing
	//  one Grant node.
	GrantUpsertOne struct {
		create *GrantCreate
	}

	// GrantUpsert is the "OnConflict" setter.
	GrantUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *GrantUpsert) SetUpdatedAt(v time.Time) *GrantUpsert {
	u.Set(grant.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GrantUpsert) UpdateUpdatedAt() *GrantUpsert {
	u.SetExcluded(grant.FieldUpdatedAt)
	return u
}

// SetCapabilityName sets the "capability_name" field.
func (u *GrantUpsert) SetCapabilityName(v string) *GrantUpsert {
	u.Set(grant.FieldCapabilityName, v)
	return u
}

// UpdateCapabilityName sets the "capability_name" field to the value that was provided on create.
func (u *GrantUpsert) UpdateCapabilityName() *GrantUpsert {
	u.SetExcluded(grant.FieldCapabilityName)
	return u
}

// SetContextKind sets the "context_kind" field.
func (u *GrantUpsert) SetContextKind(v string) *GrantUpsert {
	u.Set(grant.FieldContextKind, v)
	return u
}

// UpdateContextKind sets the "context_kind" field to the value that was provided on create.
func (u *GrantUpsert) UpdateContextKind() *GrantUpsert {
	u.SetExcluded(grant.FieldContextKind)
	return u
}

// SetContextRef sets the "context_ref" field.
func (u *GrantUpsert) SetContextRef(v string) *GrantUpsert {
	u.Set(grant.FieldContextRef, v)
	return u
}

// UpdateContextRef sets the "context_ref" field to the value that was provided on create.
func (u *GrantUpsert) UpdateContextRef() *GrantUpsert {
	u.SetExcluded(grant.FieldContextRef)
	return u
}

// SetPattern sets the "pattern" field.
func (u *GrantUpsert) SetPattern(v string) *GrantUpsert {
	u.Set(grant.FieldPattern, v)
	return u
}

// UpdatePattern sets the "pattern" field to the value that was provided on create.
func (u *GrantUpsert) UpdatePattern() *GrantUpsert {
	u.SetExcluded(grant.FieldPattern)
	return u
}

// SetMode sets the "mode" field.
func (u *GrantUpsert) SetMode(v string) *GrantUpsert {
	u.Set(grant.FieldMode, v)
	return u
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *GrantUpsert) UpdateMode() *GrantUpsert {
	u.SetExcluded(grant.FieldMode)
	return u
}

// SetLimitCount sets the "limit_count" field.
func (u *GrantUpsert) SetLimitCount(v int) *GrantUpsert {
	u.Set(grant.FieldLimitCount, v)
	return u
}

// UpdateLimitCount sets the "limit_count" field to the value that was provided on create.
func (u *GrantUpsert) UpdateLimitCount() *GrantUpsert {
	u.SetExcluded(grant.FieldLimitCount)
	return u
}

// AddLimitCount adds v to the "limit_count" field.
func (u *GrantUpsert) AddLimitCount(v int) *GrantUpsert {
	u.Add(grant.FieldLimitCount, v)
	return u
}

// SetLimitWindowSeconds sets the "limit_window_seconds" field.
func (u *GrantUpsert) SetLimitWindowSeconds(v int) *GrantUpsert {
	u.Set(grant.FieldLimitWindowSeconds, v)
	return u
}

// UpdateLimitWindowSeconds sets the "limit_window_seconds" field to the value that was provided on create.
func (u *GrantUpsert) UpdateLimitWindowSeconds() *GrantUpsert {
	u.SetExcluded(grant.FieldLimitWindowSeconds)
	return u
}

// AddLimitWindowSeconds adds v to the "limit_window_seconds" field.
func (u *GrantUpsert) AddLimitWindowSeconds(v int) *GrantUpsert {
	u.Add(grant.FieldLimitWindowSeconds, v)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *GrantUpsert) SetExpiresAt(v time.Time) *GrantUpsert {
	u.Set(grant.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *GrantUpsert) UpdateExpiresAt() *GrantUpsert {
	u.SetExcluded(grant.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *GrantUpsert) ClearExpiresAt() *GrantUpsert {
	u.SetNull(grant.FieldExpiresAt)
	return u
}

// SetGrantedBy sets the "granted_by" field.
func (u *GrantUpsert) SetGrantedBy(v string) *GrantUpsert {
	u.Set(grant.FieldGrantedBy, v)
	return u
}

// UpdateGrantedBy sets the "granted_by" field to the value that was provided on create.
func (u *GrantUpsert) UpdateGrantedBy() *GrantUpsert {
	u.SetExcluded(grant.FieldGrantedBy)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *GrantUpsert) SetRevokedAt(v time.Time) *GrantUpsert {
	u.Set(grant.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *GrantUpsert) UpdateRevokedAt() *GrantUpsert {
	u.SetExcluded(grant.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *GrantUpsert) ClearRevokedAt() *GrantUpsert {
	u.SetNull(grant.FieldRevokedAt)
	return u
}

// SetRevokedBy sets the "revoked_by" field.
func (u *GrantUpsert) SetRevokedBy(v string) *GrantUpsert {
	u.Set(grant.FieldRevokedBy, v)
	return u
}

// UpdateRevokedBy sets the "revoked_by" field to the value that was provided on create.
func (u *GrantUpsert) UpdateRevokedBy() *GrantUpsert {
	u.SetExcluded(grant.FieldRevokedBy)
	return u
}

// SetReason sets the "reason" field.
func (u *GrantUpsert) SetReason(v string) *GrantUpsert {
	u.Set(grant.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *GrantUpsert) UpdateReason() *GrantUpsert {
	u.SetExcluded(grant.FieldReason)
	return u
}

// SetNodeID sets the "node_id" field.
func (u *GrantUpsert) SetNodeID(v string) *GrantUpsert {
	u.Set(grant.FieldNodeID, v)
	return u
}

// UpdateNodeID sets the "node_id" field to the value that was provided on create.
func (u *GrantUpsert) UpdateNodeID() *GrantUpsert {
	u.SetExcluded(grant.FieldNodeID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Grant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(grant.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GrantUpsertOne) UpdateNewValues() *GrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(grant.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(grant.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.GrantedAt(); exists {
			s.SetIgnore(grant.FieldGrantedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Grant.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GrantUpsertOne) Ignore() *GrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GrantUpsertOne) DoNothing() *GrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GrantCreate.OnConflict
// documentation for more info.
func (u *GrantUpsertOne) Update(set func(*GrantUpsert)) *GrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GrantUpsertOne) SetUpdatedAt(v time.Time) *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GrantUpsertOne) UpdateUpdatedAt() *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCapabilityName sets the "capability_name" field.
func (u *GrantUpsertOne) SetCapabilityName(v string) *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.SetCapabilityName(v)
	})
}

// UpdateCapabilityName sets the "capability_name" field to the value that was provided on create.
func (u *GrantUpsertOne) UpdateCapabilityName() *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateCapabilityName()
	})
}

// SetContextKind sets the "context_kind" field.
func (u *GrantUpsertOne) SetContextKind(v string) *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.SetContextKind(v)
	})
}

// UpdateContextKind sets the "context_kind" field to the value that was provided on create.
func (u *GrantUpsertOne) UpdateContextKind() *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateContextKind()
	})
}

// SetContextRef sets the "context_ref" field.
func (u *GrantUpsertOne) SetContextRef(v string) *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.SetContextRef(v)
	})
}

// UpdateContextRef sets the "context_ref" field to the value that was provided on create.
func (u *GrantUpsertOne) UpdateContextRef() *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateContextRef()
	})
}

// SetPattern sets the "pattern" field.
func (u *GrantUpsertOne) SetPattern(v string) *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.SetPattern(v)
	})
}

// UpdatePattern sets the "pattern" field to the value that was provided on create.
func (u *GrantUpsertOne) UpdatePattern() *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.UpdatePattern()
	})
}

// SetMode sets the "mode" field.
func (u *GrantUpsertOne) SetMode(v string) *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *GrantUpsertOne) UpdateMode() *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateMode()
	})
}

// SetLimitCount sets the "limit_count" field.
func (u *GrantUpsertOne) SetLimitCount(v int) *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.SetLimitCount(v)
	})
}

// AddLimitCount adds v to the "limit_count" field.
func (u *GrantUpsertOne) AddLimitCount(v int) *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.AddLimitCount(v)
	})
}

// UpdateLimitCount sets the "limit_count" field to the value that was provided on create.
func (u *GrantUpsertOne) UpdateLimitCount() *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateLimitCount()
	})
}

// SetLimitWindowSeconds sets the "limit_window_seconds" field.
func (u *GrantUpsertOne) SetLimitWindowSeconds(v int) *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.SetLimitWindowSeconds(v)
	})
}

// AddLimitWindowSeconds adds v to the "limit_window_seconds" field.
func (u *GrantUpsertOne) AddLimitWindowSeconds(v int) *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.AddLimitWindowSeconds(v)
	})
}

// UpdateLimitWindowSeconds sets the "limit_window_seconds" field to the value that was provided on create.
func (u *GrantUpsertOne) UpdateLimitWindowSeconds() *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateLimitWindowSeconds()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *GrantUpsertOne) SetExpiresAt(v time.Time) *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *GrantUpsertOne) UpdateExpiresAt() *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *GrantUpsertOne) ClearExpiresAt() *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.ClearExpiresAt()
	})
}

// SetGrantedBy sets the "granted_by" field.
func (u *GrantUpsertOne) SetGrantedBy(v string) *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.SetGrantedBy(v)
	})
}

// UpdateGrantedBy sets the "granted_by" field to the value that was provided on create.
func (u *GrantUpsertOne) UpdateGrantedBy() *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateGrantedBy()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *GrantUpsertOne) SetRevokedAt(v time.Time) *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *GrantUpsertOne) UpdateRevokedAt() *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *GrantUpsertOne) ClearRevokedAt() *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.ClearRevokedAt()
	})
}

// SetRevokedBy sets the "revoked_by" field.
func (u *GrantUpsertOne) SetRevokedBy(v string) *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.SetRevokedBy(v)
	})
}

// UpdateRevokedBy sets the "revoked_by" field to the value that was provided on create.
func (u *GrantUpsertOne) UpdateRevokedBy() *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateRevokedBy()
	})
}

// SetReason sets the "reason" field.
func (u *GrantUpsertOne) SetReason(v string) *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *GrantUpsertOne) UpdateReason() *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateReason()
	})
}

// SetNodeID sets the "node_id" field.
func (u *GrantUpsertOne) SetNodeID(v string) *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.SetNodeID(v)
	})
}

// UpdateNodeID sets the "node_id" field to the value that was provided on create.
func (u *GrantUpsertOne) UpdateNodeID() *GrantUpsertOne {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateNodeID()
	})
}

// Exec executes the query.
func (u *GrantUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GrantCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GrantUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GrantUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: GrantUpsertOne.ID is not supported by MySQL driver. Use GrantUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GrantUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GrantCreateBulk is the builder for creating many Grant entities in bulk.
type GrantCreateBulk struct {
	config
	err      error
	builders []*GrantCreate
	conflict []sql.ConflictOption
}

// Save creates the Grant entities in the database.
func (_c *GrantCreateBulk) Save(ctx context.Context) ([]*Grant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Grant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GrantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GrantCreateBulk) SaveX(ctx context.Context) []*Grant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GrantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GrantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Grant.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GrantUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *GrantCreateBulk) OnConflict(opts ...sql.ConflictOption) *GrantUpsertBulk {
	_c.conflict = opts
	return &GrantUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Grant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GrantCreateBulk) OnConflictColumns(columns ...string) *GrantUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GrantUpsertBulk{
		create: _c,
	}
}

// GrantUpsertBulk is the builder for "upsert"-ing
// a bulk of Grant nodes.
type GrantUpsertBulk struct {
	create *GrantCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Grant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(grant.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GrantUpsertBulk) UpdateNewValues() *GrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(grant.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(grant.FieldCreatedAt)
			}
			if _, exists := b.mutation.GrantedAt(); exists {
				s.SetIgnore(grant.FieldGrantedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Grant.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GrantUpsertBulk) Ignore() *GrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GrantUpsertBulk) DoNothing() *GrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GrantCreateBulk.OnConflict
// documentation for more info.
func (u *GrantUpsertBulk) Update(set func(*GrantUpsert)) *GrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GrantUpsertBulk) SetUpdatedAt(v time.Time) *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GrantUpsertBulk) UpdateUpdatedAt() *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCapabilityName sets the "capability_name" field.
func (u *GrantUpsertBulk) SetCapabilityName(v string) *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.SetCapabilityName(v)
	})
}

// UpdateCapabilityName sets the "capability_name" field to the value that was provided on create.
func (u *GrantUpsertBulk) UpdateCapabilityName() *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateCapabilityName()
	})
}

// SetContextKind sets the "context_kind" field.
func (u *GrantUpsertBulk) SetContextKind(v string) *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.SetContextKind(v)
	})
}

// UpdateContextKind sets the "context_kind" field to the value that was provided on create.
func (u *GrantUpsertBulk) UpdateContextKind() *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateContextKind()
	})
}

// SetContextRef sets the "context_ref" field.
func (u *GrantUpsertBulk) SetContextRef(v string) *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.SetContextRef(v)
	})
}

// UpdateContextRef sets the "context_ref" field to the value that was provided on create.
func (u *GrantUpsertBulk) UpdateContextRef() *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateContextRef()
	})
}

// SetPattern sets the "pattern" field.
func (u *GrantUpsertBulk) SetPattern(v string) *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.SetPattern(v)
	})
}

// UpdatePattern sets the "pattern" field to the value that was provided on create.
func (u *GrantUpsertBulk) UpdatePattern() *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.UpdatePattern()
	})
}

// SetMode sets the "mode" field.
func (u *GrantUpsertBulk) SetMode(v string) *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *GrantUpsertBulk) UpdateMode() *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateMode()
	})
}

// SetLimitCount sets the "limit_count" field.
func (u *GrantUpsertBulk) SetLimitCount(v int) *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.SetLimitCount(v)
	})
}

// AddLimitCount adds v to the "limit_count" field.
func (u *GrantUpsertBulk) AddLimitCount(v int) *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.AddLimitCount(v)
	})
}

// UpdateLimitCount sets the "limit_count" field to the value that was provided on create.
func (u *GrantUpsertBulk) UpdateLimitCount() *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateLimitCount()
	})
}

// SetLimitWindowSeconds sets the "limit_window_seconds" field.
func (u *GrantUpsertBulk) SetLimitWindowSeconds(v int) *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.SetLimitWindowSeconds(v)
	})
}

// AddLimitWindowSeconds adds v to the "limit_window_seconds" field.
func (u *GrantUpsertBulk) AddLimitWindowSeconds(v int) *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.AddLimitWindowSeconds(v)
	})
}

// UpdateLimitWindowSeconds sets the "limit_window_seconds" field to the value that was provided on create.
func (u *GrantUpsertBulk) UpdateLimitWindowSeconds() *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateLimitWindowSeconds()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *GrantUpsertBulk) SetExpiresAt(v time.Time) *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *GrantUpsertBulk) UpdateExpiresAt() *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *GrantUpsertBulk) ClearExpiresAt() *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.ClearExpiresAt()
	})
}

// SetGrantedBy sets the "granted_by" field.
func (u *GrantUpsertBulk) SetGrantedBy(v string) *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.SetGrantedBy(v)
	})
}

// UpdateGrantedBy sets the "granted_by" field to the value that was provided on create.
func (u *GrantUpsertBulk) UpdateGrantedBy() *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateGrantedBy()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *GrantUpsertBulk) SetRevokedAt(v time.Time) *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *GrantUpsertBulk) UpdateRevokedAt() *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *GrantUpsertBulk) ClearRevokedAt() *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.ClearRevokedAt()
	})
}

// SetRevokedBy sets the "revoked_by" field.
func (u *GrantUpsertBulk) SetRevokedBy(v string) *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.SetRevokedBy(v)
	})
}

// UpdateRevokedBy sets the "revoked_by" field to the value that was provided on create.
func (u *GrantUpsertBulk) UpdateRevokedBy() *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateRevokedBy()
	})
}

// SetReason sets the "reason" field.
func (u *GrantUpsertBulk) SetReason(v string) *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *GrantUpsertBulk) UpdateReason() *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateReason()
	})
}

// SetNodeID sets the "node_id" field.
func (u *GrantUpsertBulk) SetNodeID(v string) *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.SetNodeID(v)
	})
}

// UpdateNodeID sets the "node_id" field to the value that was provided on create.
func (u *GrantUpsertBulk) UpdateNodeID() *GrantUpsertBulk {
	return u.Update(func(s *GrantUpsert) {
		s.UpdateNodeID()
	})
}

// Exec executes the query.
func (u *GrantUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GrantCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GrantCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GrantUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
