// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/kontor/server/internal/db/ent/mcpapplication"
	"github.com/lx-wnk/kontor/server/internal/db/ent/schema"
)

// MCPApplicationCreate is the builder for creating a MCPApplication entity.
type MCPApplicationCreate struct {
	config
	mutation *MCPApplicationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetResourceID sets the "resource_id" field.
func (_c *MCPApplicationCreate) SetResourceID(v string) *MCPApplicationCreate {
	_c.mutation.SetResourceID(v)
	return _c
}

// SetServerName sets the "server_name" field.
func (_c *MCPApplicationCreate) SetServerName(v string) *MCPApplicationCreate {
	_c.mutation.SetServerName(v)
	return _c
}

// SetAttachAll sets the "attach_all" field.
func (_c *MCPApplicationCreate) SetAttachAll(v bool) *MCPApplicationCreate {
	_c.mutation.SetAttachAll(v)
	return _c
}

// SetNillableAttachAll sets the "attach_all" field if the given value is not nil.
func (_c *MCPApplicationCreate) SetNillableAttachAll(v *bool) *MCPApplicationCreate {
	if v != nil {
		_c.SetAttachAll(*v)
	}
	return _c
}

// SetRequiredEnv sets the "required_env" field.
func (_c *MCPApplicationCreate) SetRequiredEnv(v []string) *MCPApplicationCreate {
	_c.mutation.SetRequiredEnv(v)
	return _c
}

// SetCatalogue sets the "catalogue" field.
func (_c *MCPApplicationCreate) SetCatalogue(v []schema.CatalogueTool) *MCPApplicationCreate {
	_c.mutation.SetCatalogue(v)
	return _c
}

// SetCatalogueError sets the "catalogue_error" field.
func (_c *MCPApplicationCreate) SetCatalogueError(v string) *MCPApplicationCreate {
	_c.mutation.SetCatalogueError(v)
	return _c
}

// SetNillableCatalogueError sets the "catalogue_error" field if the given value is not nil.
func (_c *MCPApplicationCreate) SetNillableCatalogueError(v *string) *MCPApplicationCreate {
	if v != nil {
		_c.SetCatalogueError(*v)
	}
	return _c
}

// SetCatalogueRefreshedAt sets the "catalogue_refreshed_at" field.
func (_c *MCPApplicationCreate) SetCatalogueRefreshedAt(v time.Time) *MCPApplicationCreate {
	_c.mutation.SetCatalogueRefreshedAt(v)
	return _c
}

// SetNillableCatalogueRefreshedAt sets the "catalogue_refreshed_at" field if the given value is not nil.
func (_c *MCPApplicationCreate) SetNillableCatalogueRefreshedAt(v *time.Time) *MCPApplicationCreate {
	if v != nil {
		_c.SetCatalogueRefreshedAt(*v)
	}
	return _c
}

// SetEntry sets the "entry" field.
func (_c *MCPApplicationCreate) SetEntry(v []byte) *MCPApplicationCreate {
	_c.mutation.SetEntry(v)
	return _c
}

// SetExportToClaude sets the "export_to_claude" field.
func (_c *MCPApplicationCreate) SetExportToClaude(v bool) *MCPApplicationCreate {
	_c.mutation.SetExportToClaude(v)
	return _c
}

// SetNillableExportToClaude sets the "export_to_claude" field if the given value is not nil.
func (_c *MCPApplicationCreate) SetNillableExportToClaude(v *bool) *MCPApplicationCreate {
	if v != nil {
		_c.SetExportToClaude(*v)
	}
	return _c
}

// SetExportedHash sets the "exported_hash" field.
func (_c *MCPApplicationCreate) SetExportedHash(v string) *MCPApplicationCreate {
	_c.mutation.SetExportedHash(v)
	return _c
}

// SetNillableExportedHash sets the "exported_hash" field if the given value is not nil.
func (_c *MCPApplicationCreate) SetNillableExportedHash(v *string) *MCPApplicationCreate {
	if v != nil {
		_c.SetExportedHash(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MCPApplicationCreate) SetCreatedAt(v time.Time) *MCPApplicationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MCPApplicationCreate) SetNillableCreatedAt(v *time.Time) *MCPApplicationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MCPApplicationCreate) SetUpdatedAt(v time.Time) *MCPApplicationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MCPApplicationCreate) SetNillableUpdatedAt(v *time.Time) *MCPApplicationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MCPApplicationCreate) SetID(v string) *MCPApplicationCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the MCPApplicationMutation object of the builder.
func (_c *MCPApplicationCreate) Mutation() *MCPApplicationMutation {
	return _c.mutation
}

// Save creates the MCPApplication in the database.
func (_c *MCPApplicationCreate) Save(ctx context.Context) (*MCPApplication, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MCPApplicationCreate) SaveX(ctx context.Context) *MCPApplication {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MCPApplicationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MCPApplicationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MCPApplicationCreate) defaults() {
	if _, ok := _c.mutation.AttachAll(); !ok {
		v := mcpapplication.DefaultAttachAll
		_c.mutation.SetAttachAll(v)
	}
	if _, ok := _c.mutation.RequiredEnv(); !ok {
		v := mcpapplication.DefaultRequiredEnv
		_c.mutation.SetRequiredEnv(v)
	}
	if _, ok := _c.mutation.Catalogue(); !ok {
		v := mcpapplication.DefaultCatalogue
		_c.mutation.SetCatalogue(v)
	}
	if _, ok := _c.mutation.CatalogueError(); !ok {
		v := mcpapplication.DefaultCatalogueError
		_c.mutation.SetCatalogueError(v)
	}
	if _, ok := _c.mutation.Entry(); !ok {
		v := mcpapplication.DefaultEntry
		_c.mutation.SetEntry(v)
	}
	if _, ok := _c.mutation.ExportToClaude(); !ok {
		v := mcpapplication.DefaultExportToClaude
		_c.mutation.SetExportToClaude(v)
	}
	if _, ok := _c.mutation.ExportedHash(); !ok {
		v := mcpapplication.DefaultExportedHash
		_c.mutation.SetExportedHash(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := mcpapplication.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := mcpapplication.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MCPApplicationCreate) check() error {
	if _, ok := _c.mutation.ResourceID(); !ok {
		return &ValidationError{Name: "resource_id", err: errors.New(`ent: missing required field "MCPApplication.resource_id"`)}
	}
	if _, ok := _c.mutation.ServerName(); !ok {
		return &ValidationError{Name: "server_name", err: errors.New(`ent: missing required field "MCPApplication.server_name"`)}
	}
	if _, ok := _c.mutation.AttachAll(); !ok {
		return &ValidationError{Name: "attach_all", err: errors.New(`ent: missing required field "MCPApplication.attach_all"`)}
	}
	if _, ok := _c.mutation.RequiredEnv(); !ok {
		return &ValidationError{Name: "required_env", err: errors.New(`ent: missing required field "MCPApplication.required_env"`)}
	}
	if _, ok := _c.mutation.Catalogue(); !ok {
		return &ValidationError{Name: "catalogue", err: errors.New(`ent: missing required field "MCPApplication.catalogue"`)}
	}
	if _, ok := _c.mutation.CatalogueError(); !ok {
		return &ValidationError{Name: "catalogue_error", err: errors.New(`ent: missing required field "MCPApplication.catalogue_error"`)}
	}
	if _, ok := _c.mutation.Entry(); !ok {
		return &ValidationError{Name: "entry", err: errors.New(`ent: missing required field "MCPApplication.entry"`)}
	}
	if _, ok := _c.mutation.ExportToClaude(); !ok {
		return &ValidationError{Name: "export_to_claude", err: errors.New(`ent: missing required field "MCPApplication.export_to_claude"`)}
	}
	if _, ok := _c.mutation.ExportedHash(); !ok {
		return &ValidationError{Name: "exported_hash", err: errors.New(`ent: missing required field "MCPApplication.exported_hash"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MCPApplication.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MCPApplication.updated_at"`)}
	}
	return nil
}

func (_c *MCPApplicationCreate) sqlSave(ctx context.Context) (*MCPApplication, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected MCPApplication.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MCPApplicationCreate) createSpec() (*MCPApplication, *sqlgraph.CreateSpec) {
	var (
		_node = &MCPApplication{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(mcpapplication.Table, sqlgraph.NewFieldSpec(mcpapplication.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ResourceID(); ok {
		_spec.SetField(mcpapplication.FieldResourceID, field.TypeString, value)
		_node.ResourceID = value
	}
	if value, ok := _c.mutation.ServerName(); ok {
		_spec.SetField(mcpapplication.FieldServerName, field.TypeString, value)
		_node.ServerName = value
	}
	if value, ok := _c.mutation.AttachAll(); ok {
		_spec.SetField(mcpapplication.FieldAttachAll, field.TypeBool, value)
		_node.AttachAll = value
	}
	if value, ok := _c.mutation.RequiredEnv(); ok {
		_spec.SetField(mcpapplication.FieldRequiredEnv, field.TypeJSON, value)
		_node.RequiredEnv = value
	}
	if value, ok := _c.mutation.Catalogue(); ok {
		_spec.SetField(mcpapplication.FieldCatalogue, field.TypeJSON, value)
		_node.Catalogue = value
	}
	if value, ok := _c.mutation.CatalogueError(); ok {
		_spec.SetField(mcpapplication.FieldCatalogueError, field.TypeString, value)
		_node.CatalogueError = value
	}
	if value, ok := _c.mutation.CatalogueRefreshedAt(); ok {
		_spec.SetField(mcpapplication.FieldCatalogueRefreshedAt, field.TypeTime, value)
		_node.CatalogueRefreshedAt = &value
	}
	if value, ok := _c.mutation.Entry(); ok {
		_spec.SetField(mcpapplication.FieldEntry, field.TypeBytes, value)
		_node.Entry = value
	}
	if value, ok := _c.mutation.ExportToClaude(); ok {
		_spec.SetField(mcpapplication.FieldExportToClaude, field.TypeBool, value)
		_node.ExportToClaude = value
	}
	if value, ok := _c.mutation.ExportedHash(); ok {
		_spec.SetField(mcpapplication.FieldExportedHash, field.TypeString, value)
		_node.ExportedHash = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(mcpapplication.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(mcpapplication.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MCPApplication.Create().
//		SetResourceID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MCPApplicationUpsert) {
//			SetResourceID(v+v).
//		}).
//		Exec(ctx)
func (_c *MCPApplicationCreate) OnConflict(opts ...sql.ConflictOption) *MCPApplicationUpsertOne {
	_c.conflict = opts
	return &MCPApplicationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MCPApplication.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MCPApplicationCreate) OnConflictColumns(columns ...string) *MCPApplicationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MCPApplicationUpsertOne{
		create: _c,
	}
}

type (
	// MCPApplicationUpsertOne is the builder for "upsert"-ing
	//  one MCPApplication node.
	MCPApplicationUpsertOne struct {
		create *MCPApplicationCreate
	}

	// MCPApplicationUpsert is the "OnConflict" setter.
	MCPApplicationUpsert struct {
		*sql.UpdateSet
	}
)

// SetAttachAll sets the "attach_all" field.
func (u *MCPApplicationUpsert) SetAttachAll(v bool) *MCPApplicationUpsert {
	u.Set(mcpapplication.FieldAttachAll, v)
	return u
}

// UpdateAttachAll sets the "attach_all" field to the value that was provided on create.
func (u *MCPApplicationUpsert) UpdateAttachAll() *MCPApplicationUpsert {
	u.SetExcluded(mcpapplication.FieldAttachAll)
	return u
}

// SetRequiredEnv sets the "required_env" field.
func (u *MCPApplicationUpsert) SetRequiredEnv(v []string) *MCPApplicationUpsert {
	u.Set(mcpapplication.FieldRequiredEnv, v)
	return u
}

// UpdateRequiredEnv sets the "required_env" field to the value that was provided on create.
func (u *MCPApplicationUpsert) UpdateRequiredEnv() *MCPApplicationUpsert {
	u.SetExcluded(mcpapplication.FieldRequiredEnv)
	return u
}

// SetCatalogue sets the "catalogue" field.
func (u *MCPApplicationUpsert) SetCatalogue(v []schema.CatalogueTool) *MCPApplicationUpsert {
	u.Set(mcpapplication.FieldCatalogue, v)
	return u
}

// UpdateCatalogue sets the "catalogue" field to the value that was provided on create.
func (u *MCPApplicationUpsert) UpdateCatalogue() *MCPApplicationUpsert {
	u.SetExcluded(mcpapplication.FieldCatalogue)
	return u
}

// SetCatalogueError sets the "catalogue_error" field.
func (u *MCPApplicationUpsert) SetCatalogueError(v string) *MCPApplicationUpsert {
	u.Set(mcpapplication.FieldCatalogueError, v)
	return u
}

// UpdateCatalogueError sets the "catalogue_error" field to the value that was provided on create.
func (u *MCPApplicationUpsert) UpdateCatalogueError() *MCPApplicationUpsert {
	u.SetExcluded(mcpapplication.FieldCatalogueError)
	return u
}

// SetCatalogueRefreshedAt sets the "catalogue_refreshed_at" field.
func (u *MCPApplicationUpsert) SetCatalogueRefreshedAt(v time.Time) *MCPApplicationUpsert {
	u.Set(mcpapplication.FieldCatalogueRefreshedAt, v)
	return u
}

// UpdateCatalogueRefreshedAt sets the "catalogue_refreshed_at" field to the value that was provided on create.
func (u *MCPApplicationUpsert) UpdateCatalogueRefreshedAt() *MCPApplicationUpsert {
	u.SetExcluded(mcpapplication.FieldCatalogueRefreshedAt)
	return u
}

// ClearCatalogueRefreshedAt clears the value of the "catalogue_refreshed_at" field.
func (u *MCPApplicationUpsert) ClearCatalogueRefreshedAt() *MCPApplicationUpsert {
	u.SetNull(mcpapplication.FieldCatalogueRefreshedAt)
	return u
}

// SetEntry sets the "entry" field.
func (u *MCPApplicationUpsert) SetEntry(v []byte) *MCPApplicationUpsert {
	u.Set(mcpapplication.FieldEntry, v)
	return u
}

// UpdateEntry sets the "entry" field to the value that was provided on create.
func (u *MCPApplicationUpsert) UpdateEntry() *MCPApplicationUpsert {
	u.SetExcluded(mcpapplication.FieldEntry)
	return u
}

// SetExportToClaude sets the "export_to_claude" field.
func (u *MCPApplicationUpsert) SetExportToClaude(v bool) *MCPApplicationUpsert {
	u.Set(mcpapplication.FieldExportToClaude, v)
	return u
}

// UpdateExportToClaude sets the "export_to_claude" field to the value that was provided on create.
func (u *MCPApplicationUpsert) UpdateExportToClaude() *MCPApplicationUpsert {
	u.SetExcluded(mcpapplication.FieldExportToClaude)
	return u
}

// SetExportedHash sets the "exported_hash" field.
func (u *MCPApplicationUpsert) SetExportedHash(v string) *MCPApplicationUpsert {
	u.Set(mcpapplication.FieldExportedHash, v)
	return u
}

// UpdateExportedHash sets the "exported_hash" field to the value that was provided on create.
func (u *MCPApplicationUpsert) UpdateExportedHash() *MCPApplicationUpsert {
	u.SetExcluded(mcpapplication.FieldExportedHash)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MCPApplicationUpsert) SetUpdatedAt(v time.Time) *MCPApplicationUpsert {
	u.Set(mcpapplication.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MCPApplicationUpsert) UpdateUpdatedAt() *MCPApplicationUpsert {
	u.SetExcluded(mcpapplication.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.MCPApplication.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(mcpapplication.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MCPApplicationUpsertOne) UpdateNewValues() *MCPApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(mcpapplication.FieldID)
		}
		if _, exists := u.create.mutation.ResourceID(); exists {
			s.SetIgnore(mcpapplication.FieldResourceID)
		}
		if _, exists := u.create.mutation.ServerName(); exists {
			s.SetIgnore(mcpapplication.FieldServerName)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(mcpapplication.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MCPApplication.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MCPApplicationUpsertOne) Ignore() *MCPApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MCPApplicationUpsertOne) DoNothing() *MCPApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MCPApplicationCreate.OnConflict
// documentation for more info.
func (u *MCPApplicationUpsertOne) Update(set func(*MCPApplicationUpsert)) *MCPApplicationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MCPApplicationUpsert{UpdateSet: update})
	}))
	return u
}

// SetAttachAll sets the "attach_all" field.
func (u *MCPApplicationUpsertOne) SetAttachAll(v bool) *MCPApplicationUpsertOne {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.SetAttachAll(v)
	})
}

// UpdateAttachAll sets the "attach_all" field to the value that was provided on create.
func (u *MCPApplicationUpsertOne) UpdateAttachAll() *MCPApplicationUpsertOne {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.UpdateAttachAll()
	})
}

// SetRequiredEnv sets the "required_env" field.
func (u *MCPApplicationUpsertOne) SetRequiredEnv(v []string) *MCPApplicationUpsertOne {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.SetRequiredEnv(v)
	})
}

// UpdateRequiredEnv sets the "required_env" field to the value that was provided on create.
func (u *MCPApplicationUpsertOne) UpdateRequiredEnv() *MCPApplicationUpsertOne {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.UpdateRequiredEnv()
	})
}

// SetCatalogue sets the "catalogue" field.
func (u *MCPApplicationUpsertOne) SetCatalogue(v []schema.CatalogueTool) *MCPApplicationUpsertOne {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.SetCatalogue(v)
	})
}

// UpdateCatalogue sets the "catalogue" field to the value that was provided on create.
func (u *MCPApplicationUpsertOne) UpdateCatalogue() *MCPApplicationUpsertOne {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.UpdateCatalogue()
	})
}

// SetCatalogueError sets the "catalogue_error" field.
func (u *MCPApplicationUpsertOne) SetCatalogueError(v string) *MCPApplicationUpsertOne {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.SetCatalogueError(v)
	})
}

// UpdateCatalogueError sets the "catalogue_error" field to the value that was provided on create.
func (u *MCPApplicationUpsertOne) UpdateCatalogueError() *MCPApplicationUpsertOne {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.UpdateCatalogueError()
	})
}

// SetCatalogueRefreshedAt sets the "catalogue_refreshed_at" field.
func (u *MCPApplicationUpsertOne) SetCatalogueRefreshedAt(v time.Time) *MCPApplicationUpsertOne {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.SetCatalogueRefreshedAt(v)
	})
}

// UpdateCatalogueRefreshedAt sets the "catalogue_refreshed_at" field to the value that was provided on create.
func (u *MCPApplicationUpsertOne) UpdateCatalogueRefreshedAt() *MCPApplicationUpsertOne {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.UpdateCatalogueRefreshedAt()
	})
}

// ClearCatalogueRefreshedAt clears the value of the "catalogue_refreshed_at" field.
func (u *MCPApplicationUpsertOne) ClearCatalogueRefreshedAt() *MCPApplicationUpsertOne {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.ClearCatalogueRefreshedAt()
	})
}

// SetEntry sets the "entry" field.
func (u *MCPApplicationUpsertOne) SetEntry(v []byte) *MCPApplicationUpsertOne {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.SetEntry(v)
	})
}

// UpdateEntry sets the "entry" field to the value that was provided on create.
func (u *MCPApplicationUpsertOne) UpdateEntry() *MCPApplicationUpsertOne {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.UpdateEntry()
	})
}

// SetExportToClaude sets the "export_to_claude" field.
func (u *MCPApplicationUpsertOne) SetExportToClaude(v bool) *MCPApplicationUpsertOne {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.SetExportToClaude(v)
	})
}

// UpdateExportToClaude sets the "export_to_claude" field to the value that was provided on create.
func (u *MCPApplicationUpsertOne) UpdateExportToClaude() *MCPApplicationUpsertOne {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.UpdateExportToClaude()
	})
}

// SetExportedHash sets the "exported_hash" field.
func (u *MCPApplicationUpsertOne) SetExportedHash(v string) *MCPApplicationUpsertOne {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.SetExportedHash(v)
	})
}

// UpdateExportedHash sets the "exported_hash" field to the value that was provided on create.
func (u *MCPApplicationUpsertOne) UpdateExportedHash() *MCPApplicationUpsertOne {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.UpdateExportedHash()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MCPApplicationUpsertOne) SetUpdatedAt(v time.Time) *MCPApplicationUpsertOne {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MCPApplicationUpsertOne) UpdateUpdatedAt() *MCPApplicationUpsertOne {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *MCPApplicationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MCPApplicationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MCPApplicationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MCPApplicationUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: MCPApplicationUpsertOne.ID is not supported by MySQL driver. Use MCPApplicationUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MCPApplicationUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MCPApplicationCreateBulk is the builder for creating many MCPApplication entities in bulk.
type MCPApplicationCreateBulk struct {
	config
	err      error
	builders []*MCPApplicationCreate
	conflict []sql.ConflictOption
}

// Save creates the MCPApplication entities in the database.
func (_c *MCPApplicationCreateBulk) Save(ctx context.Context) ([]*MCPApplication, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MCPApplication, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MCPApplicationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MCPApplicationCreateBulk) SaveX(ctx context.Context) []*MCPApplication {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MCPApplicationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MCPApplicationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MCPApplication.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MCPApplicationUpsert) {
//			SetResourceID(v+v).
//		}).
//		Exec(ctx)
func (_c *MCPApplicationCreateBulk) OnConflict(opts ...sql.ConflictOption) *MCPApplicationUpsertBulk {
	_c.conflict = opts
	return &MCPApplicationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MCPApplication.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MCPApplicationCreateBulk) OnConflictColumns(columns ...string) *MCPApplicationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MCPApplicationUpsertBulk{
		create: _c,
	}
}

// MCPApplicationUpsertBulk is the builder for "upsert"-ing
// a bulk of MCPApplication nodes.
type MCPApplicationUpsertBulk struct {
	create *MCPApplicationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MCPApplication.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(mcpapplication.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MCPApplicationUpsertBulk) UpdateNewValues() *MCPApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(mcpapplication.FieldID)
			}
			if _, exists := b.mutation.ResourceID(); exists {
				s.SetIgnore(mcpapplication.FieldResourceID)
			}
			if _, exists := b.mutation.ServerName(); exists {
				s.SetIgnore(mcpapplication.FieldServerName)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(mcpapplication.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MCPApplication.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MCPApplicationUpsertBulk) Ignore() *MCPApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MCPApplicationUpsertBulk) DoNothing() *MCPApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MCPApplicationCreateBulk.OnConflict
// documentation for more info.
func (u *MCPApplicationUpsertBulk) Update(set func(*MCPApplicationUpsert)) *MCPApplicationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MCPApplicationUpsert{UpdateSet: update})
	}))
	return u
}

// SetAttachAll sets the "attach_all" field.
func (u *MCPApplicationUpsertBulk) SetAttachAll(v bool) *MCPApplicationUpsertBulk {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.SetAttachAll(v)
	})
}

// UpdateAttachAll sets the "attach_all" field to the value that was provided on create.
func (u *MCPApplicationUpsertBulk) UpdateAttachAll() *MCPApplicationUpsertBulk {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.UpdateAttachAll()
	})
}

// SetRequiredEnv sets the "required_env" field.
func (u *MCPApplicationUpsertBulk) SetRequiredEnv(v []string) *MCPApplicationUpsertBulk {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.SetRequiredEnv(v)
	})
}

// UpdateRequiredEnv sets the "required_env" field to the value that was provided on create.
func (u *MCPApplicationUpsertBulk) UpdateRequiredEnv() *MCPApplicationUpsertBulk {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.UpdateRequiredEnv()
	})
}

// SetCatalogue sets the "catalogue" field.
func (u *MCPApplicationUpsertBulk) SetCatalogue(v []schema.CatalogueTool) *MCPApplicationUpsertBulk {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.SetCatalogue(v)
	})
}

// UpdateCatalogue sets the "catalogue" field to the value that was provided on create.
func (u *MCPApplicationUpsertBulk) UpdateCatalogue() *MCPApplicationUpsertBulk {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.UpdateCatalogue()
	})
}

// SetCatalogueError sets the "catalogue_error" field.
func (u *MCPApplicationUpsertBulk) SetCatalogueError(v string) *MCPApplicationUpsertBulk {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.SetCatalogueError(v)
	})
}

// UpdateCatalogueError sets the "catalogue_error" field to the value that was provided on create.
func (u *MCPApplicationUpsertBulk) UpdateCatalogueError() *MCPApplicationUpsertBulk {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.UpdateCatalogueError()
	})
}

// SetCatalogueRefreshedAt sets the "catalogue_refreshed_at" field.
func (u *MCPApplicationUpsertBulk) SetCatalogueRefreshedAt(v time.Time) *MCPApplicationUpsertBulk {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.SetCatalogueRefreshedAt(v)
	})
}

// UpdateCatalogueRefreshedAt sets the "catalogue_refreshed_at" field to the value that was provided on create.
func (u *MCPApplicationUpsertBulk) UpdateCatalogueRefreshedAt() *MCPApplicationUpsertBulk {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.UpdateCatalogueRefreshedAt()
	})
}

// ClearCatalogueRefreshedAt clears the value of the "catalogue_refreshed_at" field.
func (u *MCPApplicationUpsertBulk) ClearCatalogueRefreshedAt() *MCPApplicationUpsertBulk {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.ClearCatalogueRefreshedAt()
	})
}

// SetEntry sets the "entry" field.
func (u *MCPApplicationUpsertBulk) SetEntry(v []byte) *MCPApplicationUpsertBulk {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.SetEntry(v)
	})
}

// UpdateEntry sets the "entry" field to the value that was provided on create.
func (u *MCPApplicationUpsertBulk) UpdateEntry() *MCPApplicationUpsertBulk {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.UpdateEntry()
	})
}

// SetExportToClaude sets the "export_to_claude" field.
func (u *MCPApplicationUpsertBulk) SetExportToClaude(v bool) *MCPApplicationUpsertBulk {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.SetExportToClaude(v)
	})
}

// UpdateExportToClaude sets the "export_to_claude" field to the value that was provided on create.
func (u *MCPApplicationUpsertBulk) UpdateExportToClaude() *MCPApplicationUpsertBulk {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.UpdateExportToClaude()
	})
}

// SetExportedHash sets the "exported_hash" field.
func (u *MCPApplicationUpsertBulk) SetExportedHash(v string) *MCPApplicationUpsertBulk {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.SetExportedHash(v)
	})
}

// UpdateExportedHash sets the "exported_hash" field to the value that was provided on create.
func (u *MCPApplicationUpsertBulk) UpdateExportedHash() *MCPApplicationUpsertBulk {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.UpdateExportedHash()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MCPApplicationUpsertBulk) SetUpdatedAt(v time.Time) *MCPApplicationUpsertBulk {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MCPApplicationUpsertBulk) UpdateUpdatedAt() *MCPApplicationUpsertBulk {
	return u.Update(func(s *MCPApplicationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *MCPApplicationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MCPApplicationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MCPApplicationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MCPApplicationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
