// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lx-wnk/kontor/server/internal/db/ent/memoryentry"
)

// MemoryEntry is the model entity for the MemoryEntry schema.
type MemoryEntry struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// SpaceID holds the value of the "space_id" field.
	SpaceID string `json:"space_id,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary string `json:"summary,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// SourceKind holds the value of the "source_kind" field.
	SourceKind string `json:"source_kind,omitempty"`
	// SourceRef holds the value of the "source_ref" field.
	SourceRef *string `json:"source_ref,omitempty"`
	// Confidence holds the value of the "confidence" field.
	Confidence float64 `json:"confidence,omitempty"`
	// ValidFrom holds the value of the "valid_from" field.
	ValidFrom time.Time `json:"valid_from,omitempty"`
	// ValidUntil holds the value of the "valid_until" field.
	ValidUntil *time.Time `json:"valid_until,omitempty"`
	// SupersededBy holds the value of the "superseded_by" field.
	SupersededBy *string `json:"superseded_by,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID       *string `json:"user_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MemoryEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case memoryentry.FieldConfidence:
			values[i] = new(sql.NullFloat64)
		case memoryentry.FieldID, memoryentry.FieldSpaceID, memoryentry.FieldSummary, memoryentry.FieldContent, memoryentry.FieldKind, memoryentry.FieldSourceKind, memoryentry.FieldSourceRef, memoryentry.FieldSupersededBy, memoryentry.FieldUserID:
			values[i] = new(sql.NullString)
		case memoryentry.FieldCreatedAt, memoryentry.FieldUpdatedAt, memoryentry.FieldValidFrom, memoryentry.FieldValidUntil:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MemoryEntry fields.
func (_m *MemoryEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case memoryentry.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case memoryentry.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case memoryentry.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case memoryentry.FieldSpaceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field space_id", values[i])
			} else if value.Valid {
				_m.SpaceID = value.String
			}
		case memoryentry.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case memoryentry.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case memoryentry.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case memoryentry.FieldSourceKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_kind", values[i])
			} else if value.Valid {
				_m.SourceKind = value.String
			}
		case memoryentry.FieldSourceRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_ref", values[i])
			} else if value.Valid {
				_m.SourceRef = new(string)
				*_m.SourceRef = value.String
			}
		case memoryentry.FieldConfidence:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field confidence", values[i])
			} else if value.Valid {
				_m.Confidence = value.Float64
			}
		case memoryentry.FieldValidFrom:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field valid_from", values[i])
			} else if value.Valid {
				_m.ValidFrom = value.Time
			}
		case memoryentry.FieldValidUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field valid_until", values[i])
			} else if value.Valid {
				_m.ValidUntil = new(time.Time)
				*_m.ValidUntil = value.Time
			}
		case memoryentry.FieldSupersededBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field superseded_by", values[i])
			} else if value.Valid {
				_m.SupersededBy = new(string)
				*_m.SupersededBy = value.String
			}
		case memoryentry.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(string)
				*_m.UserID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MemoryEntry.
// This includes values selected through modifiers, order, etc.
func (_m *MemoryEntry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MemoryEntry.
// Note that you need to call MemoryEntry.Unwrap() before calling this method if this MemoryEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MemoryEntry) Update() *MemoryEntryUpdateOne {
	return NewMemoryEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MemoryEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MemoryEntry) Unwrap() *MemoryEntry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MemoryEntry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MemoryEntry) String() string {
	var builder strings.Builder
	builder.WriteString("MemoryEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("space_id=")
	builder.WriteString(_m.SpaceID)
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("source_kind=")
	builder.WriteString(_m.SourceKind)
	builder.WriteString(", ")
	if v := _m.SourceRef; v != nil {
		builder.WriteString("source_ref=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("confidence=")
	builder.WriteString(fmt.Sprintf("%v", _m.Confidence))
	builder.WriteString(", ")
	builder.WriteString("valid_from=")
	builder.WriteString(_m.ValidFrom.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ValidUntil; v != nil {
		builder.WriteString("valid_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SupersededBy; v != nil {
		builder.WriteString("superseded_by=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// MemoryEntries is a parsable slice of MemoryEntry.
type MemoryEntries []*MemoryEntry
