// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/kontor/server/internal/db/ent/permissionpreset"
)

// PermissionPresetCreate is the builder for creating a PermissionPreset entity.
type PermissionPresetCreate struct {
	config
	mutation *PermissionPresetMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *PermissionPresetCreate) SetUserID(v string) *PermissionPresetCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *PermissionPresetCreate) SetNillableUserID(v *string) *PermissionPresetCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetProjectCwd sets the "project_cwd" field.
func (_c *PermissionPresetCreate) SetProjectCwd(v string) *PermissionPresetCreate {
	_c.mutation.SetProjectCwd(v)
	return _c
}

// SetTool sets the "tool" field.
func (_c *PermissionPresetCreate) SetTool(v string) *PermissionPresetCreate {
	_c.mutation.SetTool(v)
	return _c
}

// SetPattern sets the "pattern" field.
func (_c *PermissionPresetCreate) SetPattern(v string) *PermissionPresetCreate {
	_c.mutation.SetPattern(v)
	return _c
}

// SetNillablePattern sets the "pattern" field if the given value is not nil.
func (_c *PermissionPresetCreate) SetNillablePattern(v *string) *PermissionPresetCreate {
	if v != nil {
		_c.SetPattern(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PermissionPresetCreate) SetID(v string) *PermissionPresetCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PermissionPresetMutation object of the builder.
func (_c *PermissionPresetCreate) Mutation() *PermissionPresetMutation {
	return _c.mutation
}

// Save creates the PermissionPreset in the database.
func (_c *PermissionPresetCreate) Save(ctx context.Context) (*PermissionPreset, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PermissionPresetCreate) SaveX(ctx context.Context) *PermissionPreset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PermissionPresetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PermissionPresetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PermissionPresetCreate) check() error {
	if _, ok := _c.mutation.ProjectCwd(); !ok {
		return &ValidationError{Name: "project_cwd", err: errors.New(`ent: missing required field "PermissionPreset.project_cwd"`)}
	}
	if _, ok := _c.mutation.Tool(); !ok {
		return &ValidationError{Name: "tool", err: errors.New(`ent: missing required field "PermissionPreset.tool"`)}
	}
	return nil
}

func (_c *PermissionPresetCreate) sqlSave(ctx context.Context) (*PermissionPreset, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected PermissionPreset.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PermissionPresetCreate) createSpec() (*PermissionPreset, *sqlgraph.CreateSpec) {
	var (
		_node = &PermissionPreset{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(permissionpreset.Table, sqlgraph.NewFieldSpec(permissionpreset.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(permissionpreset.FieldUserID, field.TypeString, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.ProjectCwd(); ok {
		_spec.SetField(permissionpreset.FieldProjectCwd, field.TypeString, value)
		_node.ProjectCwd = value
	}
	if value, ok := _c.mutation.Tool(); ok {
		_spec.SetField(permissionpreset.FieldTool, field.TypeString, value)
		_node.Tool = value
	}
	if value, ok := _c.mutation.Pattern(); ok {
		_spec.SetField(permissionpreset.FieldPattern, field.TypeString, value)
		_node.Pattern = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PermissionPreset.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PermissionPresetUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *PermissionPresetCreate) OnConflict(opts ...sql.ConflictOption) *PermissionPresetUpsertOne {
	_c.conflict = opts
	return &PermissionPresetUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PermissionPreset.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PermissionPresetCreate) OnConflictColumns(columns ...string) *PermissionPresetUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PermissionPresetUpsertOne{
		create: _c,
	}
}

type (
	// PermissionPresetUpsertOne is the builder for "upsert"-ing
	//  one PermissionPreset node.
	PermissionPresetUpsertOne struct {
		create *PermissionPresetCreate
	}

	// PermissionPresetUpsert is the "OnConflict" setter.
	PermissionPresetUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *PermissionPresetUpsert) SetUserID(v string) *PermissionPresetUpsert {
	u.Set(permissionpreset.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PermissionPresetUpsert) UpdateUserID() *PermissionPresetUpsert {
	u.SetExcluded(permissionpreset.FieldUserID)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *PermissionPresetUpsert) ClearUserID() *PermissionPresetUpsert {
	u.SetNull(permissionpreset.FieldUserID)
	return u
}

// SetProjectCwd sets the "project_cwd" field.
func (u *PermissionPresetUpsert) SetProjectCwd(v string) *PermissionPresetUpsert {
	u.Set(permissionpreset.FieldProjectCwd, v)
	return u
}

// UpdateProjectCwd sets the "project_cwd" field to the value that was provided on create.
func (u *PermissionPresetUpsert) UpdateProjectCwd() *PermissionPresetUpsert {
	u.SetExcluded(permissionpreset.FieldProjectCwd)
	return u
}

// SetTool sets the "tool" field.
func (u *PermissionPresetUpsert) SetTool(v string) *PermissionPresetUpsert {
	u.Set(permissionpreset.FieldTool, v)
	return u
}

// UpdateTool sets the "tool" field to the value that was provided on create.
func (u *PermissionPresetUpsert) UpdateTool() *PermissionPresetUpsert {
	u.SetExcluded(permissionpreset.FieldTool)
	return u
}

// SetPattern sets the "pattern" field.
func (u *PermissionPresetUpsert) SetPattern(v string) *PermissionPresetUpsert {
	u.Set(permissionpreset.FieldPattern, v)
	return u
}

// UpdatePattern sets the "pattern" field to the value that was provided on create.
func (u *PermissionPresetUpsert) UpdatePattern() *PermissionPresetUpsert {
	u.SetExcluded(permissionpreset.FieldPattern)
	return u
}

// ClearPattern clears the value of the "pattern" field.
func (u *PermissionPresetUpsert) ClearPattern() *PermissionPresetUpsert {
	u.SetNull(permissionpreset.FieldPattern)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PermissionPreset.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(permissionpreset.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PermissionPresetUpsertOne) UpdateNewValues() *PermissionPresetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(permissionpreset.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PermissionPreset.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PermissionPresetUpsertOne) Ignore() *PermissionPresetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PermissionPresetUpsertOne) DoNothing() *PermissionPresetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PermissionPresetCreate.OnConflict
// documentation for more info.
func (u *PermissionPresetUpsertOne) Update(set func(*PermissionPresetUpsert)) *PermissionPresetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PermissionPresetUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *PermissionPresetUpsertOne) SetUserID(v string) *PermissionPresetUpsertOne {
	return u.Update(func(s *PermissionPresetUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PermissionPresetUpsertOne) UpdateUserID() *PermissionPresetUpsertOne {
	return u.Update(func(s *PermissionPresetUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *PermissionPresetUpsertOne) ClearUserID() *PermissionPresetUpsertOne {
	return u.Update(func(s *PermissionPresetUpsert) {
		s.ClearUserID()
	})
}

// SetProjectCwd sets the "project_cwd" field.
func (u *PermissionPresetUpsertOne) SetProjectCwd(v string) *PermissionPresetUpsertOne {
	return u.Update(func(s *PermissionPresetUpsert) {
		s.SetProjectCwd(v)
	})
}

// UpdateProjectCwd sets the "project_cwd" field to the value that was provided on create.
func (u *PermissionPresetUpsertOne) UpdateProjectCwd() *PermissionPresetUpsertOne {
	return u.Update(func(s *PermissionPresetUpsert) {
		s.UpdateProjectCwd()
	})
}

// SetTool sets the "tool" field.
func (u *PermissionPresetUpsertOne) SetTool(v string) *PermissionPresetUpsertOne {
	return u.Update(func(s *PermissionPresetUpsert) {
		s.SetTool(v)
	})
}

// UpdateTool sets the "tool" field to the value that was provided on create.
func (u *PermissionPresetUpsertOne) UpdateTool() *PermissionPresetUpsertOne {
	return u.Update(func(s *PermissionPresetUpsert) {
		s.UpdateTool()
	})
}

// SetPattern sets the "pattern" field.
func (u *PermissionPresetUpsertOne) SetPattern(v string) *PermissionPresetUpsertOne {
	return u.Update(func(s *PermissionPresetUpsert) {
		s.SetPattern(v)
	})
}

// UpdatePattern sets the "pattern" field to the value that was provided on create.
func (u *PermissionPresetUpsertOne) UpdatePattern() *PermissionPresetUpsertOne {
	return u.Update(func(s *PermissionPresetUpsert) {
		s.UpdatePattern()
	})
}

// ClearPattern clears the value of the "pattern" field.
func (u *PermissionPresetUpsertOne) ClearPattern() *PermissionPresetUpsertOne {
	return u.Update(func(s *PermissionPresetUpsert) {
		s.ClearPattern()
	})
}

// Exec executes the query.
func (u *PermissionPresetUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PermissionPresetCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PermissionPresetUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PermissionPresetUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PermissionPresetUpsertOne.ID is not supported by MySQL driver. Use PermissionPresetUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PermissionPresetUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PermissionPresetCreateBulk is the builder for creating many PermissionPreset entities in bulk.
type PermissionPresetCreateBulk struct {
	config
	err      error
	builders []*PermissionPresetCreate
	conflict []sql.ConflictOption
}

// Save creates the PermissionPreset entities in the database.
func (_c *PermissionPresetCreateBulk) Save(ctx context.Context) ([]*PermissionPreset, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PermissionPreset, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PermissionPresetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PermissionPresetCreateBulk) SaveX(ctx context.Context) []*PermissionPreset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PermissionPresetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PermissionPresetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PermissionPreset.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PermissionPresetUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *PermissionPresetCreateBulk) OnConflict(opts ...sql.ConflictOption) *PermissionPresetUpsertBulk {
	_c.conflict = opts
	return &PermissionPresetUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PermissionPreset.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PermissionPresetCreateBulk) OnConflictColumns(columns ...string) *PermissionPresetUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PermissionPresetUpsertBulk{
		create: _c,
	}
}

// PermissionPresetUpsertBulk is the builder for "upsert"-ing
// a bulk of PermissionPreset nodes.
type PermissionPresetUpsertBulk struct {
	create *PermissionPresetCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PermissionPreset.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(permissionpreset.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PermissionPresetUpsertBulk) UpdateNewValues() *PermissionPresetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(permissionpreset.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PermissionPreset.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PermissionPresetUpsertBulk) Ignore() *PermissionPresetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PermissionPresetUpsertBulk) DoNothing() *PermissionPresetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PermissionPresetCreateBulk.OnConflict
// documentation for more info.
func (u *PermissionPresetUpsertBulk) Update(set func(*PermissionPresetUpsert)) *PermissionPresetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PermissionPresetUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *PermissionPresetUpsertBulk) SetUserID(v string) *PermissionPresetUpsertBulk {
	return u.Update(func(s *PermissionPresetUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PermissionPresetUpsertBulk) UpdateUserID() *PermissionPresetUpsertBulk {
	return u.Update(func(s *PermissionPresetUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *PermissionPresetUpsertBulk) ClearUserID() *PermissionPresetUpsertBulk {
	return u.Update(func(s *PermissionPresetUpsert) {
		s.ClearUserID()
	})
}

// SetProjectCwd sets the "project_cwd" field.
func (u *PermissionPresetUpsertBulk) SetProjectCwd(v string) *PermissionPresetUpsertBulk {
	return u.Update(func(s *PermissionPresetUpsert) {
		s.SetProjectCwd(v)
	})
}

// UpdateProjectCwd sets the "project_cwd" field to the value that was provided on create.
func (u *PermissionPresetUpsertBulk) UpdateProjectCwd() *PermissionPresetUpsertBulk {
	return u.Update(func(s *PermissionPresetUpsert) {
		s.UpdateProjectCwd()
	})
}

// SetTool sets the "tool" field.
func (u *PermissionPresetUpsertBulk) SetTool(v string) *PermissionPresetUpsertBulk {
	return u.Update(func(s *PermissionPresetUpsert) {
		s.SetTool(v)
	})
}

// UpdateTool sets the "tool" field to the value that was provided on create.
func (u *PermissionPresetUpsertBulk) UpdateTool() *PermissionPresetUpsertBulk {
	return u.Update(func(s *PermissionPresetUpsert) {
		s.UpdateTool()
	})
}

// SetPattern sets the "pattern" field.
func (u *PermissionPresetUpsertBulk) SetPattern(v string) *PermissionPresetUpsertBulk {
	return u.Update(func(s *PermissionPresetUpsert) {
		s.SetPattern(v)
	})
}

// UpdatePattern sets the "pattern" field to the value that was provided on create.
func (u *PermissionPresetUpsertBulk) UpdatePattern() *PermissionPresetUpsertBulk {
	return u.Update(func(s *PermissionPresetUpsert) {
		s.UpdatePattern()
	})
}

// ClearPattern clears the value of the "pattern" field.
func (u *PermissionPresetUpsertBulk) ClearPattern() *PermissionPresetUpsertBulk {
	return u.Update(func(s *PermissionPresetUpsert) {
		s.ClearPattern()
	})
}

// Exec executes the query.
func (u *PermissionPresetUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PermissionPresetCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PermissionPresetCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PermissionPresetUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
