// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/kontor/server/internal/db/ent/permissionpreset"
	"github.com/lx-wnk/kontor/server/internal/db/ent/predicate"
)

// PermissionPresetDelete is the builder for deleting a PermissionPreset entity.
type PermissionPresetDelete struct {
	config
	hooks    []Hook
	mutation *PermissionPresetMutation
}

// Where appends a list predicates to the PermissionPresetDelete builder.
func (_d *PermissionPresetDelete) Where(ps ...predicate.PermissionPreset) *PermissionPresetDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PermissionPresetDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PermissionPresetDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PermissionPresetDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(permissionpreset.Table, sqlgraph.NewFieldSpec(permissionpreset.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PermissionPresetDeleteOne is the builder for deleting a single PermissionPreset entity.
type PermissionPresetDeleteOne struct {
	_d *PermissionPresetDelete
}

// Where appends a list predicates to the PermissionPresetDelete builder.
func (_d *PermissionPresetDeleteOne) Where(ps ...predicate.PermissionPreset) *PermissionPresetDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PermissionPresetDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{permissionpreset.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PermissionPresetDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
