// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/kontor/server/internal/db/ent/pipelineconfig"
)

// PipelineConfigCreate is the builder for creating a PipelineConfig entity.
type PipelineConfigCreate struct {
	config
	mutation *PipelineConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetKey sets the "key" field.
func (_c *PipelineConfigCreate) SetKey(v string) *PipelineConfigCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *PipelineConfigCreate) SetProjectID(v string) *PipelineConfigCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_c *PipelineConfigCreate) SetNillableProjectID(v *string) *PipelineConfigCreate {
	if v != nil {
		_c.SetProjectID(*v)
	}
	return _c
}

// SetValue sets the "value" field.
func (_c *PipelineConfigCreate) SetValue(v string) *PipelineConfigCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PipelineConfigCreate) SetID(v string) *PipelineConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PipelineConfigMutation object of the builder.
func (_c *PipelineConfigCreate) Mutation() *PipelineConfigMutation {
	return _c.mutation
}

// Save creates the PipelineConfig in the database.
func (_c *PipelineConfigCreate) Save(ctx context.Context) (*PipelineConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PipelineConfigCreate) SaveX(ctx context.Context) *PipelineConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PipelineConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PipelineConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PipelineConfigCreate) defaults() {
	if _, ok := _c.mutation.ProjectID(); !ok {
		v := pipelineconfig.DefaultProjectID
		_c.mutation.SetProjectID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PipelineConfigCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "PipelineConfig.key"`)}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "PipelineConfig.project_id"`)}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "PipelineConfig.value"`)}
	}
	return nil
}

func (_c *PipelineConfigCreate) sqlSave(ctx context.Context) (*PipelineConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected PipelineConfig.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PipelineConfigCreate) createSpec() (*PipelineConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &PipelineConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pipelineconfig.Table, sqlgraph.NewFieldSpec(pipelineconfig.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(pipelineconfig.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.ProjectID(); ok {
		_spec.SetField(pipelineconfig.FieldProjectID, field.TypeString, value)
		_node.ProjectID = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(pipelineconfig.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PipelineConfig.Create().
//		SetKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PipelineConfigUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *PipelineConfigCreate) OnConflict(opts ...sql.ConflictOption) *PipelineConfigUpsertOne {
	_c.conflict = opts
	return &PipelineConfigUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PipelineConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PipelineConfigCreate) OnConflictColumns(columns ...string) *PipelineConfigUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PipelineConfigUpsertOne{
		create: _c,
	}
}

type (
	// PipelineConfigUpsertOne is the builder for "upsert"-ing
	//  one PipelineConfig node.
	PipelineConfigUpsertOne struct {
		create *PipelineConfigCreate
	}

	// PipelineConfigUpsert is the "OnConflict" setter.
	PipelineConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetProjectID sets the "project_id" field.
func (u *PipelineConfigUpsert) SetProjectID(v string) *PipelineConfigUpsert {
	u.Set(pipelineconfig.FieldProjectID, v)
	return u
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *PipelineConfigUpsert) UpdateProjectID() *PipelineConfigUpsert {
	u.SetExcluded(pipelineconfig.FieldProjectID)
	return u
}

// SetValue sets the "value" field.
func (u *PipelineConfigUpsert) SetValue(v string) *PipelineConfigUpsert {
	u.Set(pipelineconfig.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *PipelineConfigUpsert) UpdateValue() *PipelineConfigUpsert {
	u.SetExcluded(pipelineconfig.FieldValue)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PipelineConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(pipelineconfig.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PipelineConfigUpsertOne) UpdateNewValues() *PipelineConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(pipelineconfig.FieldID)
		}
		if _, exists := u.create.mutation.Key(); exists {
			s.SetIgnore(pipelineconfig.FieldKey)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PipelineConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PipelineConfigUpsertOne) Ignore() *PipelineConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PipelineConfigUpsertOne) DoNothing() *PipelineConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PipelineConfigCreate.OnConflict
// documentation for more info.
func (u *PipelineConfigUpsertOne) Update(set func(*PipelineConfigUpsert)) *PipelineConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PipelineConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetProjectID sets the "project_id" field.
func (u *PipelineConfigUpsertOne) SetProjectID(v string) *PipelineConfigUpsertOne {
	return u.Update(func(s *PipelineConfigUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *PipelineConfigUpsertOne) UpdateProjectID() *PipelineConfigUpsertOne {
	return u.Update(func(s *PipelineConfigUpsert) {
		s.UpdateProjectID()
	})
}

// SetValue sets the "value" field.
func (u *PipelineConfigUpsertOne) SetValue(v string) *PipelineConfigUpsertOne {
	return u.Update(func(s *PipelineConfigUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *PipelineConfigUpsertOne) UpdateValue() *PipelineConfigUpsertOne {
	return u.Update(func(s *PipelineConfigUpsert) {
		s.UpdateValue()
	})
}

// Exec executes the query.
func (u *PipelineConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PipelineConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PipelineConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PipelineConfigUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PipelineConfigUpsertOne.ID is not supported by MySQL driver. Use PipelineConfigUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PipelineConfigUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PipelineConfigCreateBulk is the builder for creating many PipelineConfig entities in bulk.
type PipelineConfigCreateBulk struct {
	config
	err      error
	builders []*PipelineConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the PipelineConfig entities in the database.
func (_c *PipelineConfigCreateBulk) Save(ctx context.Context) ([]*PipelineConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PipelineConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PipelineConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PipelineConfigCreateBulk) SaveX(ctx context.Context) []*PipelineConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PipelineConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PipelineConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PipelineConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PipelineConfigUpsert) {
//			SetKey(v+v).
//		}).
//		Exec(ctx)
func (_c *PipelineConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *PipelineConfigUpsertBulk {
	_c.conflict = opts
	return &PipelineConfigUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PipelineConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PipelineConfigCreateBulk) OnConflictColumns(columns ...string) *PipelineConfigUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PipelineConfigUpsertBulk{
		create: _c,
	}
}

// PipelineConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of PipelineConfig nodes.
type PipelineConfigUpsertBulk struct {
	create *PipelineConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PipelineConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(pipelineconfig.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PipelineConfigUpsertBulk) UpdateNewValues() *PipelineConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(pipelineconfig.FieldID)
			}
			if _, exists := b.mutation.Key(); exists {
				s.SetIgnore(pipelineconfig.FieldKey)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PipelineConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PipelineConfigUpsertBulk) Ignore() *PipelineConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PipelineConfigUpsertBulk) DoNothing() *PipelineConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PipelineConfigCreateBulk.OnConflict
// documentation for more info.
func (u *PipelineConfigUpsertBulk) Update(set func(*PipelineConfigUpsert)) *PipelineConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PipelineConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetProjectID sets the "project_id" field.
func (u *PipelineConfigUpsertBulk) SetProjectID(v string) *PipelineConfigUpsertBulk {
	return u.Update(func(s *PipelineConfigUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *PipelineConfigUpsertBulk) UpdateProjectID() *PipelineConfigUpsertBulk {
	return u.Update(func(s *PipelineConfigUpsert) {
		s.UpdateProjectID()
	})
}

// SetValue sets the "value" field.
func (u *PipelineConfigUpsertBulk) SetValue(v string) *PipelineConfigUpsertBulk {
	return u.Update(func(s *PipelineConfigUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *PipelineConfigUpsertBulk) UpdateValue() *PipelineConfigUpsertBulk {
	return u.Update(func(s *PipelineConfigUpsert) {
		s.UpdateValue()
	})
}

// Exec executes the query.
func (u *PipelineConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PipelineConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PipelineConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PipelineConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
