// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/kontor/server/internal/db/ent/resource"
)

// ResourceCreate is the builder for creating a Resource entity.
type ResourceCreate struct {
	config
	mutation *ResourceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResourceCreate) SetCreatedAt(v time.Time) *ResourceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableCreatedAt(v *time.Time) *ResourceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ResourceCreate) SetUpdatedAt(v time.Time) *ResourceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableUpdatedAt(v *time.Time) *ResourceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetKind sets the "kind" field.
func (_c *ResourceCreate) SetKind(v string) *ResourceCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetSlug sets the "slug" field.
func (_c *ResourceCreate) SetSlug(v string) *ResourceCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ResourceCreate) SetName(v string) *ResourceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableName(v *string) *ResourceCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetScopeKind sets the "scope_kind" field.
func (_c *ResourceCreate) SetScopeKind(v string) *ResourceCreate {
	_c.mutation.SetScopeKind(v)
	return _c
}

// SetNillableScopeKind sets the "scope_kind" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableScopeKind(v *string) *ResourceCreate {
	if v != nil {
		_c.SetScopeKind(*v)
	}
	return _c
}

// SetScopeRef sets the "scope_ref" field.
func (_c *ResourceCreate) SetScopeRef(v string) *ResourceCreate {
	_c.mutation.SetScopeRef(v)
	return _c
}

// SetNillableScopeRef sets the "scope_ref" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableScopeRef(v *string) *ResourceCreate {
	if v != nil {
		_c.SetScopeRef(*v)
	}
	return _c
}

// SetNodeID sets the "node_id" field.
func (_c *ResourceCreate) SetNodeID(v string) *ResourceCreate {
	_c.mutation.SetNodeID(v)
	return _c
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableNodeID(v *string) *ResourceCreate {
	if v != nil {
		_c.SetNodeID(*v)
	}
	return _c
}

// SetState sets the "state" field.
func (_c *ResourceCreate) SetState(v string) *ResourceCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableState(v *string) *ResourceCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *ResourceCreate) SetVersion(v string) *ResourceCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableVersion(v *string) *ResourceCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetOrigin sets the "origin" field.
func (_c *ResourceCreate) SetOrigin(v string) *ResourceCreate {
	_c.mutation.SetOrigin(v)
	return _c
}

// SetNillableOrigin sets the "origin" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableOrigin(v *string) *ResourceCreate {
	if v != nil {
		_c.SetOrigin(*v)
	}
	return _c
}

// SetOriginRef sets the "origin_ref" field.
func (_c *ResourceCreate) SetOriginRef(v string) *ResourceCreate {
	_c.mutation.SetOriginRef(v)
	return _c
}

// SetNillableOriginRef sets the "origin_ref" field if the given value is not nil.
func (_c *ResourceCreate) SetNillableOriginRef(v *string) *ResourceCreate {
	if v != nil {
		_c.SetOriginRef(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ResourceCreate) SetID(v string) *ResourceCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ResourceMutation object of the builder.
func (_c *ResourceCreate) Mutation() *ResourceMutation {
	return _c.mutation
}

// Save creates the Resource in the database.
func (_c *ResourceCreate) Save(ctx context.Context) (*Resource, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResourceCreate) SaveX(ctx context.Context) *Resource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResourceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := resource.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := resource.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Name(); !ok {
		v := resource.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.ScopeKind(); !ok {
		v := resource.DefaultScopeKind
		_c.mutation.SetScopeKind(v)
	}
	if _, ok := _c.mutation.ScopeRef(); !ok {
		v := resource.DefaultScopeRef
		_c.mutation.SetScopeRef(v)
	}
	if _, ok := _c.mutation.NodeID(); !ok {
		v := resource.DefaultNodeID
		_c.mutation.SetNodeID(v)
	}
	if _, ok := _c.mutation.State(); !ok {
		v := resource.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := resource.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.Origin(); !ok {
		v := resource.DefaultOrigin
		_c.mutation.SetOrigin(v)
	}
	if _, ok := _c.mutation.OriginRef(); !ok {
		v := resource.DefaultOriginRef
		_c.mutation.SetOriginRef(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResourceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Resource.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Resource.updated_at"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Resource.kind"`)}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Resource.slug"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Resource.name"`)}
	}
	if _, ok := _c.mutation.ScopeKind(); !ok {
		return &ValidationError{Name: "scope_kind", err: errors.New(`ent: missing required field "Resource.scope_kind"`)}
	}
	if _, ok := _c.mutation.ScopeRef(); !ok {
		return &ValidationError{Name: "scope_ref", err: errors.New(`ent: missing required field "Resource.scope_ref"`)}
	}
	if _, ok := _c.mutation.NodeID(); !ok {
		return &ValidationError{Name: "node_id", err: errors.New(`ent: missing required field "Resource.node_id"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Resource.state"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Resource.version"`)}
	}
	if _, ok := _c.mutation.Origin(); !ok {
		return &ValidationError{Name: "origin", err: errors.New(`ent: missing required field "Resource.origin"`)}
	}
	if _, ok := _c.mutation.OriginRef(); !ok {
		return &ValidationError{Name: "origin_ref", err: errors.New(`ent: missing required field "Resource.origin_ref"`)}
	}
	return nil
}

func (_c *ResourceCreate) sqlSave(ctx context.Context) (*Resource, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Resource.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResourceCreate) createSpec() (*Resource, *sqlgraph.CreateSpec) {
	var (
		_node = &Resource{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(resource.Table, sqlgraph.NewFieldSpec(resource.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(resource.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(resource.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(resource.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(resource.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(resource.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ScopeKind(); ok {
		_spec.SetField(resource.FieldScopeKind, field.TypeString, value)
		_node.ScopeKind = value
	}
	if value, ok := _c.mutation.ScopeRef(); ok {
		_spec.SetField(resource.FieldScopeRef, field.TypeString, value)
		_node.ScopeRef = value
	}
	if value, ok := _c.mutation.NodeID(); ok {
		_spec.SetField(resource.FieldNodeID, field.TypeString, value)
		_node.NodeID = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(resource.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(resource.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Origin(); ok {
		_spec.SetField(resource.FieldOrigin, field.TypeString, value)
		_node.Origin = value
	}
	if value, ok := _c.mutation.OriginRef(); ok {
		_spec.SetField(resource.FieldOriginRef, field.TypeString, value)
		_node.OriginRef = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Resource.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResourceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ResourceCreate) OnConflict(opts ...sql.ConflictOption) *ResourceUpsertOne {
	_c.conflict = opts
	return &ResourceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Resource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResourceCreate) OnConflictColumns(columns ...string) *ResourceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResourceUpsertOne{
		create: _c,
	}
}

type (
	// ResourceUpsertOne is the builder for "upsert"-ing
	//  one Resource node.
	ResourceUpsertOne struct {
		create *ResourceCreate
	}

	// ResourceUpsert is the "OnConflict" setter.
	ResourceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ResourceUpsert) SetUpdatedAt(v time.Time) *ResourceUpsert {
	u.Set(resource.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResourceUpsert) UpdateUpdatedAt() *ResourceUpsert {
	u.SetExcluded(resource.FieldUpdatedAt)
	return u
}

// SetSlug sets the "slug" field.
func (u *ResourceUpsert) SetSlug(v string) *ResourceUpsert {
	u.Set(resource.FieldSlug, v)
	return u
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *ResourceUpsert) UpdateSlug() *ResourceUpsert {
	u.SetExcluded(resource.FieldSlug)
	return u
}

// SetName sets the "name" field.
func (u *ResourceUpsert) SetName(v string) *ResourceUpsert {
	u.Set(resource.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ResourceUpsert) UpdateName() *ResourceUpsert {
	u.SetExcluded(resource.FieldName)
	return u
}

// SetScopeKind sets the "scope_kind" field.
func (u *ResourceUpsert) SetScopeKind(v string) *ResourceUpsert {
	u.Set(resource.FieldScopeKind, v)
	return u
}

// UpdateScopeKind sets the "scope_kind" field to the value that was provided on create.
func (u *ResourceUpsert) UpdateScopeKind() *ResourceUpsert {
	u.SetExcluded(resource.FieldScopeKind)
	return u
}

// SetScopeRef sets the "scope_ref" field.
func (u *ResourceUpsert) SetScopeRef(v string) *ResourceUpsert {
	u.Set(resource.FieldScopeRef, v)
	return u
}

// UpdateScopeRef sets the "scope_ref" field to the value that was provided on create.
func (u *ResourceUpsert) UpdateScopeRef() *ResourceUpsert {
	u.SetExcluded(resource.FieldScopeRef)
	return u
}

// SetNodeID sets the "node_id" field.
func (u *ResourceUpsert) SetNodeID(v string) *ResourceUpsert {
	u.Set(resource.FieldNodeID, v)
	return u
}

// UpdateNodeID sets the "node_id" field to the value that was provided on create.
func (u *ResourceUpsert) UpdateNodeID() *ResourceUpsert {
	u.SetExcluded(resource.FieldNodeID)
	return u
}

// SetState sets the "state" field.
func (u *ResourceUpsert) SetState(v string) *ResourceUpsert {
	u.Set(resource.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *ResourceUpsert) UpdateState() *ResourceUpsert {
	u.SetExcluded(resource.FieldState)
	return u
}

// SetVersion sets the "version" field.
func (u *ResourceUpsert) SetVersion(v string) *ResourceUpsert {
	u.Set(resource.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ResourceUpsert) UpdateVersion() *ResourceUpsert {
	u.SetExcluded(resource.FieldVersion)
	return u
}

// SetOrigin sets the "origin" field.
func (u *ResourceUpsert) SetOrigin(v string) *ResourceUpsert {
	u.Set(resource.FieldOrigin, v)
	return u
}

// UpdateOrigin sets the "origin" field to the value that was provided on create.
func (u *ResourceUpsert) UpdateOrigin() *ResourceUpsert {
	u.SetExcluded(resource.FieldOrigin)
	return u
}

// SetOriginRef sets the "origin_ref" field.
func (u *ResourceUpsert) SetOriginRef(v string) *ResourceUpsert {
	u.Set(resource.FieldOriginRef, v)
	return u
}

// UpdateOriginRef sets the "origin_ref" field to the value that was provided on create.
func (u *ResourceUpsert) UpdateOriginRef() *ResourceUpsert {
	u.SetExcluded(resource.FieldOriginRef)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Resource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(resource.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ResourceUpsertOne) UpdateNewValues() *ResourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(resource.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(resource.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.Kind(); exists {
			s.SetIgnore(resource.FieldKind)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Resource.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ResourceUpsertOne) Ignore() *ResourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResourceUpsertOne) DoNothing() *ResourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResourceCreate.OnConflict
// documentation for more info.
func (u *ResourceUpsertOne) Update(set func(*ResourceUpsert)) *ResourceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResourceUpsertOne) SetUpdatedAt(v time.Time) *ResourceUpsertOne {
	return u.Update(func(s *ResourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResourceUpsertOne) UpdateUpdatedAt() *ResourceUpsertOne {
	return u.Update(func(s *ResourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSlug sets the "slug" field.
func (u *ResourceUpsertOne) SetSlug(v string) *ResourceUpsertOne {
	return u.Update(func(s *ResourceUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *ResourceUpsertOne) UpdateSlug() *ResourceUpsertOne {
	return u.Update(func(s *ResourceUpsert) {
		s.UpdateSlug()
	})
}

// SetName sets the "name" field.
func (u *ResourceUpsertOne) SetName(v string) *ResourceUpsertOne {
	return u.Update(func(s *ResourceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ResourceUpsertOne) UpdateName() *ResourceUpsertOne {
	return u.Update(func(s *ResourceUpsert) {
		s.UpdateName()
	})
}

// SetScopeKind sets the "scope_kind" field.
func (u *ResourceUpsertOne) SetScopeKind(v string) *ResourceUpsertOne {
	return u.Update(func(s *ResourceUpsert) {
		s.SetScopeKind(v)
	})
}

// UpdateScopeKind sets the "scope_kind" field to the value that was provided on create.
func (u *ResourceUpsertOne) UpdateScopeKind() *ResourceUpsertOne {
	return u.Update(func(s *ResourceUpsert) {
		s.UpdateScopeKind()
	})
}

// SetScopeRef sets the "scope_ref" field.
func (u *ResourceUpsertOne) SetScopeRef(v string) *ResourceUpsertOne {
	return u.Update(func(s *ResourceUpsert) {
		s.SetScopeRef(v)
	})
}

// UpdateScopeRef sets the "scope_ref" field to the value that was provided on create.
func (u *ResourceUpsertOne) UpdateScopeRef() *ResourceUpsertOne {
	return u.Update(func(s *ResourceUpsert) {
		s.UpdateScopeRef()
	})
}

// SetNodeID sets the "node_id" field.
func (u *ResourceUpsertOne) SetNodeID(v string) *ResourceUpsertOne {
	return u.Update(func(s *ResourceUpsert) {
		s.SetNodeID(v)
	})
}

// UpdateNodeID sets the "node_id" field to the value that was provided on create.
func (u *ResourceUpsertOne) UpdateNodeID() *ResourceUpsertOne {
	return u.Update(func(s *ResourceUpsert) {
		s.UpdateNodeID()
	})
}

// SetState sets the "state" field.
func (u *ResourceUpsertOne) SetState(v string) *ResourceUpsertOne {
	return u.Update(func(s *ResourceUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *ResourceUpsertOne) UpdateState() *ResourceUpsertOne {
	return u.Update(func(s *ResourceUpsert) {
		s.UpdateState()
	})
}

// SetVersion sets the "version" field.
func (u *ResourceUpsertOne) SetVersion(v string) *ResourceUpsertOne {
	return u.Update(func(s *ResourceUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ResourceUpsertOne) UpdateVersion() *ResourceUpsertOne {
	return u.Update(func(s *ResourceUpsert) {
		s.UpdateVersion()
	})
}

// SetOrigin sets the "origin" field.
func (u *ResourceUpsertOne) SetOrigin(v string) *ResourceUpsertOne {
	return u.Update(func(s *ResourceUpsert) {
		s.SetOrigin(v)
	})
}

// UpdateOrigin sets the "origin" field to the value that was provided on create.
func (u *ResourceUpsertOne) UpdateOrigin() *ResourceUpsertOne {
	return u.Update(func(s *ResourceUpsert) {
		s.UpdateOrigin()
	})
}

// SetOriginRef sets the "origin_ref" field.
func (u *ResourceUpsertOne) SetOriginRef(v string) *ResourceUpsertOne {
	return u.Update(func(s *ResourceUpsert) {
		s.SetOriginRef(v)
	})
}

// UpdateOriginRef sets the "origin_ref" field to the value that was provided on create.
func (u *ResourceUpsertOne) UpdateOriginRef() *ResourceUpsertOne {
	return u.Update(func(s *ResourceUpsert) {
		s.UpdateOriginRef()
	})
}

// Exec executes the query.
func (u *ResourceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResourceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResourceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ResourceUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ResourceUpsertOne.ID is not supported by MySQL driver. Use ResourceUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ResourceUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ResourceCreateBulk is the builder for creating many Resource entities in bulk.
type ResourceCreateBulk struct {
	config
	err      error
	builders []*ResourceCreate
	conflict []sql.ConflictOption
}

// Save creates the Resource entities in the database.
func (_c *ResourceCreateBulk) Save(ctx context.Context) ([]*Resource, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Resource, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResourceCreateBulk) SaveX(ctx context.Context) []*Resource {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResourceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResourceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Resource.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResourceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ResourceCreateBulk) OnConflict(opts ...sql.ConflictOption) *ResourceUpsertBulk {
	_c.conflict = opts
	return &ResourceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Resource.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResourceCreateBulk) OnConflictColumns(columns ...string) *ResourceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResourceUpsertBulk{
		create: _c,
	}
}

// ResourceUpsertBulk is the builder for "upsert"-ing
// a bulk of Resource nodes.
type ResourceUpsertBulk struct {
	create *ResourceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Resource.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(resource.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ResourceUpsertBulk) UpdateNewValues() *ResourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(resource.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(resource.FieldCreatedAt)
			}
			if _, exists := b.mutation.Kind(); exists {
				s.SetIgnore(resource.FieldKind)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Resource.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ResourceUpsertBulk) Ignore() *ResourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResourceUpsertBulk) DoNothing() *ResourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResourceCreateBulk.OnConflict
// documentation for more info.
func (u *ResourceUpsertBulk) Update(set func(*ResourceUpsert)) *ResourceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResourceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ResourceUpsertBulk) SetUpdatedAt(v time.Time) *ResourceUpsertBulk {
	return u.Update(func(s *ResourceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ResourceUpsertBulk) UpdateUpdatedAt() *ResourceUpsertBulk {
	return u.Update(func(s *ResourceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSlug sets the "slug" field.
func (u *ResourceUpsertBulk) SetSlug(v string) *ResourceUpsertBulk {
	return u.Update(func(s *ResourceUpsert) {
		s.SetSlug(v)
	})
}

// UpdateSlug sets the "slug" field to the value that was provided on create.
func (u *ResourceUpsertBulk) UpdateSlug() *ResourceUpsertBulk {
	return u.Update(func(s *ResourceUpsert) {
		s.UpdateSlug()
	})
}

// SetName sets the "name" field.
func (u *ResourceUpsertBulk) SetName(v string) *ResourceUpsertBulk {
	return u.Update(func(s *ResourceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ResourceUpsertBulk) UpdateName() *ResourceUpsertBulk {
	return u.Update(func(s *ResourceUpsert) {
		s.UpdateName()
	})
}

// SetScopeKind sets the "scope_kind" field.
func (u *ResourceUpsertBulk) SetScopeKind(v string) *ResourceUpsertBulk {
	return u.Update(func(s *ResourceUpsert) {
		s.SetScopeKind(v)
	})
}

// UpdateScopeKind sets the "scope_kind" field to the value that was provided on create.
func (u *ResourceUpsertBulk) UpdateScopeKind() *ResourceUpsertBulk {
	return u.Update(func(s *ResourceUpsert) {
		s.UpdateScopeKind()
	})
}

// SetScopeRef sets the "scope_ref" field.
func (u *ResourceUpsertBulk) SetScopeRef(v string) *ResourceUpsertBulk {
	return u.Update(func(s *ResourceUpsert) {
		s.SetScopeRef(v)
	})
}

// UpdateScopeRef sets the "scope_ref" field to the value that was provided on create.
func (u *ResourceUpsertBulk) UpdateScopeRef() *ResourceUpsertBulk {
	return u.Update(func(s *ResourceUpsert) {
		s.UpdateScopeRef()
	})
}

// SetNodeID sets the "node_id" field.
func (u *ResourceUpsertBulk) SetNodeID(v string) *ResourceUpsertBulk {
	return u.Update(func(s *ResourceUpsert) {
		s.SetNodeID(v)
	})
}

// UpdateNodeID sets the "node_id" field to the value that was provided on create.
func (u *ResourceUpsertBulk) UpdateNodeID() *ResourceUpsertBulk {
	return u.Update(func(s *ResourceUpsert) {
		s.UpdateNodeID()
	})
}

// SetState sets the "state" field.
func (u *ResourceUpsertBulk) SetState(v string) *ResourceUpsertBulk {
	return u.Update(func(s *ResourceUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *ResourceUpsertBulk) UpdateState() *ResourceUpsertBulk {
	return u.Update(func(s *ResourceUpsert) {
		s.UpdateState()
	})
}

// SetVersion sets the "version" field.
func (u *ResourceUpsertBulk) SetVersion(v string) *ResourceUpsertBulk {
	return u.Update(func(s *ResourceUpsert) {
		s.SetVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ResourceUpsertBulk) UpdateVersion() *ResourceUpsertBulk {
	return u.Update(func(s *ResourceUpsert) {
		s.UpdateVersion()
	})
}

// SetOrigin sets the "origin" field.
func (u *ResourceUpsertBulk) SetOrigin(v string) *ResourceUpsertBulk {
	return u.Update(func(s *ResourceUpsert) {
		s.SetOrigin(v)
	})
}

// UpdateOrigin sets the "origin" field to the value that was provided on create.
func (u *ResourceUpsertBulk) UpdateOrigin() *ResourceUpsertBulk {
	return u.Update(func(s *ResourceUpsert) {
		s.UpdateOrigin()
	})
}

// SetOriginRef sets the "origin_ref" field.
func (u *ResourceUpsertBulk) SetOriginRef(v string) *ResourceUpsertBulk {
	return u.Update(func(s *ResourceUpsert) {
		s.SetOriginRef(v)
	})
}

// UpdateOriginRef sets the "origin_ref" field to the value that was provided on create.
func (u *ResourceUpsertBulk) UpdateOriginRef() *ResourceUpsertBulk {
	return u.Update(func(s *ResourceUpsert) {
		s.UpdateOriginRef()
	})
}

// Exec executes the query.
func (u *ResourceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ResourceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResourceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResourceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
