// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/kontor/server/internal/db/ent/predicate"
	"github.com/lx-wnk/kontor/server/internal/db/ent/spawner"
)

// SpawnerUpdate is the builder for updating Spawner entities.
type SpawnerUpdate struct {
	config
	hooks    []Hook
	mutation *SpawnerMutation
}

// Where appends a list predicates to the SpawnerUpdate builder.
func (_u *SpawnerUpdate) Where(ps ...predicate.Spawner) *SpawnerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SpawnerUpdate) SetName(v string) *SpawnerUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SpawnerUpdate) SetNillableName(v *string) *SpawnerUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *SpawnerUpdate) SetSlug(v string) *SpawnerUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *SpawnerUpdate) SetNillableSlug(v *string) *SpawnerUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetCommand sets the "command" field.
func (_u *SpawnerUpdate) SetCommand(v string) *SpawnerUpdate {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *SpawnerUpdate) SetNillableCommand(v *string) *SpawnerUpdate {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// SetArgs sets the "args" field.
func (_u *SpawnerUpdate) SetArgs(v []string) *SpawnerUpdate {
	_u.mutation.SetArgs(v)
	return _u
}

// AppendArgs appends value to the "args" field.
func (_u *SpawnerUpdate) AppendArgs(v []string) *SpawnerUpdate {
	_u.mutation.AppendArgs(v)
	return _u
}

// SetEnv sets the "env" field.
func (_u *SpawnerUpdate) SetEnv(v map[string]string) *SpawnerUpdate {
	_u.mutation.SetEnv(v)
	return _u
}

// SetAdapterType sets the "adapter_type" field.
func (_u *SpawnerUpdate) SetAdapterType(v string) *SpawnerUpdate {
	_u.mutation.SetAdapterType(v)
	return _u
}

// SetNillableAdapterType sets the "adapter_type" field if the given value is not nil.
func (_u *SpawnerUpdate) SetNillableAdapterType(v *string) *SpawnerUpdate {
	if v != nil {
		_u.SetAdapterType(*v)
	}
	return _u
}

// SetAdapterConfig sets the "adapter_config" field.
func (_u *SpawnerUpdate) SetAdapterConfig(v map[string]string) *SpawnerUpdate {
	_u.mutation.SetAdapterConfig(v)
	return _u
}

// SetModelOverride sets the "model_override" field.
func (_u *SpawnerUpdate) SetModelOverride(v string) *SpawnerUpdate {
	_u.mutation.SetModelOverride(v)
	return _u
}

// SetNillableModelOverride sets the "model_override" field if the given value is not nil.
func (_u *SpawnerUpdate) SetNillableModelOverride(v *string) *SpawnerUpdate {
	if v != nil {
		_u.SetModelOverride(*v)
	}
	return _u
}

// ClearModelOverride clears the value of the "model_override" field.
func (_u *SpawnerUpdate) ClearModelOverride() *SpawnerUpdate {
	_u.mutation.ClearModelOverride()
	return _u
}

// SetDescription sets the "description" field.
func (_u *SpawnerUpdate) SetDescription(v string) *SpawnerUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SpawnerUpdate) SetNillableDescription(v *string) *SpawnerUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SpawnerUpdate) ClearDescription() *SpawnerUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetBuiltIn sets the "built_in" field.
func (_u *SpawnerUpdate) SetBuiltIn(v bool) *SpawnerUpdate {
	_u.mutation.SetBuiltIn(v)
	return _u
}

// SetNillableBuiltIn sets the "built_in" field if the given value is not nil.
func (_u *SpawnerUpdate) SetNillableBuiltIn(v *bool) *SpawnerUpdate {
	if v != nil {
		_u.SetBuiltIn(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *SpawnerUpdate) SetIsDefault(v bool) *SpawnerUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *SpawnerUpdate) SetNillableIsDefault(v *bool) *SpawnerUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SpawnerUpdate) SetUpdatedAt(v time.Time) *SpawnerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SpawnerMutation object of the builder.
func (_u *SpawnerUpdate) Mutation() *SpawnerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SpawnerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SpawnerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SpawnerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SpawnerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SpawnerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := spawner.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SpawnerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(spawner.Table, spawner.Columns, sqlgraph.NewFieldSpec(spawner.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(spawner.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(spawner.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(spawner.FieldCommand, field.TypeString, value)
	}
	if value, ok := _u.mutation.Args(); ok {
		_spec.SetField(spawner.FieldArgs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedArgs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, spawner.FieldArgs, value)
		})
	}
	if value, ok := _u.mutation.Env(); ok {
		_spec.SetField(spawner.FieldEnv, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AdapterType(); ok {
		_spec.SetField(spawner.FieldAdapterType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AdapterConfig(); ok {
		_spec.SetField(spawner.FieldAdapterConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ModelOverride(); ok {
		_spec.SetField(spawner.FieldModelOverride, field.TypeString, value)
	}
	if _u.mutation.ModelOverrideCleared() {
		_spec.ClearField(spawner.FieldModelOverride, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(spawner.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(spawner.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.BuiltIn(); ok {
		_spec.SetField(spawner.FieldBuiltIn, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(spawner.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(spawner.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{spawner.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SpawnerUpdateOne is the builder for updating a single Spawner entity.
type SpawnerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SpawnerMutation
}

// SetName sets the "name" field.
func (_u *SpawnerUpdateOne) SetName(v string) *SpawnerUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SpawnerUpdateOne) SetNillableName(v *string) *SpawnerUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *SpawnerUpdateOne) SetSlug(v string) *SpawnerUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *SpawnerUpdateOne) SetNillableSlug(v *string) *SpawnerUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetCommand sets the "command" field.
func (_u *SpawnerUpdateOne) SetCommand(v string) *SpawnerUpdateOne {
	_u.mutation.SetCommand(v)
	return _u
}

// SetNillableCommand sets the "command" field if the given value is not nil.
func (_u *SpawnerUpdateOne) SetNillableCommand(v *string) *SpawnerUpdateOne {
	if v != nil {
		_u.SetCommand(*v)
	}
	return _u
}

// SetArgs sets the "args" field.
func (_u *SpawnerUpdateOne) SetArgs(v []string) *SpawnerUpdateOne {
	_u.mutation.SetArgs(v)
	return _u
}

// AppendArgs appends value to the "args" field.
func (_u *SpawnerUpdateOne) AppendArgs(v []string) *SpawnerUpdateOne {
	_u.mutation.AppendArgs(v)
	return _u
}

// SetEnv sets the "env" field.
func (_u *SpawnerUpdateOne) SetEnv(v map[string]string) *SpawnerUpdateOne {
	_u.mutation.SetEnv(v)
	return _u
}

// SetAdapterType sets the "adapter_type" field.
func (_u *SpawnerUpdateOne) SetAdapterType(v string) *SpawnerUpdateOne {
	_u.mutation.SetAdapterType(v)
	return _u
}

// SetNillableAdapterType sets the "adapter_type" field if the given value is not nil.
func (_u *SpawnerUpdateOne) SetNillableAdapterType(v *string) *SpawnerUpdateOne {
	if v != nil {
		_u.SetAdapterType(*v)
	}
	return _u
}

// SetAdapterConfig sets the "adapter_config" field.
func (_u *SpawnerUpdateOne) SetAdapterConfig(v map[string]string) *SpawnerUpdateOne {
	_u.mutation.SetAdapterConfig(v)
	return _u
}

// SetModelOverride sets the "model_override" field.
func (_u *SpawnerUpdateOne) SetModelOverride(v string) *SpawnerUpdateOne {
	_u.mutation.SetModelOverride(v)
	return _u
}

// SetNillableModelOverride sets the "model_override" field if the given value is not nil.
func (_u *SpawnerUpdateOne) SetNillableModelOverride(v *string) *SpawnerUpdateOne {
	if v != nil {
		_u.SetModelOverride(*v)
	}
	return _u
}

// ClearModelOverride clears the value of the "model_override" field.
func (_u *SpawnerUpdateOne) ClearModelOverride() *SpawnerUpdateOne {
	_u.mutation.ClearModelOverride()
	return _u
}

// SetDescription sets the "description" field.
func (_u *SpawnerUpdateOne) SetDescription(v string) *SpawnerUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SpawnerUpdateOne) SetNillableDescription(v *string) *SpawnerUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SpawnerUpdateOne) ClearDescription() *SpawnerUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetBuiltIn sets the "built_in" field.
func (_u *SpawnerUpdateOne) SetBuiltIn(v bool) *SpawnerUpdateOne {
	_u.mutation.SetBuiltIn(v)
	return _u
}

// SetNillableBuiltIn sets the "built_in" field if the given value is not nil.
func (_u *SpawnerUpdateOne) SetNillableBuiltIn(v *bool) *SpawnerUpdateOne {
	if v != nil {
		_u.SetBuiltIn(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *SpawnerUpdateOne) SetIsDefault(v bool) *SpawnerUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *SpawnerUpdateOne) SetNillableIsDefault(v *bool) *SpawnerUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SpawnerUpdateOne) SetUpdatedAt(v time.Time) *SpawnerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SpawnerMutation object of the builder.
func (_u *SpawnerUpdateOne) Mutation() *SpawnerMutation {
	return _u.mutation
}

// Where appends a list predicates to the SpawnerUpdate builder.
func (_u *SpawnerUpdateOne) Where(ps ...predicate.Spawner) *SpawnerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SpawnerUpdateOne) Select(field string, fields ...string) *SpawnerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Spawner entity.
func (_u *SpawnerUpdateOne) Save(ctx context.Context) (*Spawner, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SpawnerUpdateOne) SaveX(ctx context.Context) *Spawner {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SpawnerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SpawnerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SpawnerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := spawner.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SpawnerUpdateOne) sqlSave(ctx context.Context) (_node *Spawner, err error) {
	_spec := sqlgraph.NewUpdateSpec(spawner.Table, spawner.Columns, sqlgraph.NewFieldSpec(spawner.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Spawner.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, spawner.FieldID)
		for _, f := range fields {
			if !spawner.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != spawner.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(spawner.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(spawner.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Command(); ok {
		_spec.SetField(spawner.FieldCommand, field.TypeString, value)
	}
	if value, ok := _u.mutation.Args(); ok {
		_spec.SetField(spawner.FieldArgs, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedArgs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, spawner.FieldArgs, value)
		})
	}
	if value, ok := _u.mutation.Env(); ok {
		_spec.SetField(spawner.FieldEnv, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AdapterType(); ok {
		_spec.SetField(spawner.FieldAdapterType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AdapterConfig(); ok {
		_spec.SetField(spawner.FieldAdapterConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.ModelOverride(); ok {
		_spec.SetField(spawner.FieldModelOverride, field.TypeString, value)
	}
	if _u.mutation.ModelOverrideCleared() {
		_spec.ClearField(spawner.FieldModelOverride, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(spawner.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(spawner.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.BuiltIn(); ok {
		_spec.SetField(spawner.FieldBuiltIn, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(spawner.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(spawner.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Spawner{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{spawner.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
