// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/kontor/server/internal/db/ent/systemprompt"
)

// SystemPromptCreate is the builder for creating a SystemPrompt entity.
type SystemPromptCreate struct {
	config
	mutation *SystemPromptMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetScope sets the "scope" field.
func (_c *SystemPromptCreate) SetScope(v string) *SystemPromptCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_c *SystemPromptCreate) SetNillableScope(v *string) *SystemPromptCreate {
	if v != nil {
		_c.SetScope(*v)
	}
	return _c
}

// SetStage sets the "stage" field.
func (_c *SystemPromptCreate) SetStage(v string) *SystemPromptCreate {
	_c.mutation.SetStage(v)
	return _c
}

// SetNillableStage sets the "stage" field if the given value is not nil.
func (_c *SystemPromptCreate) SetNillableStage(v *string) *SystemPromptCreate {
	if v != nil {
		_c.SetStage(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *SystemPromptCreate) SetContent(v string) *SystemPromptCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *SystemPromptCreate) SetPriority(v int) *SystemPromptCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *SystemPromptCreate) SetNillablePriority(v *int) *SystemPromptCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SystemPromptCreate) SetCreatedBy(v string) *SystemPromptCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *SystemPromptCreate) SetNillableCreatedBy(v *string) *SystemPromptCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SystemPromptCreate) SetCreatedAt(v time.Time) *SystemPromptCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SystemPromptCreate) SetNillableCreatedAt(v *time.Time) *SystemPromptCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SystemPromptCreate) SetUpdatedAt(v time.Time) *SystemPromptCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SystemPromptCreate) SetNillableUpdatedAt(v *time.Time) *SystemPromptCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SystemPromptCreate) SetID(v string) *SystemPromptCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SystemPromptMutation object of the builder.
func (_c *SystemPromptCreate) Mutation() *SystemPromptMutation {
	return _c.mutation
}

// Save creates the SystemPrompt in the database.
func (_c *SystemPromptCreate) Save(ctx context.Context) (*SystemPrompt, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SystemPromptCreate) SaveX(ctx context.Context) *SystemPrompt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SystemPromptCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SystemPromptCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SystemPromptCreate) defaults() {
	if _, ok := _c.mutation.Scope(); !ok {
		v := systemprompt.DefaultScope
		_c.mutation.SetScope(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := systemprompt.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := systemprompt.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := systemprompt.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SystemPromptCreate) check() error {
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "SystemPrompt.scope"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "SystemPrompt.content"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "SystemPrompt.priority"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SystemPrompt.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SystemPrompt.updated_at"`)}
	}
	return nil
}

func (_c *SystemPromptCreate) sqlSave(ctx context.Context) (*SystemPrompt, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SystemPrompt.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SystemPromptCreate) createSpec() (*SystemPrompt, *sqlgraph.CreateSpec) {
	var (
		_node = &SystemPrompt{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(systemprompt.Table, sqlgraph.NewFieldSpec(systemprompt.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(systemprompt.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.Stage(); ok {
		_spec.SetField(systemprompt.FieldStage, field.TypeString, value)
		_node.Stage = &value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(systemprompt.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(systemprompt.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(systemprompt.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(systemprompt.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(systemprompt.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SystemPrompt.Create().
//		SetScope(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SystemPromptUpsert) {
//			SetScope(v+v).
//		}).
//		Exec(ctx)
func (_c *SystemPromptCreate) OnConflict(opts ...sql.ConflictOption) *SystemPromptUpsertOne {
	_c.conflict = opts
	return &SystemPromptUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SystemPrompt.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SystemPromptCreate) OnConflictColumns(columns ...string) *SystemPromptUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SystemPromptUpsertOne{
		create: _c,
	}
}

type (
	// SystemPromptUpsertOne is the builder for "upsert"-ing
	//  one SystemPrompt node.
	SystemPromptUpsertOne struct {
		create *SystemPromptCreate
	}

	// SystemPromptUpsert is the "OnConflict" setter.
	SystemPromptUpsert struct {
		*sql.UpdateSet
	}
)

// SetScope sets the "scope" field.
func (u *SystemPromptUpsert) SetScope(v string) *SystemPromptUpsert {
	u.Set(systemprompt.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *SystemPromptUpsert) UpdateScope() *SystemPromptUpsert {
	u.SetExcluded(systemprompt.FieldScope)
	return u
}

// SetStage sets the "stage" field.
func (u *SystemPromptUpsert) SetStage(v string) *SystemPromptUpsert {
	u.Set(systemprompt.FieldStage, v)
	return u
}

// UpdateStage sets the "stage" field to the value that was provided on create.
func (u *SystemPromptUpsert) UpdateStage() *SystemPromptUpsert {
	u.SetExcluded(systemprompt.FieldStage)
	return u
}

// ClearStage clears the value of the "stage" field.
func (u *SystemPromptUpsert) ClearStage() *SystemPromptUpsert {
	u.SetNull(systemprompt.FieldStage)
	return u
}

// SetContent sets the "content" field.
func (u *SystemPromptUpsert) SetContent(v string) *SystemPromptUpsert {
	u.Set(systemprompt.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *SystemPromptUpsert) UpdateContent() *SystemPromptUpsert {
	u.SetExcluded(systemprompt.FieldContent)
	return u
}

// SetPriority sets the "priority" field.
func (u *SystemPromptUpsert) SetPriority(v int) *SystemPromptUpsert {
	u.Set(systemprompt.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *SystemPromptUpsert) UpdatePriority() *SystemPromptUpsert {
	u.SetExcluded(systemprompt.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *SystemPromptUpsert) AddPriority(v int) *SystemPromptUpsert {
	u.Add(systemprompt.FieldPriority, v)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *SystemPromptUpsert) SetCreatedBy(v string) *SystemPromptUpsert {
	u.Set(systemprompt.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SystemPromptUpsert) UpdateCreatedBy() *SystemPromptUpsert {
	u.SetExcluded(systemprompt.FieldCreatedBy)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *SystemPromptUpsert) ClearCreatedBy() *SystemPromptUpsert {
	u.SetNull(systemprompt.FieldCreatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SystemPromptUpsert) SetUpdatedAt(v time.Time) *SystemPromptUpsert {
	u.Set(systemprompt.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SystemPromptUpsert) UpdateUpdatedAt() *SystemPromptUpsert {
	u.SetExcluded(systemprompt.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SystemPrompt.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(systemprompt.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SystemPromptUpsertOne) UpdateNewValues() *SystemPromptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(systemprompt.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(systemprompt.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SystemPrompt.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SystemPromptUpsertOne) Ignore() *SystemPromptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SystemPromptUpsertOne) DoNothing() *SystemPromptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SystemPromptCreate.OnConflict
// documentation for more info.
func (u *SystemPromptUpsertOne) Update(set func(*SystemPromptUpsert)) *SystemPromptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SystemPromptUpsert{UpdateSet: update})
	}))
	return u
}

// SetScope sets the "scope" field.
func (u *SystemPromptUpsertOne) SetScope(v string) *SystemPromptUpsertOne {
	return u.Update(func(s *SystemPromptUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *SystemPromptUpsertOne) UpdateScope() *SystemPromptUpsertOne {
	return u.Update(func(s *SystemPromptUpsert) {
		s.UpdateScope()
	})
}

// SetStage sets the "stage" field.
func (u *SystemPromptUpsertOne) SetStage(v string) *SystemPromptUpsertOne {
	return u.Update(func(s *SystemPromptUpsert) {
		s.SetStage(v)
	})
}

// UpdateStage sets the "stage" field to the value that was provided on create.
func (u *SystemPromptUpsertOne) UpdateStage() *SystemPromptUpsertOne {
	return u.Update(func(s *SystemPromptUpsert) {
		s.UpdateStage()
	})
}

// ClearStage clears the value of the "stage" field.
func (u *SystemPromptUpsertOne) ClearStage() *SystemPromptUpsertOne {
	return u.Update(func(s *SystemPromptUpsert) {
		s.ClearStage()
	})
}

// SetContent sets the "content" field.
func (u *SystemPromptUpsertOne) SetContent(v string) *SystemPromptUpsertOne {
	return u.Update(func(s *SystemPromptUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *SystemPromptUpsertOne) UpdateContent() *SystemPromptUpsertOne {
	return u.Update(func(s *SystemPromptUpsert) {
		s.UpdateContent()
	})
}

// SetPriority sets the "priority" field.
func (u *SystemPromptUpsertOne) SetPriority(v int) *SystemPromptUpsertOne {
	return u.Update(func(s *SystemPromptUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *SystemPromptUpsertOne) AddPriority(v int) *SystemPromptUpsertOne {
	return u.Update(func(s *SystemPromptUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *SystemPromptUpsertOne) UpdatePriority() *SystemPromptUpsertOne {
	return u.Update(func(s *SystemPromptUpsert) {
		s.UpdatePriority()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *SystemPromptUpsertOne) SetCreatedBy(v string) *SystemPromptUpsertOne {
	return u.Update(func(s *SystemPromptUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SystemPromptUpsertOne) UpdateCreatedBy() *SystemPromptUpsertOne {
	return u.Update(func(s *SystemPromptUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *SystemPromptUpsertOne) ClearCreatedBy() *SystemPromptUpsertOne {
	return u.Update(func(s *SystemPromptUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SystemPromptUpsertOne) SetUpdatedAt(v time.Time) *SystemPromptUpsertOne {
	return u.Update(func(s *SystemPromptUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SystemPromptUpsertOne) UpdateUpdatedAt() *SystemPromptUpsertOne {
	return u.Update(func(s *SystemPromptUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SystemPromptUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SystemPromptCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SystemPromptUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SystemPromptUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SystemPromptUpsertOne.ID is not supported by MySQL driver. Use SystemPromptUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SystemPromptUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SystemPromptCreateBulk is the builder for creating many SystemPrompt entities in bulk.
type SystemPromptCreateBulk struct {
	config
	err      error
	builders []*SystemPromptCreate
	conflict []sql.ConflictOption
}

// Save creates the SystemPrompt entities in the database.
func (_c *SystemPromptCreateBulk) Save(ctx context.Context) ([]*SystemPrompt, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SystemPrompt, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SystemPromptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SystemPromptCreateBulk) SaveX(ctx context.Context) []*SystemPrompt {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SystemPromptCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SystemPromptCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SystemPrompt.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SystemPromptUpsert) {
//			SetScope(v+v).
//		}).
//		Exec(ctx)
func (_c *SystemPromptCreateBulk) OnConflict(opts ...sql.ConflictOption) *SystemPromptUpsertBulk {
	_c.conflict = opts
	return &SystemPromptUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SystemPrompt.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SystemPromptCreateBulk) OnConflictColumns(columns ...string) *SystemPromptUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SystemPromptUpsertBulk{
		create: _c,
	}
}

// SystemPromptUpsertBulk is the builder for "upsert"-ing
// a bulk of SystemPrompt nodes.
type SystemPromptUpsertBulk struct {
	create *SystemPromptCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SystemPrompt.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(systemprompt.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SystemPromptUpsertBulk) UpdateNewValues() *SystemPromptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(systemprompt.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(systemprompt.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SystemPrompt.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SystemPromptUpsertBulk) Ignore() *SystemPromptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SystemPromptUpsertBulk) DoNothing() *SystemPromptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SystemPromptCreateBulk.OnConflict
// documentation for more info.
func (u *SystemPromptUpsertBulk) Update(set func(*SystemPromptUpsert)) *SystemPromptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SystemPromptUpsert{UpdateSet: update})
	}))
	return u
}

// SetScope sets the "scope" field.
func (u *SystemPromptUpsertBulk) SetScope(v string) *SystemPromptUpsertBulk {
	return u.Update(func(s *SystemPromptUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *SystemPromptUpsertBulk) UpdateScope() *SystemPromptUpsertBulk {
	return u.Update(func(s *SystemPromptUpsert) {
		s.UpdateScope()
	})
}

// SetStage sets the "stage" field.
func (u *SystemPromptUpsertBulk) SetStage(v string) *SystemPromptUpsertBulk {
	return u.Update(func(s *SystemPromptUpsert) {
		s.SetStage(v)
	})
}

// UpdateStage sets the "stage" field to the value that was provided on create.
func (u *SystemPromptUpsertBulk) UpdateStage() *SystemPromptUpsertBulk {
	return u.Update(func(s *SystemPromptUpsert) {
		s.UpdateStage()
	})
}

// ClearStage clears the value of the "stage" field.
func (u *SystemPromptUpsertBulk) ClearStage() *SystemPromptUpsertBulk {
	return u.Update(func(s *SystemPromptUpsert) {
		s.ClearStage()
	})
}

// SetContent sets the "content" field.
func (u *SystemPromptUpsertBulk) SetContent(v string) *SystemPromptUpsertBulk {
	return u.Update(func(s *SystemPromptUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *SystemPromptUpsertBulk) UpdateContent() *SystemPromptUpsertBulk {
	return u.Update(func(s *SystemPromptUpsert) {
		s.UpdateContent()
	})
}

// SetPriority sets the "priority" field.
func (u *SystemPromptUpsertBulk) SetPriority(v int) *SystemPromptUpsertBulk {
	return u.Update(func(s *SystemPromptUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *SystemPromptUpsertBulk) AddPriority(v int) *SystemPromptUpsertBulk {
	return u.Update(func(s *SystemPromptUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *SystemPromptUpsertBulk) UpdatePriority() *SystemPromptUpsertBulk {
	return u.Update(func(s *SystemPromptUpsert) {
		s.UpdatePriority()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *SystemPromptUpsertBulk) SetCreatedBy(v string) *SystemPromptUpsertBulk {
	return u.Update(func(s *SystemPromptUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SystemPromptUpsertBulk) UpdateCreatedBy() *SystemPromptUpsertBulk {
	return u.Update(func(s *SystemPromptUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *SystemPromptUpsertBulk) ClearCreatedBy() *SystemPromptUpsertBulk {
	return u.Update(func(s *SystemPromptUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SystemPromptUpsertBulk) SetUpdatedAt(v time.Time) *SystemPromptUpsertBulk {
	return u.Update(func(s *SystemPromptUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SystemPromptUpsertBulk) UpdateUpdatedAt() *SystemPromptUpsertBulk {
	return u.Update(func(s *SystemPromptUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SystemPromptUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SystemPromptCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SystemPromptCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SystemPromptUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
