// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/kontor/server/internal/db/ent/predicate"
	"github.com/lx-wnk/kontor/server/internal/db/ent/taskschedule"
)

// TaskScheduleUpdate is the builder for updating TaskSchedule entities.
type TaskScheduleUpdate struct {
	config
	hooks    []Hook
	mutation *TaskScheduleMutation
}

// Where appends a list predicates to the TaskScheduleUpdate builder.
func (_u *TaskScheduleUpdate) Where(ps ...predicate.TaskSchedule) *TaskScheduleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TaskScheduleUpdate) SetName(v string) *TaskScheduleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableName(v *string) *TaskScheduleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *TaskScheduleUpdate) SetEnabled(v bool) *TaskScheduleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableEnabled(v *bool) *TaskScheduleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetNlText sets the "nl_text" field.
func (_u *TaskScheduleUpdate) SetNlText(v string) *TaskScheduleUpdate {
	_u.mutation.SetNlText(v)
	return _u
}

// SetNillableNlText sets the "nl_text" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableNlText(v *string) *TaskScheduleUpdate {
	if v != nil {
		_u.SetNlText(*v)
	}
	return _u
}

// ClearNlText clears the value of the "nl_text" field.
func (_u *TaskScheduleUpdate) ClearNlText() *TaskScheduleUpdate {
	_u.mutation.ClearNlText()
	return _u
}

// SetCronExpr sets the "cron_expr" field.
func (_u *TaskScheduleUpdate) SetCronExpr(v string) *TaskScheduleUpdate {
	_u.mutation.SetCronExpr(v)
	return _u
}

// SetNillableCronExpr sets the "cron_expr" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableCronExpr(v *string) *TaskScheduleUpdate {
	if v != nil {
		_u.SetCronExpr(*v)
	}
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *TaskScheduleUpdate) SetTimezone(v string) *TaskScheduleUpdate {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableTimezone(v *string) *TaskScheduleUpdate {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetCatchup sets the "catchup" field.
func (_u *TaskScheduleUpdate) SetCatchup(v string) *TaskScheduleUpdate {
	_u.mutation.SetCatchup(v)
	return _u
}

// SetNillableCatchup sets the "catchup" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableCatchup(v *string) *TaskScheduleUpdate {
	if v != nil {
		_u.SetCatchup(*v)
	}
	return _u
}

// SetSlugPrefix sets the "slug_prefix" field.
func (_u *TaskScheduleUpdate) SetSlugPrefix(v string) *TaskScheduleUpdate {
	_u.mutation.SetSlugPrefix(v)
	return _u
}

// SetNillableSlugPrefix sets the "slug_prefix" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableSlugPrefix(v *string) *TaskScheduleUpdate {
	if v != nil {
		_u.SetSlugPrefix(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *TaskScheduleUpdate) SetTitle(v string) *TaskScheduleUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableTitle(v *string) *TaskScheduleUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskScheduleUpdate) SetDescription(v string) *TaskScheduleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableDescription(v *string) *TaskScheduleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskScheduleUpdate) ClearDescription() *TaskScheduleUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetCwd sets the "cwd" field.
func (_u *TaskScheduleUpdate) SetCwd(v string) *TaskScheduleUpdate {
	_u.mutation.SetCwd(v)
	return _u
}

// SetNillableCwd sets the "cwd" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableCwd(v *string) *TaskScheduleUpdate {
	if v != nil {
		_u.SetCwd(*v)
	}
	return _u
}

// SetSourceBranch sets the "source_branch" field.
func (_u *TaskScheduleUpdate) SetSourceBranch(v string) *TaskScheduleUpdate {
	_u.mutation.SetSourceBranch(v)
	return _u
}

// SetNillableSourceBranch sets the "source_branch" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableSourceBranch(v *string) *TaskScheduleUpdate {
	if v != nil {
		_u.SetSourceBranch(*v)
	}
	return _u
}

// ClearSourceBranch clears the value of the "source_branch" field.
func (_u *TaskScheduleUpdate) ClearSourceBranch() *TaskScheduleUpdate {
	_u.mutation.ClearSourceBranch()
	return _u
}

// SetTargetBranch sets the "target_branch" field.
func (_u *TaskScheduleUpdate) SetTargetBranch(v string) *TaskScheduleUpdate {
	_u.mutation.SetTargetBranch(v)
	return _u
}

// SetNillableTargetBranch sets the "target_branch" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableTargetBranch(v *string) *TaskScheduleUpdate {
	if v != nil {
		_u.SetTargetBranch(*v)
	}
	return _u
}

// ClearTargetBranch clears the value of the "target_branch" field.
func (_u *TaskScheduleUpdate) ClearTargetBranch() *TaskScheduleUpdate {
	_u.mutation.ClearTargetBranch()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TaskScheduleUpdate) SetPriority(v string) *TaskScheduleUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillablePriority(v *string) *TaskScheduleUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetRunMode sets the "run_mode" field.
func (_u *TaskScheduleUpdate) SetRunMode(v string) *TaskScheduleUpdate {
	_u.mutation.SetRunMode(v)
	return _u
}

// SetNillableRunMode sets the "run_mode" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableRunMode(v *string) *TaskScheduleUpdate {
	if v != nil {
		_u.SetRunMode(*v)
	}
	return _u
}

// SetMaxIterations sets the "max_iterations" field.
func (_u *TaskScheduleUpdate) SetMaxIterations(v int) *TaskScheduleUpdate {
	_u.mutation.ResetMaxIterations()
	_u.mutation.SetMaxIterations(v)
	return _u
}

// SetNillableMaxIterations sets the "max_iterations" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableMaxIterations(v *int) *TaskScheduleUpdate {
	if v != nil {
		_u.SetMaxIterations(*v)
	}
	return _u
}

// AddMaxIterations adds value to the "max_iterations" field.
func (_u *TaskScheduleUpdate) AddMaxIterations(v int) *TaskScheduleUpdate {
	_u.mutation.AddMaxIterations(v)
	return _u
}

// SetTokenBudget sets the "token_budget" field.
func (_u *TaskScheduleUpdate) SetTokenBudget(v int) *TaskScheduleUpdate {
	_u.mutation.ResetTokenBudget()
	_u.mutation.SetTokenBudget(v)
	return _u
}

// SetNillableTokenBudget sets the "token_budget" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableTokenBudget(v *int) *TaskScheduleUpdate {
	if v != nil {
		_u.SetTokenBudget(*v)
	}
	return _u
}

// AddTokenBudget adds value to the "token_budget" field.
func (_u *TaskScheduleUpdate) AddTokenBudget(v int) *TaskScheduleUpdate {
	_u.mutation.AddTokenBudget(v)
	return _u
}

// ClearTokenBudget clears the value of the "token_budget" field.
func (_u *TaskScheduleUpdate) ClearTokenBudget() *TaskScheduleUpdate {
	_u.mutation.ClearTokenBudget()
	return _u
}

// SetCostBudgetCents sets the "cost_budget_cents" field.
func (_u *TaskScheduleUpdate) SetCostBudgetCents(v int) *TaskScheduleUpdate {
	_u.mutation.ResetCostBudgetCents()
	_u.mutation.SetCostBudgetCents(v)
	return _u
}

// SetNillableCostBudgetCents sets the "cost_budget_cents" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableCostBudgetCents(v *int) *TaskScheduleUpdate {
	if v != nil {
		_u.SetCostBudgetCents(*v)
	}
	return _u
}

// AddCostBudgetCents adds value to the "cost_budget_cents" field.
func (_u *TaskScheduleUpdate) AddCostBudgetCents(v int) *TaskScheduleUpdate {
	_u.mutation.AddCostBudgetCents(v)
	return _u
}

// ClearCostBudgetCents clears the value of the "cost_budget_cents" field.
func (_u *TaskScheduleUpdate) ClearCostBudgetCents() *TaskScheduleUpdate {
	_u.mutation.ClearCostBudgetCents()
	return _u
}

// SetStageTimeoutSeconds sets the "stage_timeout_seconds" field.
func (_u *TaskScheduleUpdate) SetStageTimeoutSeconds(v int) *TaskScheduleUpdate {
	_u.mutation.ResetStageTimeoutSeconds()
	_u.mutation.SetStageTimeoutSeconds(v)
	return _u
}

// SetNillableStageTimeoutSeconds sets the "stage_timeout_seconds" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableStageTimeoutSeconds(v *int) *TaskScheduleUpdate {
	if v != nil {
		_u.SetStageTimeoutSeconds(*v)
	}
	return _u
}

// AddStageTimeoutSeconds adds value to the "stage_timeout_seconds" field.
func (_u *TaskScheduleUpdate) AddStageTimeoutSeconds(v int) *TaskScheduleUpdate {
	_u.mutation.AddStageTimeoutSeconds(v)
	return _u
}

// SetSilverBullet sets the "silver_bullet" field.
func (_u *TaskScheduleUpdate) SetSilverBullet(v bool) *TaskScheduleUpdate {
	_u.mutation.SetSilverBullet(v)
	return _u
}

// SetNillableSilverBullet sets the "silver_bullet" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableSilverBullet(v *bool) *TaskScheduleUpdate {
	if v != nil {
		_u.SetSilverBullet(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *TaskScheduleUpdate) SetProjectID(v string) *TaskScheduleUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableProjectID(v *string) *TaskScheduleUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *TaskScheduleUpdate) ClearProjectID() *TaskScheduleUpdate {
	_u.mutation.ClearProjectID()
	return _u
}

// SetSpawnerID sets the "spawner_id" field.
func (_u *TaskScheduleUpdate) SetSpawnerID(v string) *TaskScheduleUpdate {
	_u.mutation.SetSpawnerID(v)
	return _u
}

// SetNillableSpawnerID sets the "spawner_id" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableSpawnerID(v *string) *TaskScheduleUpdate {
	if v != nil {
		_u.SetSpawnerID(*v)
	}
	return _u
}

// ClearSpawnerID clears the value of the "spawner_id" field.
func (_u *TaskScheduleUpdate) ClearSpawnerID() *TaskScheduleUpdate {
	_u.mutation.ClearSpawnerID()
	return _u
}

// SetPermissionTemplate sets the "permission_template" field.
func (_u *TaskScheduleUpdate) SetPermissionTemplate(v string) *TaskScheduleUpdate {
	_u.mutation.SetPermissionTemplate(v)
	return _u
}

// SetNillablePermissionTemplate sets the "permission_template" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillablePermissionTemplate(v *string) *TaskScheduleUpdate {
	if v != nil {
		_u.SetPermissionTemplate(*v)
	}
	return _u
}

// ClearPermissionTemplate clears the value of the "permission_template" field.
func (_u *TaskScheduleUpdate) ClearPermissionTemplate() *TaskScheduleUpdate {
	_u.mutation.ClearPermissionTemplate()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *TaskScheduleUpdate) SetMetadata(v map[string]interface{}) *TaskScheduleUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *TaskScheduleUpdate) ClearMetadata() *TaskScheduleUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetNextRunAt sets the "next_run_at" field.
func (_u *TaskScheduleUpdate) SetNextRunAt(v time.Time) *TaskScheduleUpdate {
	_u.mutation.SetNextRunAt(v)
	return _u
}

// SetNillableNextRunAt sets the "next_run_at" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableNextRunAt(v *time.Time) *TaskScheduleUpdate {
	if v != nil {
		_u.SetNextRunAt(*v)
	}
	return _u
}

// ClearNextRunAt clears the value of the "next_run_at" field.
func (_u *TaskScheduleUpdate) ClearNextRunAt() *TaskScheduleUpdate {
	_u.mutation.ClearNextRunAt()
	return _u
}

// SetLastRunAt sets the "last_run_at" field.
func (_u *TaskScheduleUpdate) SetLastRunAt(v time.Time) *TaskScheduleUpdate {
	_u.mutation.SetLastRunAt(v)
	return _u
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableLastRunAt(v *time.Time) *TaskScheduleUpdate {
	if v != nil {
		_u.SetLastRunAt(*v)
	}
	return _u
}

// ClearLastRunAt clears the value of the "last_run_at" field.
func (_u *TaskScheduleUpdate) ClearLastRunAt() *TaskScheduleUpdate {
	_u.mutation.ClearLastRunAt()
	return _u
}

// SetLastTaskID sets the "last_task_id" field.
func (_u *TaskScheduleUpdate) SetLastTaskID(v string) *TaskScheduleUpdate {
	_u.mutation.SetLastTaskID(v)
	return _u
}

// SetNillableLastTaskID sets the "last_task_id" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableLastTaskID(v *string) *TaskScheduleUpdate {
	if v != nil {
		_u.SetLastTaskID(*v)
	}
	return _u
}

// ClearLastTaskID clears the value of the "last_task_id" field.
func (_u *TaskScheduleUpdate) ClearLastTaskID() *TaskScheduleUpdate {
	_u.mutation.ClearLastTaskID()
	return _u
}

// SetLastSkippedAt sets the "last_skipped_at" field.
func (_u *TaskScheduleUpdate) SetLastSkippedAt(v time.Time) *TaskScheduleUpdate {
	_u.mutation.SetLastSkippedAt(v)
	return _u
}

// SetNillableLastSkippedAt sets the "last_skipped_at" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableLastSkippedAt(v *time.Time) *TaskScheduleUpdate {
	if v != nil {
		_u.SetLastSkippedAt(*v)
	}
	return _u
}

// ClearLastSkippedAt clears the value of the "last_skipped_at" field.
func (_u *TaskScheduleUpdate) ClearLastSkippedAt() *TaskScheduleUpdate {
	_u.mutation.ClearLastSkippedAt()
	return _u
}

// SetSkippedCount sets the "skipped_count" field.
func (_u *TaskScheduleUpdate) SetSkippedCount(v int) *TaskScheduleUpdate {
	_u.mutation.ResetSkippedCount()
	_u.mutation.SetSkippedCount(v)
	return _u
}

// SetNillableSkippedCount sets the "skipped_count" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableSkippedCount(v *int) *TaskScheduleUpdate {
	if v != nil {
		_u.SetSkippedCount(*v)
	}
	return _u
}

// AddSkippedCount adds value to the "skipped_count" field.
func (_u *TaskScheduleUpdate) AddSkippedCount(v int) *TaskScheduleUpdate {
	_u.mutation.AddSkippedCount(v)
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *TaskScheduleUpdate) SetResourceID(v string) *TaskScheduleUpdate {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableResourceID(v *string) *TaskScheduleUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *TaskScheduleUpdate) ClearResourceID() *TaskScheduleUpdate {
	_u.mutation.ClearResourceID()
	return _u
}

// SetApplications sets the "applications" field.
func (_u *TaskScheduleUpdate) SetApplications(v []string) *TaskScheduleUpdate {
	_u.mutation.SetApplications(v)
	return _u
}

// AppendApplications appends value to the "applications" field.
func (_u *TaskScheduleUpdate) AppendApplications(v []string) *TaskScheduleUpdate {
	_u.mutation.AppendApplications(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TaskScheduleUpdate) SetUserID(v string) *TaskScheduleUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TaskScheduleUpdate) SetNillableUserID(v *string) *TaskScheduleUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *TaskScheduleUpdate) ClearUserID() *TaskScheduleUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskScheduleUpdate) SetUpdatedAt(v time.Time) *TaskScheduleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TaskScheduleMutation object of the builder.
func (_u *TaskScheduleUpdate) Mutation() *TaskScheduleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskScheduleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskScheduleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskScheduleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskScheduleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskScheduleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := taskschedule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskScheduleUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := taskschedule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TaskSchedule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SlugPrefix(); ok {
		if err := taskschedule.SlugPrefixValidator(v); err != nil {
			return &ValidationError{Name: "slug_prefix", err: fmt.Errorf(`ent: validator failed for field "TaskSchedule.slug_prefix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := taskschedule.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "TaskSchedule.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Cwd(); ok {
		if err := taskschedule.CwdValidator(v); err != nil {
			return &ValidationError{Name: "cwd", err: fmt.Errorf(`ent: validator failed for field "TaskSchedule.cwd": %w`, err)}
		}
	}
	return nil
}

func (_u *TaskScheduleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskschedule.Table, taskschedule.Columns, sqlgraph.NewFieldSpec(taskschedule.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(taskschedule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(taskschedule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NlText(); ok {
		_spec.SetField(taskschedule.FieldNlText, field.TypeString, value)
	}
	if _u.mutation.NlTextCleared() {
		_spec.ClearField(taskschedule.FieldNlText, field.TypeString)
	}
	if value, ok := _u.mutation.CronExpr(); ok {
		_spec.SetField(taskschedule.FieldCronExpr, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(taskschedule.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Catchup(); ok {
		_spec.SetField(taskschedule.FieldCatchup, field.TypeString, value)
	}
	if value, ok := _u.mutation.SlugPrefix(); ok {
		_spec.SetField(taskschedule.FieldSlugPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(taskschedule.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(taskschedule.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(taskschedule.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Cwd(); ok {
		_spec.SetField(taskschedule.FieldCwd, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceBranch(); ok {
		_spec.SetField(taskschedule.FieldSourceBranch, field.TypeString, value)
	}
	if _u.mutation.SourceBranchCleared() {
		_spec.ClearField(taskschedule.FieldSourceBranch, field.TypeString)
	}
	if value, ok := _u.mutation.TargetBranch(); ok {
		_spec.SetField(taskschedule.FieldTargetBranch, field.TypeString, value)
	}
	if _u.mutation.TargetBranchCleared() {
		_spec.ClearField(taskschedule.FieldTargetBranch, field.TypeString)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(taskschedule.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunMode(); ok {
		_spec.SetField(taskschedule.FieldRunMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxIterations(); ok {
		_spec.SetField(taskschedule.FieldMaxIterations, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxIterations(); ok {
		_spec.AddField(taskschedule.FieldMaxIterations, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TokenBudget(); ok {
		_spec.SetField(taskschedule.FieldTokenBudget, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenBudget(); ok {
		_spec.AddField(taskschedule.FieldTokenBudget, field.TypeInt, value)
	}
	if _u.mutation.TokenBudgetCleared() {
		_spec.ClearField(taskschedule.FieldTokenBudget, field.TypeInt)
	}
	if value, ok := _u.mutation.CostBudgetCents(); ok {
		_spec.SetField(taskschedule.FieldCostBudgetCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCostBudgetCents(); ok {
		_spec.AddField(taskschedule.FieldCostBudgetCents, field.TypeInt, value)
	}
	if _u.mutation.CostBudgetCentsCleared() {
		_spec.ClearField(taskschedule.FieldCostBudgetCents, field.TypeInt)
	}
	if value, ok := _u.mutation.StageTimeoutSeconds(); ok {
		_spec.SetField(taskschedule.FieldStageTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStageTimeoutSeconds(); ok {
		_spec.AddField(taskschedule.FieldStageTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SilverBullet(); ok {
		_spec.SetField(taskschedule.FieldSilverBullet, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(taskschedule.FieldProjectID, field.TypeString, value)
	}
	if _u.mutation.ProjectIDCleared() {
		_spec.ClearField(taskschedule.FieldProjectID, field.TypeString)
	}
	if value, ok := _u.mutation.SpawnerID(); ok {
		_spec.SetField(taskschedule.FieldSpawnerID, field.TypeString, value)
	}
	if _u.mutation.SpawnerIDCleared() {
		_spec.ClearField(taskschedule.FieldSpawnerID, field.TypeString)
	}
	if value, ok := _u.mutation.PermissionTemplate(); ok {
		_spec.SetField(taskschedule.FieldPermissionTemplate, field.TypeString, value)
	}
	if _u.mutation.PermissionTemplateCleared() {
		_spec.ClearField(taskschedule.FieldPermissionTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(taskschedule.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(taskschedule.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.NextRunAt(); ok {
		_spec.SetField(taskschedule.FieldNextRunAt, field.TypeTime, value)
	}
	if _u.mutation.NextRunAtCleared() {
		_spec.ClearField(taskschedule.FieldNextRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastRunAt(); ok {
		_spec.SetField(taskschedule.FieldLastRunAt, field.TypeTime, value)
	}
	if _u.mutation.LastRunAtCleared() {
		_spec.ClearField(taskschedule.FieldLastRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastTaskID(); ok {
		_spec.SetField(taskschedule.FieldLastTaskID, field.TypeString, value)
	}
	if _u.mutation.LastTaskIDCleared() {
		_spec.ClearField(taskschedule.FieldLastTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.LastSkippedAt(); ok {
		_spec.SetField(taskschedule.FieldLastSkippedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSkippedAtCleared() {
		_spec.ClearField(taskschedule.FieldLastSkippedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SkippedCount(); ok {
		_spec.SetField(taskschedule.FieldSkippedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSkippedCount(); ok {
		_spec.AddField(taskschedule.FieldSkippedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(taskschedule.FieldResourceID, field.TypeString, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(taskschedule.FieldResourceID, field.TypeString)
	}
	if value, ok := _u.mutation.Applications(); ok {
		_spec.SetField(taskschedule.FieldApplications, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedApplications(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, taskschedule.FieldApplications, value)
		})
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(taskschedule.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(taskschedule.FieldUserID, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(taskschedule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskschedule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskScheduleUpdateOne is the builder for updating a single TaskSchedule entity.
type TaskScheduleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TaskScheduleMutation
}

// SetName sets the "name" field.
func (_u *TaskScheduleUpdateOne) SetName(v string) *TaskScheduleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableName(v *string) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *TaskScheduleUpdateOne) SetEnabled(v bool) *TaskScheduleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableEnabled(v *bool) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetNlText sets the "nl_text" field.
func (_u *TaskScheduleUpdateOne) SetNlText(v string) *TaskScheduleUpdateOne {
	_u.mutation.SetNlText(v)
	return _u
}

// SetNillableNlText sets the "nl_text" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableNlText(v *string) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetNlText(*v)
	}
	return _u
}

// ClearNlText clears the value of the "nl_text" field.
func (_u *TaskScheduleUpdateOne) ClearNlText() *TaskScheduleUpdateOne {
	_u.mutation.ClearNlText()
	return _u
}

// SetCronExpr sets the "cron_expr" field.
func (_u *TaskScheduleUpdateOne) SetCronExpr(v string) *TaskScheduleUpdateOne {
	_u.mutation.SetCronExpr(v)
	return _u
}

// SetNillableCronExpr sets the "cron_expr" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableCronExpr(v *string) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetCronExpr(*v)
	}
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *TaskScheduleUpdateOne) SetTimezone(v string) *TaskScheduleUpdateOne {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableTimezone(v *string) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetCatchup sets the "catchup" field.
func (_u *TaskScheduleUpdateOne) SetCatchup(v string) *TaskScheduleUpdateOne {
	_u.mutation.SetCatchup(v)
	return _u
}

// SetNillableCatchup sets the "catchup" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableCatchup(v *string) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetCatchup(*v)
	}
	return _u
}

// SetSlugPrefix sets the "slug_prefix" field.
func (_u *TaskScheduleUpdateOne) SetSlugPrefix(v string) *TaskScheduleUpdateOne {
	_u.mutation.SetSlugPrefix(v)
	return _u
}

// SetNillableSlugPrefix sets the "slug_prefix" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableSlugPrefix(v *string) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetSlugPrefix(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *TaskScheduleUpdateOne) SetTitle(v string) *TaskScheduleUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableTitle(v *string) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskScheduleUpdateOne) SetDescription(v string) *TaskScheduleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableDescription(v *string) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskScheduleUpdateOne) ClearDescription() *TaskScheduleUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetCwd sets the "cwd" field.
func (_u *TaskScheduleUpdateOne) SetCwd(v string) *TaskScheduleUpdateOne {
	_u.mutation.SetCwd(v)
	return _u
}

// SetNillableCwd sets the "cwd" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableCwd(v *string) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetCwd(*v)
	}
	return _u
}

// SetSourceBranch sets the "source_branch" field.
func (_u *TaskScheduleUpdateOne) SetSourceBranch(v string) *TaskScheduleUpdateOne {
	_u.mutation.SetSourceBranch(v)
	return _u
}

// SetNillableSourceBranch sets the "source_branch" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableSourceBranch(v *string) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetSourceBranch(*v)
	}
	return _u
}

// ClearSourceBranch clears the value of the "source_branch" field.
func (_u *TaskScheduleUpdateOne) ClearSourceBranch() *TaskScheduleUpdateOne {
	_u.mutation.ClearSourceBranch()
	return _u
}

// SetTargetBranch sets the "target_branch" field.
func (_u *TaskScheduleUpdateOne) SetTargetBranch(v string) *TaskScheduleUpdateOne {
	_u.mutation.SetTargetBranch(v)
	return _u
}

// SetNillableTargetBranch sets the "target_branch" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableTargetBranch(v *string) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetTargetBranch(*v)
	}
	return _u
}

// ClearTargetBranch clears the value of the "target_branch" field.
func (_u *TaskScheduleUpdateOne) ClearTargetBranch() *TaskScheduleUpdateOne {
	_u.mutation.ClearTargetBranch()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TaskScheduleUpdateOne) SetPriority(v string) *TaskScheduleUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillablePriority(v *string) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetRunMode sets the "run_mode" field.
func (_u *TaskScheduleUpdateOne) SetRunMode(v string) *TaskScheduleUpdateOne {
	_u.mutation.SetRunMode(v)
	return _u
}

// SetNillableRunMode sets the "run_mode" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableRunMode(v *string) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetRunMode(*v)
	}
	return _u
}

// SetMaxIterations sets the "max_iterations" field.
func (_u *TaskScheduleUpdateOne) SetMaxIterations(v int) *TaskScheduleUpdateOne {
	_u.mutation.ResetMaxIterations()
	_u.mutation.SetMaxIterations(v)
	return _u
}

// SetNillableMaxIterations sets the "max_iterations" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableMaxIterations(v *int) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetMaxIterations(*v)
	}
	return _u
}

// AddMaxIterations adds value to the "max_iterations" field.
func (_u *TaskScheduleUpdateOne) AddMaxIterations(v int) *TaskScheduleUpdateOne {
	_u.mutation.AddMaxIterations(v)
	return _u
}

// SetTokenBudget sets the "token_budget" field.
func (_u *TaskScheduleUpdateOne) SetTokenBudget(v int) *TaskScheduleUpdateOne {
	_u.mutation.ResetTokenBudget()
	_u.mutation.SetTokenBudget(v)
	return _u
}

// SetNillableTokenBudget sets the "token_budget" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableTokenBudget(v *int) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetTokenBudget(*v)
	}
	return _u
}

// AddTokenBudget adds value to the "token_budget" field.
func (_u *TaskScheduleUpdateOne) AddTokenBudget(v int) *TaskScheduleUpdateOne {
	_u.mutation.AddTokenBudget(v)
	return _u
}

// ClearTokenBudget clears the value of the "token_budget" field.
func (_u *TaskScheduleUpdateOne) ClearTokenBudget() *TaskScheduleUpdateOne {
	_u.mutation.ClearTokenBudget()
	return _u
}

// SetCostBudgetCents sets the "cost_budget_cents" field.
func (_u *TaskScheduleUpdateOne) SetCostBudgetCents(v int) *TaskScheduleUpdateOne {
	_u.mutation.ResetCostBudgetCents()
	_u.mutation.SetCostBudgetCents(v)
	return _u
}

// SetNillableCostBudgetCents sets the "cost_budget_cents" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableCostBudgetCents(v *int) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetCostBudgetCents(*v)
	}
	return _u
}

// AddCostBudgetCents adds value to the "cost_budget_cents" field.
func (_u *TaskScheduleUpdateOne) AddCostBudgetCents(v int) *TaskScheduleUpdateOne {
	_u.mutation.AddCostBudgetCents(v)
	return _u
}

// ClearCostBudgetCents clears the value of the "cost_budget_cents" field.
func (_u *TaskScheduleUpdateOne) ClearCostBudgetCents() *TaskScheduleUpdateOne {
	_u.mutation.ClearCostBudgetCents()
	return _u
}

// SetStageTimeoutSeconds sets the "stage_timeout_seconds" field.
func (_u *TaskScheduleUpdateOne) SetStageTimeoutSeconds(v int) *TaskScheduleUpdateOne {
	_u.mutation.ResetStageTimeoutSeconds()
	_u.mutation.SetStageTimeoutSeconds(v)
	return _u
}

// SetNillableStageTimeoutSeconds sets the "stage_timeout_seconds" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableStageTimeoutSeconds(v *int) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetStageTimeoutSeconds(*v)
	}
	return _u
}

// AddStageTimeoutSeconds adds value to the "stage_timeout_seconds" field.
func (_u *TaskScheduleUpdateOne) AddStageTimeoutSeconds(v int) *TaskScheduleUpdateOne {
	_u.mutation.AddStageTimeoutSeconds(v)
	return _u
}

// SetSilverBullet sets the "silver_bullet" field.
func (_u *TaskScheduleUpdateOne) SetSilverBullet(v bool) *TaskScheduleUpdateOne {
	_u.mutation.SetSilverBullet(v)
	return _u
}

// SetNillableSilverBullet sets the "silver_bullet" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableSilverBullet(v *bool) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetSilverBullet(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *TaskScheduleUpdateOne) SetProjectID(v string) *TaskScheduleUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableProjectID(v *string) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// ClearProjectID clears the value of the "project_id" field.
func (_u *TaskScheduleUpdateOne) ClearProjectID() *TaskScheduleUpdateOne {
	_u.mutation.ClearProjectID()
	return _u
}

// SetSpawnerID sets the "spawner_id" field.
func (_u *TaskScheduleUpdateOne) SetSpawnerID(v string) *TaskScheduleUpdateOne {
	_u.mutation.SetSpawnerID(v)
	return _u
}

// SetNillableSpawnerID sets the "spawner_id" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableSpawnerID(v *string) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetSpawnerID(*v)
	}
	return _u
}

// ClearSpawnerID clears the value of the "spawner_id" field.
func (_u *TaskScheduleUpdateOne) ClearSpawnerID() *TaskScheduleUpdateOne {
	_u.mutation.ClearSpawnerID()
	return _u
}

// SetPermissionTemplate sets the "permission_template" field.
func (_u *TaskScheduleUpdateOne) SetPermissionTemplate(v string) *TaskScheduleUpdateOne {
	_u.mutation.SetPermissionTemplate(v)
	return _u
}

// SetNillablePermissionTemplate sets the "permission_template" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillablePermissionTemplate(v *string) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetPermissionTemplate(*v)
	}
	return _u
}

// ClearPermissionTemplate clears the value of the "permission_template" field.
func (_u *TaskScheduleUpdateOne) ClearPermissionTemplate() *TaskScheduleUpdateOne {
	_u.mutation.ClearPermissionTemplate()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *TaskScheduleUpdateOne) SetMetadata(v map[string]interface{}) *TaskScheduleUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *TaskScheduleUpdateOne) ClearMetadata() *TaskScheduleUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetNextRunAt sets the "next_run_at" field.
func (_u *TaskScheduleUpdateOne) SetNextRunAt(v time.Time) *TaskScheduleUpdateOne {
	_u.mutation.SetNextRunAt(v)
	return _u
}

// SetNillableNextRunAt sets the "next_run_at" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableNextRunAt(v *time.Time) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetNextRunAt(*v)
	}
	return _u
}

// ClearNextRunAt clears the value of the "next_run_at" field.
func (_u *TaskScheduleUpdateOne) ClearNextRunAt() *TaskScheduleUpdateOne {
	_u.mutation.ClearNextRunAt()
	return _u
}

// SetLastRunAt sets the "last_run_at" field.
func (_u *TaskScheduleUpdateOne) SetLastRunAt(v time.Time) *TaskScheduleUpdateOne {
	_u.mutation.SetLastRunAt(v)
	return _u
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableLastRunAt(v *time.Time) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetLastRunAt(*v)
	}
	return _u
}

// ClearLastRunAt clears the value of the "last_run_at" field.
func (_u *TaskScheduleUpdateOne) ClearLastRunAt() *TaskScheduleUpdateOne {
	_u.mutation.ClearLastRunAt()
	return _u
}

// SetLastTaskID sets the "last_task_id" field.
func (_u *TaskScheduleUpdateOne) SetLastTaskID(v string) *TaskScheduleUpdateOne {
	_u.mutation.SetLastTaskID(v)
	return _u
}

// SetNillableLastTaskID sets the "last_task_id" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableLastTaskID(v *string) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetLastTaskID(*v)
	}
	return _u
}

// ClearLastTaskID clears the value of the "last_task_id" field.
func (_u *TaskScheduleUpdateOne) ClearLastTaskID() *TaskScheduleUpdateOne {
	_u.mutation.ClearLastTaskID()
	return _u
}

// SetLastSkippedAt sets the "last_skipped_at" field.
func (_u *TaskScheduleUpdateOne) SetLastSkippedAt(v time.Time) *TaskScheduleUpdateOne {
	_u.mutation.SetLastSkippedAt(v)
	return _u
}

// SetNillableLastSkippedAt sets the "last_skipped_at" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableLastSkippedAt(v *time.Time) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetLastSkippedAt(*v)
	}
	return _u
}

// ClearLastSkippedAt clears the value of the "last_skipped_at" field.
func (_u *TaskScheduleUpdateOne) ClearLastSkippedAt() *TaskScheduleUpdateOne {
	_u.mutation.ClearLastSkippedAt()
	return _u
}

// SetSkippedCount sets the "skipped_count" field.
func (_u *TaskScheduleUpdateOne) SetSkippedCount(v int) *TaskScheduleUpdateOne {
	_u.mutation.ResetSkippedCount()
	_u.mutation.SetSkippedCount(v)
	return _u
}

// SetNillableSkippedCount sets the "skipped_count" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableSkippedCount(v *int) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetSkippedCount(*v)
	}
	return _u
}

// AddSkippedCount adds value to the "skipped_count" field.
func (_u *TaskScheduleUpdateOne) AddSkippedCount(v int) *TaskScheduleUpdateOne {
	_u.mutation.AddSkippedCount(v)
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *TaskScheduleUpdateOne) SetResourceID(v string) *TaskScheduleUpdateOne {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableResourceID(v *string) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *TaskScheduleUpdateOne) ClearResourceID() *TaskScheduleUpdateOne {
	_u.mutation.ClearResourceID()
	return _u
}

// SetApplications sets the "applications" field.
func (_u *TaskScheduleUpdateOne) SetApplications(v []string) *TaskScheduleUpdateOne {
	_u.mutation.SetApplications(v)
	return _u
}

// AppendApplications appends value to the "applications" field.
func (_u *TaskScheduleUpdateOne) AppendApplications(v []string) *TaskScheduleUpdateOne {
	_u.mutation.AppendApplications(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TaskScheduleUpdateOne) SetUserID(v string) *TaskScheduleUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TaskScheduleUpdateOne) SetNillableUserID(v *string) *TaskScheduleUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *TaskScheduleUpdateOne) ClearUserID() *TaskScheduleUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TaskScheduleUpdateOne) SetUpdatedAt(v time.Time) *TaskScheduleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the TaskScheduleMutation object of the builder.
func (_u *TaskScheduleUpdateOne) Mutation() *TaskScheduleMutation {
	return _u.mutation
}

// Where appends a list predicates to the TaskScheduleUpdate builder.
func (_u *TaskScheduleUpdateOne) Where(ps ...predicate.TaskSchedule) *TaskScheduleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskScheduleUpdateOne) Select(field string, fields ...string) *TaskScheduleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TaskSchedule entity.
func (_u *TaskScheduleUpdateOne) Save(ctx context.Context) (*TaskSchedule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskScheduleUpdateOne) SaveX(ctx context.Context) *TaskSchedule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskScheduleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskScheduleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TaskScheduleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := taskschedule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskScheduleUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := taskschedule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TaskSchedule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SlugPrefix(); ok {
		if err := taskschedule.SlugPrefixValidator(v); err != nil {
			return &ValidationError{Name: "slug_prefix", err: fmt.Errorf(`ent: validator failed for field "TaskSchedule.slug_prefix": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := taskschedule.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "TaskSchedule.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Cwd(); ok {
		if err := taskschedule.CwdValidator(v); err != nil {
			return &ValidationError{Name: "cwd", err: fmt.Errorf(`ent: validator failed for field "TaskSchedule.cwd": %w`, err)}
		}
	}
	return nil
}

func (_u *TaskScheduleUpdateOne) sqlSave(ctx context.Context) (_node *TaskSchedule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskschedule.Table, taskschedule.Columns, sqlgraph.NewFieldSpec(taskschedule.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TaskSchedule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taskschedule.FieldID)
		for _, f := range fields {
			if !taskschedule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != taskschedule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(taskschedule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(taskschedule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.NlText(); ok {
		_spec.SetField(taskschedule.FieldNlText, field.TypeString, value)
	}
	if _u.mutation.NlTextCleared() {
		_spec.ClearField(taskschedule.FieldNlText, field.TypeString)
	}
	if value, ok := _u.mutation.CronExpr(); ok {
		_spec.SetField(taskschedule.FieldCronExpr, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(taskschedule.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Catchup(); ok {
		_spec.SetField(taskschedule.FieldCatchup, field.TypeString, value)
	}
	if value, ok := _u.mutation.SlugPrefix(); ok {
		_spec.SetField(taskschedule.FieldSlugPrefix, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(taskschedule.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(taskschedule.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(taskschedule.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Cwd(); ok {
		_spec.SetField(taskschedule.FieldCwd, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceBranch(); ok {
		_spec.SetField(taskschedule.FieldSourceBranch, field.TypeString, value)
	}
	if _u.mutation.SourceBranchCleared() {
		_spec.ClearField(taskschedule.FieldSourceBranch, field.TypeString)
	}
	if value, ok := _u.mutation.TargetBranch(); ok {
		_spec.SetField(taskschedule.FieldTargetBranch, field.TypeString, value)
	}
	if _u.mutation.TargetBranchCleared() {
		_spec.ClearField(taskschedule.FieldTargetBranch, field.TypeString)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(taskschedule.FieldPriority, field.TypeString, value)
	}
	if value, ok := _u.mutation.RunMode(); ok {
		_spec.SetField(taskschedule.FieldRunMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxIterations(); ok {
		_spec.SetField(taskschedule.FieldMaxIterations, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxIterations(); ok {
		_spec.AddField(taskschedule.FieldMaxIterations, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TokenBudget(); ok {
		_spec.SetField(taskschedule.FieldTokenBudget, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTokenBudget(); ok {
		_spec.AddField(taskschedule.FieldTokenBudget, field.TypeInt, value)
	}
	if _u.mutation.TokenBudgetCleared() {
		_spec.ClearField(taskschedule.FieldTokenBudget, field.TypeInt)
	}
	if value, ok := _u.mutation.CostBudgetCents(); ok {
		_spec.SetField(taskschedule.FieldCostBudgetCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCostBudgetCents(); ok {
		_spec.AddField(taskschedule.FieldCostBudgetCents, field.TypeInt, value)
	}
	if _u.mutation.CostBudgetCentsCleared() {
		_spec.ClearField(taskschedule.FieldCostBudgetCents, field.TypeInt)
	}
	if value, ok := _u.mutation.StageTimeoutSeconds(); ok {
		_spec.SetField(taskschedule.FieldStageTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStageTimeoutSeconds(); ok {
		_spec.AddField(taskschedule.FieldStageTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SilverBullet(); ok {
		_spec.SetField(taskschedule.FieldSilverBullet, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(taskschedule.FieldProjectID, field.TypeString, value)
	}
	if _u.mutation.ProjectIDCleared() {
		_spec.ClearField(taskschedule.FieldProjectID, field.TypeString)
	}
	if value, ok := _u.mutation.SpawnerID(); ok {
		_spec.SetField(taskschedule.FieldSpawnerID, field.TypeString, value)
	}
	if _u.mutation.SpawnerIDCleared() {
		_spec.ClearField(taskschedule.FieldSpawnerID, field.TypeString)
	}
	if value, ok := _u.mutation.PermissionTemplate(); ok {
		_spec.SetField(taskschedule.FieldPermissionTemplate, field.TypeString, value)
	}
	if _u.mutation.PermissionTemplateCleared() {
		_spec.ClearField(taskschedule.FieldPermissionTemplate, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(taskschedule.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(taskschedule.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.NextRunAt(); ok {
		_spec.SetField(taskschedule.FieldNextRunAt, field.TypeTime, value)
	}
	if _u.mutation.NextRunAtCleared() {
		_spec.ClearField(taskschedule.FieldNextRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastRunAt(); ok {
		_spec.SetField(taskschedule.FieldLastRunAt, field.TypeTime, value)
	}
	if _u.mutation.LastRunAtCleared() {
		_spec.ClearField(taskschedule.FieldLastRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastTaskID(); ok {
		_spec.SetField(taskschedule.FieldLastTaskID, field.TypeString, value)
	}
	if _u.mutation.LastTaskIDCleared() {
		_spec.ClearField(taskschedule.FieldLastTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.LastSkippedAt(); ok {
		_spec.SetField(taskschedule.FieldLastSkippedAt, field.TypeTime, value)
	}
	if _u.mutation.LastSkippedAtCleared() {
		_spec.ClearField(taskschedule.FieldLastSkippedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SkippedCount(); ok {
		_spec.SetField(taskschedule.FieldSkippedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSkippedCount(); ok {
		_spec.AddField(taskschedule.FieldSkippedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(taskschedule.FieldResourceID, field.TypeString, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(taskschedule.FieldResourceID, field.TypeString)
	}
	if value, ok := _u.mutation.Applications(); ok {
		_spec.SetField(taskschedule.FieldApplications, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedApplications(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, taskschedule.FieldApplications, value)
		})
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(taskschedule.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(taskschedule.FieldUserID, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(taskschedule.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &TaskSchedule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskschedule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
