// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lx-wnk/kontor/server/internal/db/ent/taskschedule"
)

// TaskSchedule is the model entity for the TaskSchedule schema.
type TaskSchedule struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// NlText holds the value of the "nl_text" field.
	NlText *string `json:"nl_text,omitempty"`
	// CronExpr holds the value of the "cron_expr" field.
	CronExpr string `json:"cron_expr,omitempty"`
	// Timezone holds the value of the "timezone" field.
	Timezone string `json:"timezone,omitempty"`
	// Catchup holds the value of the "catchup" field.
	Catchup string `json:"catchup,omitempty"`
	// SlugPrefix holds the value of the "slug_prefix" field.
	SlugPrefix string `json:"slug_prefix,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Cwd holds the value of the "cwd" field.
	Cwd string `json:"cwd,omitempty"`
	// SourceBranch holds the value of the "source_branch" field.
	SourceBranch *string `json:"source_branch,omitempty"`
	// TargetBranch holds the value of the "target_branch" field.
	TargetBranch *string `json:"target_branch,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority string `json:"priority,omitempty"`
	// RunMode holds the value of the "run_mode" field.
	RunMode string `json:"run_mode,omitempty"`
	// MaxIterations holds the value of the "max_iterations" field.
	MaxIterations int `json:"max_iterations,omitempty"`
	// TokenBudget holds the value of the "token_budget" field.
	TokenBudget *int `json:"token_budget,omitempty"`
	// CostBudgetCents holds the value of the "cost_budget_cents" field.
	CostBudgetCents *int `json:"cost_budget_cents,omitempty"`
	// SilverBullet holds the value of the "silver_bullet" field.
	SilverBullet bool `json:"silver_bullet,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID *string `json:"project_id,omitempty"`
	// SpawnerID holds the value of the "spawner_id" field.
	SpawnerID *string `json:"spawner_id,omitempty"`
	// PermissionTemplate holds the value of the "permission_template" field.
	PermissionTemplate *string `json:"permission_template,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// NextRunAt holds the value of the "next_run_at" field.
	NextRunAt *time.Time `json:"next_run_at,omitempty"`
	// LastRunAt holds the value of the "last_run_at" field.
	LastRunAt *time.Time `json:"last_run_at,omitempty"`
	// LastTaskID holds the value of the "last_task_id" field.
	LastTaskID *string `json:"last_task_id,omitempty"`
	// LastSkippedAt holds the value of the "last_skipped_at" field.
	LastSkippedAt *time.Time `json:"last_skipped_at,omitempty"`
	// SkippedCount holds the value of the "skipped_count" field.
	SkippedCount int `json:"skipped_count,omitempty"`
	// ResourceID holds the value of the "resource_id" field.
	ResourceID string `json:"resource_id,omitempty"`
	// OwnerModule holds the value of the "owner_module" field.
	OwnerModule string `json:"owner_module,omitempty"`
	// Applications holds the value of the "applications" field.
	Applications []string `json:"applications,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID *string `json:"user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TaskSchedule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case taskschedule.FieldMetadata, taskschedule.FieldApplications:
			values[i] = new([]byte)
		case taskschedule.FieldEnabled, taskschedule.FieldSilverBullet:
			values[i] = new(sql.NullBool)
		case taskschedule.FieldMaxIterations, taskschedule.FieldTokenBudget, taskschedule.FieldCostBudgetCents, taskschedule.FieldSkippedCount:
			values[i] = new(sql.NullInt64)
		case taskschedule.FieldID, taskschedule.FieldName, taskschedule.FieldNlText, taskschedule.FieldCronExpr, taskschedule.FieldTimezone, taskschedule.FieldCatchup, taskschedule.FieldSlugPrefix, taskschedule.FieldTitle, taskschedule.FieldDescription, taskschedule.FieldCwd, taskschedule.FieldSourceBranch, taskschedule.FieldTargetBranch, taskschedule.FieldPriority, taskschedule.FieldRunMode, taskschedule.FieldProjectID, taskschedule.FieldSpawnerID, taskschedule.FieldPermissionTemplate, taskschedule.FieldLastTaskID, taskschedule.FieldResourceID, taskschedule.FieldOwnerModule, taskschedule.FieldUserID:
			values[i] = new(sql.NullString)
		case taskschedule.FieldNextRunAt, taskschedule.FieldLastRunAt, taskschedule.FieldLastSkippedAt, taskschedule.FieldCreatedAt, taskschedule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TaskSchedule fields.
func (_m *TaskSchedule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case taskschedule.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case taskschedule.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case taskschedule.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case taskschedule.FieldNlText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nl_text", values[i])
			} else if value.Valid {
				_m.NlText = new(string)
				*_m.NlText = value.String
			}
		case taskschedule.FieldCronExpr:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cron_expr", values[i])
			} else if value.Valid {
				_m.CronExpr = value.String
			}
		case taskschedule.FieldTimezone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field timezone", values[i])
			} else if value.Valid {
				_m.Timezone = value.String
			}
		case taskschedule.FieldCatchup:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field catchup", values[i])
			} else if value.Valid {
				_m.Catchup = value.String
			}
		case taskschedule.FieldSlugPrefix:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug_prefix", values[i])
			} else if value.Valid {
				_m.SlugPrefix = value.String
			}
		case taskschedule.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case taskschedule.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case taskschedule.FieldCwd:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cwd", values[i])
			} else if value.Valid {
				_m.Cwd = value.String
			}
		case taskschedule.FieldSourceBranch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_branch", values[i])
			} else if value.Valid {
				_m.SourceBranch = new(string)
				*_m.SourceBranch = value.String
			}
		case taskschedule.FieldTargetBranch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_branch", values[i])
			} else if value.Valid {
				_m.TargetBranch = new(string)
				*_m.TargetBranch = value.String
			}
		case taskschedule.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = value.String
			}
		case taskschedule.FieldRunMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field run_mode", values[i])
			} else if value.Valid {
				_m.RunMode = value.String
			}
		case taskschedule.FieldMaxIterations:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_iterations", values[i])
			} else if value.Valid {
				_m.MaxIterations = int(value.Int64)
			}
		case taskschedule.FieldTokenBudget:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field token_budget", values[i])
			} else if value.Valid {
				_m.TokenBudget = new(int)
				*_m.TokenBudget = int(value.Int64)
			}
		case taskschedule.FieldCostBudgetCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cost_budget_cents", values[i])
			} else if value.Valid {
				_m.CostBudgetCents = new(int)
				*_m.CostBudgetCents = int(value.Int64)
			}
		case taskschedule.FieldSilverBullet:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field silver_bullet", values[i])
			} else if value.Valid {
				_m.SilverBullet = value.Bool
			}
		case taskschedule.FieldProjectID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = new(string)
				*_m.ProjectID = value.String
			}
		case taskschedule.FieldSpawnerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field spawner_id", values[i])
			} else if value.Valid {
				_m.SpawnerID = new(string)
				*_m.SpawnerID = value.String
			}
		case taskschedule.FieldPermissionTemplate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field permission_template", values[i])
			} else if value.Valid {
				_m.PermissionTemplate = new(string)
				*_m.PermissionTemplate = value.String
			}
		case taskschedule.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case taskschedule.FieldNextRunAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_run_at", values[i])
			} else if value.Valid {
				_m.NextRunAt = new(time.Time)
				*_m.NextRunAt = value.Time
			}
		case taskschedule.FieldLastRunAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_run_at", values[i])
			} else if value.Valid {
				_m.LastRunAt = new(time.Time)
				*_m.LastRunAt = value.Time
			}
		case taskschedule.FieldLastTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_task_id", values[i])
			} else if value.Valid {
				_m.LastTaskID = new(string)
				*_m.LastTaskID = value.String
			}
		case taskschedule.FieldLastSkippedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_skipped_at", values[i])
			} else if value.Valid {
				_m.LastSkippedAt = new(time.Time)
				*_m.LastSkippedAt = value.Time
			}
		case taskschedule.FieldSkippedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field skipped_count", values[i])
			} else if value.Valid {
				_m.SkippedCount = int(value.Int64)
			}
		case taskschedule.FieldResourceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource_id", values[i])
			} else if value.Valid {
				_m.ResourceID = value.String
			}
		case taskschedule.FieldOwnerModule:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field owner_module", values[i])
			} else if value.Valid {
				_m.OwnerModule = value.String
			}
		case taskschedule.FieldApplications:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field applications", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Applications); err != nil {
					return fmt.Errorf("unmarshal field applications: %w", err)
				}
			}
		case taskschedule.FieldUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(string)
				*_m.UserID = value.String
			}
		case taskschedule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case taskschedule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TaskSchedule.
// This includes values selected through modifiers, order, etc.
func (_m *TaskSchedule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TaskSchedule.
// Note that you need to call TaskSchedule.Unwrap() before calling this method if this TaskSchedule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TaskSchedule) Update() *TaskScheduleUpdateOne {
	return NewTaskScheduleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TaskSchedule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TaskSchedule) Unwrap() *TaskSchedule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TaskSchedule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TaskSchedule) String() string {
	var builder strings.Builder
	builder.WriteString("TaskSchedule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	if v := _m.NlText; v != nil {
		builder.WriteString("nl_text=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("cron_expr=")
	builder.WriteString(_m.CronExpr)
	builder.WriteString(", ")
	builder.WriteString("timezone=")
	builder.WriteString(_m.Timezone)
	builder.WriteString(", ")
	builder.WriteString("catchup=")
	builder.WriteString(_m.Catchup)
	builder.WriteString(", ")
	builder.WriteString("slug_prefix=")
	builder.WriteString(_m.SlugPrefix)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("cwd=")
	builder.WriteString(_m.Cwd)
	builder.WriteString(", ")
	if v := _m.SourceBranch; v != nil {
		builder.WriteString("source_branch=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TargetBranch; v != nil {
		builder.WriteString("target_branch=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(_m.Priority)
	builder.WriteString(", ")
	builder.WriteString("run_mode=")
	builder.WriteString(_m.RunMode)
	builder.WriteString(", ")
	builder.WriteString("max_iterations=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxIterations))
	builder.WriteString(", ")
	if v := _m.TokenBudget; v != nil {
		builder.WriteString("token_budget=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CostBudgetCents; v != nil {
		builder.WriteString("cost_budget_cents=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("silver_bullet=")
	builder.WriteString(fmt.Sprintf("%v", _m.SilverBullet))
	builder.WriteString(", ")
	if v := _m.ProjectID; v != nil {
		builder.WriteString("project_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SpawnerID; v != nil {
		builder.WriteString("spawner_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PermissionTemplate; v != nil {
		builder.WriteString("permission_template=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	if v := _m.NextRunAt; v != nil {
		builder.WriteString("next_run_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastRunAt; v != nil {
		builder.WriteString("last_run_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastTaskID; v != nil {
		builder.WriteString("last_task_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastSkippedAt; v != nil {
		builder.WriteString("last_skipped_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("skipped_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkippedCount))
	builder.WriteString(", ")
	builder.WriteString("resource_id=")
	builder.WriteString(_m.ResourceID)
	builder.WriteString(", ")
	builder.WriteString("owner_module=")
	builder.WriteString(_m.OwnerModule)
	builder.WriteString(", ")
	builder.WriteString("applications=")
	builder.WriteString(fmt.Sprintf("%v", _m.Applications))
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TaskSchedules is a parsable slice of TaskSchedule.
type TaskSchedules []*TaskSchedule
